### ISSUE TITLE
Ubuntu derivative support

### ISSUE THREAD

**Issue by Septolum** [netbootxyz/netboot.xyz#100]
Is it possible to add *buntu support, such as xbuntu, or primarily lubuntu as I personally would use

**Comment by Septolum** [comment]
http://www.ubuntu.com/about/about-ubuntu/flavours

http://lubuntu.net

**Comment by antonym** [comment]
Have you tried doing a regular install and then choosing that package set for the derivative you want?

**Comment by Septolum** [comment]
My apologies, I was sure they hosted their own mini.iso, I was misinformed, the ubuntu installation works perfectly

**Comment by antonym** [comment]
Cool, sounds good, thanks!
