### ISSUE TITLE
k3os boot has a bug

### ISSUE THREAD

**Issue by jwells38654** [netbootxyz/netboot.xyz#1002]
### Discussed in https://github.com/netbootxyz/netboot.xyz/discussions/1001

<div type='discussions-op-text'>

<sup>Originally posted by **jwells38654** September 17, 2021</sup>
Can someone fix the netboot.xyz bootstrap file for TFTP to now append /latest/download/k3os.... as it is no longer the correct GitHub URL path to download the K3os images.  Or how can I fix this?  

FYI- Setting the mirror path still appends the incorrect path mention above.</div>

**Comment by antonym** [comment]
Should be fixed with https://github.com/netbootxyz/netboot.xyz/commit/46f0182de9d091c25ef904585b39ba86721a39c3

**Comment by antonym** [comment]
You can test via Development Endpoint via Utilities menu.

**Comment by jwells38654** [comment]
Do I need to download a new netboot.xyz bootstrap file to configure on my TFTP server?
