### ISSUE TITLE
Building Dockerfile-build in submodule fails

### ISSUE THREAD

**Issue by clarsen** [netbootxyz/netboot.xyz#1018]
**Describe the bug**

if netboot.xyz is added as submodule and then we attempt to build it, git running within the docker build fails due to .git being a file instead of a directory (or non-existant) due to COPY bringing it into the container.

**To Reproduce**
1. mkdir test
2. cd test; git init
3. git submodule add https://github.com/netbootxyz/netboot.xyz.git external/netboot.xyz
4. docker build -t localbuild  -f external/netboot.xyz/Dockerfile-build external/netboot.xyz

**Expected behavior**

Successful build

**Screenshots**

Example failure:
```
TASK [netbootxyz : Check out latest iPXE sources] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote https://github.com/ipxe/ipxe -h refs/heads/master", "msg": "fatal: not a git repository: /ansible/../../.git/modules/external/netboot.xyz", "rc": 128, "stderr": "fatal: not a git repository: /ansible/../../.git/modules/external/netboot.xyz\n", "stderr_lines": ["fatal: not a git repository: /ansible/../../.git/modules/external/netboot.xyz"], "stdout": "", "stdout_lines": []}
```

**Additional context**

To fix,  add to .dockerignore:
```
.git
```

**Comment by antonym** [comment]
Thanks!
