### ISSUE TITLE
Archlinux images fail to boot

### ISSUE THREAD

**Issue by coderobe** [netbootxyz/netboot.xyz#102]
The Server that served the PXE images (releng.archlinux.org) was shut down entirely, thus netboot.xyz times out when trying to load http://releng.archlinux.org/pxeboot/boot/pxelinux.0.  
The new netboot images can be found [here](https://www.archlinux.org/releng/netboot/)

**Comment by antonym** [comment]
Thanks for the heads up, I'll look at redoing them this week.  I'll probably adapt something from https://www.archlinux.org/releng/netboot/archlinux.ipxe

**Comment by antonym** [comment]
Fixed with https://github.com/antonym/netboot.xyz/pull/103
