### ISSUE TITLE
Documentation is vague on how to deploy using Docker and how use netbootxyz

### ISSUE THREAD

**Issue by Alex2357** [netbootxyz/netboot.xyz#1030]
The section https://github.com/netbootxyz/netboot.xyz# deploying-with-docker is missing few things.
I have never used any IPXE, but very interested to use it. The step on that page doesn't explain how to deploy netbootxyz and how to use it. I found in another place https://netboot.xyz/docs/docker/#docker-cli but still not sure what is missing.
I have build and I got buildoutput. Then I have started it in Docker container. Checked container logs all looks good. Web interface works ok. Then I created VM using KVM and specified to boot from IPXE. It doesn't boot. It is not clear if I miss any steps on netbootxyz side or I'm doing something wrong in KVM. I personally have more experience with VirtualBox but I have feeling that I have not done something to make netbootxyz work. I have tried nearly all network interfaces in KVM and still no success.

**Expected behavior**
A clear steps how to deploy it using docker and the clear steps how to use it(I mean to validate that it is working).

I understand it might be not a fun to update documentation, but if someone could send the link(s) I could submit PR for documentation. Thanks in advance.

**Comment by antonym** [comment]
I just started working on the Docker docs this week to the main site so still a work in progress. The thing that is missing is you'll need to set up your DHCP boot file and next server to the ip of the host running the docker container. The Docker containers are more for advanced users who want to set up and manipulate their own menu. 

If you are just getting started with iPXE and want to experience the hosted menu, I would add the netboot.xyz ISO to Virtual Box and start from there. That will get you up and running to where you can install operating systems. You can also join our Discord if you have any questions.

But hopefully I will be working on more docs over the coming weeks. The docs are here: https://github.com/netbootxyz/netboot.xyz-docs/tree/master/docs so if you find some stuff missing that would be helpful to PR, it would be very appreciated. Some of the docs pull from the READMEs of some of the repos to avoid duplicate documentation.

**Comment by Alex2357** [comment]
@antonym sorry for the late response. Even if I have many years of experience with VirtualBox, I'm after running iPXE in docker. I wanna have a repo with everything configured and forget about it. 

Thanks for mentioning DHCP boot file. Before that I had a feeling that to make this work I need DHCP server setup. After reading https://networkengineering.stackexchange.com/a/60691/54160 and https://2pintsoftware.com/whitepaper-using-dhcp-uefi-bios-pxe-booting/ I think I'm on the right way.

**Comment by antonym** [comment]
I pushed up some incremental docs as well last week that may help.
