### ISSUE TITLE
"Permission denied" error on NixOS

### ISSUE THREAD

**Issue by MidAutumnMoon** [netbootxyz/netboot.xyz#1050]
**Describe the bug**
The error `Permission denied`(https://ipxe.org/err/020c61) occurs while downloading NixOS.
But any other distros have no problem downloading their files and booting.

I've reproduced this issue on different machines from different locations.

**To Reproduce**
1. Go to `Linux Network Installs`
2. Go to `NixOS`
3. Select any version of NixOS to load

**Expected behavior**
It should load and boot NixOS.

**Screenshots**
![A](https://user-images.githubusercontent.com/27620522/140321737-7522b73d-ed99-46ff-aacc-4dc99a85be1e.png)

**Additional context**

**Comment by antonym** [comment]
Was able to reproduce this, the next release of 2.0.53 should include this upstream fix from iPXE:

https://github.com/ipxe/ipxe/commit/1844aacc837bf81cb1959fa65f2e52dcc70a0cae

It seemed to fix the issue once I switched to that newer iPXE build. Once the next release is pushed, you should be able to download the latest netbook.xyz binaries and see if that fixes the issue.

**Comment by MidAutumnMoon** [comment]
Thanks! I'm looking forward to the updates.

**Comment by antonym** [comment]
Closing as latest release is pushed.

**Comment by MidAutumnMoon** [comment]
Confirmed that this issue is fixed with the latest release :)
