### ISSUE TITLE
iPXE support for secure boot on EFI

### ISSUE THREAD

**Issue by Akrugerus** [netbootxyz/netboot.xyz#1051]
I noticed that iPXE has [build support for secure boot](https://github.com/ipxe/ipxe/commit/7428ab7) on EFI, would it be possible to integrate that to allow for booting into netboot.xyz on systems with secure boot enabled?

**Comment by AlternativeBoi** [comment]
Would love this functionality as well, especially with some games now requiring secure boot on windows 11.

**Comment by antonym** [comment]
Closing for now, no current plans for support for Secure Boot at the moment as the process involves getting Microsoft involved for Code Signing certs. https://ipxe.org/appnote/etoken

I'm open to other ideas though if they come up and if someone is more familiar with the process and we can always revisit in the future.

**Comment by Sporesirius** [comment]
@antonym maybe it would be possible to use a shim? like https://github.com/rhboot/shim
Also found https://github.com/ipxe/shimdemo

**Comment by Timoses** [comment]
Ventoy allows adding its key as trusted which in turn allows secure boot. See https://www.ventoy.net/en/doc_secure.html
