### ISSUE TITLE
fail to boot gparted on network card lacking dhcp

### ISSUE THREAD

**Issue by divinity76** [netbootxyz/netboot.xyz#1055]
**Describe the bug**
when first booting netboot.xyz , it gives up on dhcp and ask you for the connection details; 
after your tell netboot the ip/gateway/mask it will ask you what system to boot: if you choose gparted, this will happen: 
![image](https://user-images.githubusercontent.com/1874996/143318306-a0f3216c-4658-4814-8093-bd307011847b.png)
when it tries to download gparted, it will try dhcp again and fail, this time it won't ask though, it wil just start a busybox shell...

**To Reproduce**
try to boot gparted on a network without dhcp

**Expected behavior**
it should either remember the network settings, or ask again

**Screenshots**
see above

**Additional context**
tested on netboot.xyz version 2.0.53 released 2021-11-22

probably related to, and possibly a duplicate of, #1043 

setting the ip with kernel boot parameters work, eg 

>ip=[DEVICE]:[CLIENT_IP]:[NETMASK]:[GATEWAY_IP]:[NAMESERVER]

important to note that DEVICE must be a iface name like `ens1f0` , just specifying "0" for the first device does not work.

**Comment by sonuyos** [comment]
Same issue, it just wont work.

**Comment by divinity76** [comment]
duplicate of #1043
