### ISSUE TITLE
Support for Clear Linux OS?

### ISSUE THREAD

**Issue by shanoaice** [netbootxyz/netboot.xyz#1058]
**Is your feature request related to a problem? Please describe.**
Clear Linux OS is a Linux distribution developed by Intel, primarily designed with performance and cloud use-cases in mind. The operating system upgrades as a whole rather than using individual packages. Extra software can be added to the system (along with associated dependencies) using pre-compiled bundles which can be accessed through the distribution's swupd software manager. 

**Describe the solution you'd like**
Clear Linux provides an officially built PXE image, so it should be easy to host.

**Describe alternatives you've considered**
Clear Linux also provides ISO images.

**Comment by antonym** [comment]
We looked at this before, but we can look at it again if they've made more recent improvements:

https://github.com/netbootxyz/netboot.xyz/discussions/500

**Comment by shanoaice** [comment]
I see. I remember their PXE image is still data destructive and automated for now, so maybe we should still wait......

**Comment by antonym** [comment]
Closing, we can revisit as things may change.
