### ISSUE TITLE
run virtualbox iso

### ISSUE THREAD

**Issue by edgiru** [netbootxyz/netboot.xyz#106]
hello
Not determined standard network card of Virtualbox not work network Intel PRO/1000 MT Desktop (82540EM). Download any image freezes at 5% -6%, and on the question this is network card: PCnet-PCI II or III (Am79C970A)

**Comment by edgiru** [comment]
Not work Intel PRO/1000 T Server (82543GC)

Ip defined but not loaded: Intel PRO/100 MT Server (82545EM) and screenshot
![default](https://cloud.githubusercontent.com/assets/4624056/16893231/29fc4a2c-4b3a-11e6-8ce7-5619fdc3aa1c.JPG)

**Comment by antonym** [comment]
I'm using the 82545EM NIC without issue on 5.0.24 using NAT mode.

**Comment by antonym** [comment]
There's a thread discussing the latest version of Virtual Box and issues with iPXE here:

http://forum.ipxe.org/showthread.php?tid=8151

**Comment by antonym** [comment]
Also bug has been reported with Virtual Box:

https://www.virtualbox.org/ticket/15846

**Comment by antonym** [comment]
Latest version of Virtual Box has been released which should resolve this issue (5.1.6 - released 2016-09-12):  https://www.virtualbox.org/wiki/Changelog#v6
