### ISSUE TITLE
Support 2.5GB Realtek RTL8125B NIC - Requires kernel 5.9

### ISSUE THREAD

**Issue by TheLinuxGuy** [netbootxyz/netboot.xyz#1062]
**Is your feature request related to a problem? Please describe.**
I am unable to boot and use netboot.xyz on my [MSI MAG B550M MORTAR](https://www.msi.com/Motherboard/MAG-B550M-MORTAR/Specification) motherboard. It fails at detecting the network NIC 2.5GB RTL8125B. 

https://linuxreviews.org/Realtek_RTL_8125 indicates the kernel 5.9 should support this 2.5GB LAN NIC.

**Describe the solution you'd like**
Upgrade netboot.xyz kernel to newer to test native support for RTL8125B 

**Describe alternatives you've considered**
This motherboard has a single NIC and limited slots (all in use). Ideal solution is to support these NIC for everyone as 2.5GB is becoming more commonplace. 

**Additional context**

**Comment by NiKiZe** [comment]
iPXE support has nothing to do with the Linux kernel. More details in ipxe/ipxe#540

**Comment by TheLinuxGuy** [comment]
Is there a precompiled .iso that defaults to undionly.kpxe? the only option I see seems to require DHCP options for netbooting.

https://netboot.xyz/downloads/

**Comment by antonym** [comment]
Support for the NIC would be need to be added upstream in iPXE, closing out here as we don't really manage any of the hardware support but maintain the menus and installers.

undionly options only work with DHCP.
