### ISSUE TITLE
Downloading asset fails on multipart squashfs files (e.g. Ubuntu) bug + "solution"

### ISSUE THREAD

**Issue by benj919** [netbootxyz/netboot.xyz#1068]
**Describe the bug**
Some of the Ubuntu releases have multipart squashfs files , e.g. https://github.com/netbootxyz/ubuntu-squash/releases/tag/20.04.3-9bc4558b when pulling the corresponding assets only the default file (filesystem.squashfs) is downloaded, but not the part2 file (filesystem.squashfs.part2). After changing the config file for ubuntu to look at the local server first booting fails. Manually downloading the part2 file (and possibly chown'ing it) fixes the broken boot.

**To Reproduce**
Pull all 3 assets for a ubuntu distro/flavour ( eg. 20.04, gnonme/default) and set the ipxe server as default server in the ubuntu config. Try to netboot that ubuntu version.

**Expected behavior**
The missing part2 file should be automatically downloaded when pulling the squashfs file

**Screenshots**
x

**Additional context**
Remote assets at version 2.0.54, run using the linuxserver docker image.
Manually downloading and placing the .part2 fixes this.

**Comment by antonym** [comment]
Fix rolled out in webapp 0.6.6 and is in latest netbootxyz container. 

https://github.com/orgs/netbootxyz/packages/container/netbootxyz/13690342?tag=0.6.6-nbxyz1
