### ISSUE TITLE
Flatcar PXE boot is broken in netboot.xyz

### ISSUE THREAD

**Issue by jepio** [netbootxyz/netboot.xyz#1070]
**Describe the bug**

Flatcar PXE booting appears to not work correctly in netboot.xyz. Flatcar ships with an initramfs embedded in the kernel, and a second one that gets overlayed when pxe booting (the second one is passed through the usual iPXE protocol). This works in our testing when `initrd=flatcar_production_pxe_image.cpio.gz` is provided on the kernel command line. Since commit https://github.com/netbootxyz/netboot.xyz/commit/efc9fa5dd1db42bf6f3ebbfe54097729446d3a39#diff-d3aefe4b4c58d9e9d91f58b6fe4025dae8cd5578e0e9f0f944e109fbcbf6db19 an `initrd=initrd.magic` parameter is passed instead and this breaks boot, as the second initramfs is missing.

I tested with netboot.xyz 2.0.40, which didn't have that commit, and UEFI iPXE boot of Flatcar works correctly. BIOS iPXE boot doesn't work in netboot.xyz 2.0.40, so there appears to be a required iPXE fix since then (we test current iPXE builds directly in many environments and those work)

**To Reproduce**
1. fetch netboot.xyz.iso
2. boot in qemu `qemu-system-x86_64 -enable-kvm -m 4096 -smp 2 -cdrom netboot.xyz.iso`
3. "Linux Network Installs" -> "Container Linux by Flatcar" (btw. could we rename that to Flatcar Container Linux?) -> any channel
4. boot gets stuck at "A start job is running for /dev/disk/by-partlabel/USR-A (40s / 1min 30s)" which is a sign that the second initramfs is missing.

**Expected behavior**

Machine boots to login prompt.

**Screenshots**

**Additional context**

**Comment by holymoly** [comment]
The commit solved the issue partly. When booting is using UEFI it works perfectly. When used in Bios mode there is still an error which also was discussed here https://github.com/flatcar-linux/Flatcar/issues/586#issuecomment-1041476482.
`
[    0.932433] Initramfs unpacking failed: invalid magic at start of compressed archive
`
