### ISSUE TITLE
Windows Installers prompt for a Driver

### ISSUE THREAD

**Issue by cpressland** [netbootxyz/netboot.xyz#108]
After extracting both a Windows 7 and Windows 10 ISO onto a CentOS 7.2 Server running Nginx 1.6.3 Netboot successfully boots the ISO, however, the installation cannot run due to some missing driver. My expectation is that this is fundamentally a Windows issue. See attached screenshots. 
![screen shot 2016-08-17 at 13 23 38](https://cloud.githubusercontent.com/assets/6557665/17736610/a8cebb46-6480-11e6-874f-5b47a6b3be45.png)

![screen shot 2016-08-17 at 13 40 15](https://cloud.githubusercontent.com/assets/6557665/17736611/ac523b94-6480-11e6-9b5d-cc8d128a53e8.png)

After the wimboot process starts, I can see the following logging in the Nginx access log:

```
10.166.16.205 - - [17/Aug/2016:15:17:49 +0100] "GET /x64/bootmgr HTTP/1.1" 200 400228 "-" "iPXE/1.0.0+ (f6e8)" "-"
10.166.16.205 - - [17/Aug/2016:15:17:49 +0100] "GET /x64/boot/bcd HTTP/1.1" 200 16384 "-" "iPXE/1.0.0+ (f6e8)" "-"
10.166.16.205 - - [17/Aug/2016:15:17:50 +0100] "GET /x64/boot/boot.sdi HTTP/1.1" 200 3170304 "-" "iPXE/1.0.0+ (f6e8)" "-"
10.166.16.205 - - [17/Aug/2016:15:17:57 +0100] "GET /x64/sources/boot.wim HTTP/1.1" 200 257783122 "-" "iPXE/1.0.0+ (f6e8)" "-"
```

But I'm not seeing any further requests following this, so it would seem like windows is able to boot, but the installer is missing and not loaded from HTTP.

**Comment by antonym** [comment]
See these posts for more info:

http://forum.ipxe.org/showthread.php?tid=7059
http://ipxe.org/howto/winpe

I haven't had time to play around with this myself, but I believe you'll need to kick off the installer from a network share once you're up and running.  Loading the installer itself can't see the media.

**Comment by cpressland** [comment]
Awesome, thanks! Sorry for not researching this in a little more detail. Converted the netboot target to a WinPE image and all was fine.
