### ISSUE TITLE
Add xcpng xen hypervisor ipxe boot

### ISSUE THREAD

**Issue by ITJamie** [netbootxyz/netboot.xyz#1089]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add xcp-ng as an installer option. It is a linux xen hypervisor

**Additional context**
https://xcp-ng.org/docs/install.html#ipxe-over-http-install xcpng already have docs on how to ipxe install

**Comment by ITJamie** [comment]
Bump

**Comment by ITJamie** [comment]
Bump

**Comment by dstecholution** [comment]
Second this, @denzuko might have to look into how to do a PR for this project.

**Comment by tifredfr** [comment]
Hi,

I saw builds of xcpng but there is no menu.ipxe :(

Has anyone created the ipxe entry ?

**Comment by debugrr** [comment]
Bump
