### ISSUE TITLE
Inconsistent use of bootloader_filename and site_name

### ISSUE THREAD

**Issue by abh** [netbootxyz/netboot.xyz#1095]
The templates have a setting for `bootloader_filename`, but in most places `site_name` is used instead. This causes some features to break if `site_name` and `bootloader_filename` aren't set to the same thing.

For example the `tftpmenu` items aren't loaded and the URLs on the index.html page doesn't work.

**Comment by abh** [comment]
Uh, not sure what's expected here. Bad bot?

**Comment by oe3gwu** [comment]
No idea why this is inactive. It is a real issue.

**Comment by abh** [comment]
@oe3gwu I'm not using this actively anymore, but for my use it was fixed by #1096

**Comment by oe3gwu** [comment]
@abh I once looked at it, but actually wasnt aware that it was fixed. This issue should be closed then.

**Comment by abh** [comment]
@oe3gwu no, that change wasn't merged so it shouldn't be closed (but you can try the patch to see if it works for you).

**Comment by oe3gwu** [comment]
This project seems kinda ... dead or inactive at least. If my bugs dont get fixed, I gonna build my own iPXE Server.
