### ISSUE TITLE
Tails Linux doesn't boot from 'Live CD' menu.

### ISSUE THREAD

**Issue by accessiblepixel** [netbootxyz/netboot.xyz#1102]
**Describe the bug**
The Tails Linux entry does not boot, it just drops to the initramfs shell.

**To Reproduce**
Chain boot from boot.netboot.xyz and navigate to Tails Linux and boot from it.

**Expected behavior**
Tails Linux should boot normally.

**Screenshots**

N/A

**Additional context**

No entries are added to /boot.log.

Kind regards,
Jessica

**Comment by antonym** [comment]
You may need to increase the memory to 8GB or so to boot it. I was able to boot it 4.27 with 8GB in a VM.

**Comment by accessiblepixel** [comment]
@antonym  I tried increasing the memory to 8GB, and it shows the same problem? Not sure what to do to fix it, I've tried most things I can think of, including cloning it locally to avoid having to download a big iso file each time. Any advice?

**Comment by accessiblepixel** [comment]
The error I get is "(initramfs) unable to find a medium containing a live filesystem."
