### ISSUE TITLE
Tails still not booting even following suggestions in reply to #1102 (Virtual Machines, workaround/fix included)

### ISSUE THREAD

**Issue by accessiblepixel** [netbootxyz/netboot.xyz#1104]
**Describe the bug**
I tried live booting Tails linux from netboot.xyz and it fails with ``(initramfs) unable to find a medium containing a live filesystem.``

I believe this is a specific issue with KVM based virtual machines as I have now tried it with VirtualBox and it boots with 4GB RAM (it will not boot with 2GB of RAM, just brings up the initramfs shell)

I have found a workaround in the process of documenting this. It is at the bottom. The TL;DR is add an empty virtual CDROM drive to your virtual machine and it'll boot.

**To Reproduce**
1. Go to the boot entry for Tails
2. Try and boot from it
3. Starts loading then says ``(initramfs) unable to find a medium containing a live filesystem.``

**Expected behavior**
Tails should boot normally.

**Additional context**

I opened an issue in #1102 and tried increasing the memory to 8GB as suggested but it still did not boot and the issue was closed so I don't think anyone would have seen my replies and my eventual workaround, which I have documented here.

**The Troubleshooting**

I have tried the KVM virtual machine with UEFI (rather than SeaBIOS) with no change.
Tried increasing RAM to 8GB
Tried disabling KVM hardware virtualisation
Tried setting CPU to 'Host'
Tried changing network card from E1000 to VirtIO
Tried changing SCSI controller from VirtIO to LSI 53C895A
Tried changing system type from ix440fx to q35.
Tried changing OS Type from Linux 5.x-2.6 Kernel to Linux 2.4 Kernel
Tried turning off memory ballooning.

However, I think I have finally found an option that makes it boot. If I add an IDE or SATA virtual CDROM drive to the system, it lets me get to the 'Welcome to Tails Linux' screen. My assumption is whatever modifications were made to get it to boot from a network require some interaction with a real CDROM drive for it to work.

The settings that finally got me to boot were:

**Memory:** 4GB (Balloon Disabled)
**Processors:** 1 (2 Cores) [Host]
**BIOS:** SeaBIOS (Default)
**Display:** Default
**System:** q35
**SCSI Controller:** LSI 53C895A
**CD/DVD Drive (sata2):** None, media=cdrom)
**Network Device:** VirtIO
**OS Type:** Linux 2.4 Kernel

I am going to test to see what settings require to be changed from a default VM, but I expect that it's just a CDROM drive either sata or IDE.

Yes, it seems to boot fine with the addition of an IDE or SATA CDROM, using mostly defaults (listed below):

**The Fix**

**Memory:** 4GB (Balloon Enabled)
**Processors:** 1 (2 Cores) default (kvm64)
**BIOS:** SeaBIOS (Default)
**System:** Default (i440fx)
**SCSI Controller:** VirtIO
**CD/DVD Drive (ide2):** none, media=cdrom
**Network Device:** VirtIO
**OS Type:** Linux 5.x - 2.6 Kernel

So this is an interesting 'issue'. The workaround seems to be assign an empty CD/DVD drive to the machine and it boots as expected.

**The Verification**

I have also gone back to VirtualBox to test this theory, I removed the virtual CDROM drive from the storage settings, and it does not boot with the same error as I was having in KVM, ``(Initramfs) Unable to find a medium containing a live file system``.

So it does indeed require a virtual CDROM drive on the virtual machine to boot correctly.

I hope this proves useful.

Kind regards,
Jessica

**Comment by antonym** [comment]
You'll need a lot of memory, probably 4GB to 8GB as it's loading the ISO into RAM and still needs space to run. (2GB probably wouldn't cut it) I've tested on Proxmox (KVM) with and without a CD drive, and on ESXi and both work from what I've seen where it loads the "Welcome to Tails" screen. Tails 5 (based on Bullseye) is coming out soon and I'll be testing it to hopefully get it working as well so that may be worth a try soon to see if there's any different behavior.

**Comment by antonym** [comment]
You'll need a lot of memory, probably 4GB to 8GB as it's loading the ISO into RAM and still needs space to run. (2GB probably wouldn't cut it) I've tested on Proxmox (KVM) with and without a CD drive, and on ESXi and both work from what I've seen where it loads the "Welcome to Tails" screen. Tails 5 (based on Bullseye) is coming out soon and I'll be testing it to hopefully get it working as well so that may be worth a try soon to see if there's any different behavior.

**Comment by accessiblepixel** [comment]
Well, the testing I did, it didn't work without an emulated CD drive in Virtualbox or KVM based virtual machines.

I'm aware it copies the iso to RAM to load it, it copies it to /tails.iso compared to root (as specified in it's boot parameters) so yeah, ~4GB is about the right amount needed to boot, although you can get away with less. 

The **minimum** required to get a successful boot (the way this menu option boots) is _3840MB (3.75GB)_ but yeah 4GB or more is recommended. (For tails 4.28 anyway. I haven't tested other versions)

Well, hopefully if anyone else experiences the issue (that you can't seem to reproduce) at least they'll find this thread and the steps to get it working will have been useful to someone.
