### ISSUE TITLE
Proxmox VE not booting properly

### ISSUE THREAD

**Issue by CornelCotoara** [netbootxyz/netboot.xyz#1109]
Tried to boot my nuc5 over network to install another proxmox to test HA. It fails right after tries to pull iso with "No space left on device (http://ipxe.org/34182006)" and no such file or directory (http://ipxe.org/2d02803b)
I tested under a running proxmox VE test VM, the iso is pulled but the installer fails to load, endlessly trying to find some /dev/.
Downgraded to 2.0.56, under proxmox VM as it should but still no luck with real hardware. 
I have tested also debian live and redorescue under 2.0.57, working regardless of machine type.

**Comment by antonym** [comment]
Sounds like you may need more memory if you are running into that issue. How much does the nuc5 have?

**Comment by CornelCotoara** [comment]
Yea, sounds like that, but the nuc has 16GB of RAM installed.

**Comment by mscott83** [comment]
The Proxmox install process is completely broken, netboot references the old 7.1-2 ISO file which is no longer available from the Proxmox downloads site: [http://download.proxmox.com/iso/proxmox-ve_7.1-2.iso](http://download.proxmox.com/iso/proxmox-ve_7.1-2.iso) returns a 404.

I tried hacking the menus to just use the 7.2-1 ISO which is available but that doesn't work. Basically the menus need to be updated for 7.2-1 for everything to work again. The vmlinuz and initrd assets probably need to be updated as well.

**Comment by antonym** [comment]
@mscott83 can you try the development menu via Utilites? It has been updated for the latest version of 7.2-1 on the development side, but rolling won't pick it up until the next release.

**Comment by mscott83** [comment]
@antonym yes that works :)

I wonder if this is something that is likely to re-occur every time a new Proxmox release comes out if they delete the older versions from their downloads site. Maybe the ISOs are mirrored somewhere else that is a bit more reliable to use as a source?

**Comment by antonym** [comment]
The asset mirror is capturing it already, I'm just using upstream as it's the main source of truth, but I could switch to the asset mirror if it's causing that much of an issue long term:

https://github.com/netbootxyz/asset-mirror/releases/tag/7.1-2-a42c4ce8

**Comment by antonym** [comment]
Closing as I suspect the initial issue is hardware related and not bug related. You might want to see if there are others having a similar issue on the Proxmox forums or try just doing a regular install and see if you run across the same issue.

You can also try tuning kernel flags from the Utility menu and see if those may help out to debug.
