### ISSUE TITLE
DBAN booting is broken

### ISSUE THREAD

**Issue by pandruszkow** [netbootxyz/netboot.xyz#1118]
**Describe the bug**
Booting Darik's Boot And Nuke using the netboot.xyz USB image fails every time

**To Reproduce**
1. Boot netboot.xyz in either UEFI or MBR mode on a physical machine
2. Attempt to boot either the x86 or x86_64 version of DBAN
3. DBAN fails to boot to the main wiping screen

**Expected behavior**
DBAN boots completely, and shows the main screen that allows the user to proceed with the data wipe.

**Screenshots**
None, but I will add some later if I can reproduce this in a virtual machine

**Additional context**
n/a

**Comment by antonym** [comment]
DBAN is not in a UEFI option, you may want to use ShredOS instead as DBAN is no longer maintained upstream. I'm able to boot DBAN under legacy mode on the latest build.
