### ISSUE TITLE
Missing info from netboot's documentation

### ISSUE THREAD

**Issue by danboid** [netbootxyz/netboot.xyz#1127]
I thought I might as well bundle all the things I think need to be added or improved in the current netboot documentation into one ticket to reduce clutter.

The Docker page ( https://netboot.xyz/docs/docker ) currently states that  when you use `docker run` to create your netboot container, specifying a path for the assets is optional. It seems to me that if you don't provide an assets path the netboot web interface doesn't work (doesn't get configured?) at all and I've not found a working setting for the assets path, if there is one? Maybe this feature (local assets usage) has never worked?

@antonym have you tested the local assets feature of the netboot docker container?

I opened this issue for my assets problem https://github.com/netbootxyz/docker-netbootxyz/issues/24

The Self-hosted page seems mistitled. What most people prob want for 'self-hosted' is explained on the Docker page. The self-hosted page seems to be for those who want to fully customise netboot / netboot devs not just how to set up a local instance which is what I expected to see on the self-hosted page. We should explain this at the top of the self-hosted page if we don't rename that page to make it less confusing. I think the self-hosted page should be called 'Developers' and the Docker page 'Self-hosted', or just leave that as Docker.

Has anyone written a guide for extracting the Windows install ISO for installation via netboot? Windows is currently missing from the supported OSs list in the FAQ but there's no point in adding it until we tell people how they can install it via netboot.

netboot's lack of support for secure boot should be covered in the FAQ https://netboot.xyz/docs/faq  - I should be able to do a PR to fix this one now if I can find the correct repo.

**Comment by danboid** [comment]
I've added the Secure Boot QA to the FAQ

https://github.com/netbootxyz/netboot.xyz-docs/pull/58

**Comment by antonym** [comment]
If there are any additional docs to add, please feel free to open PRs. Thanks!
