### ISSUE TITLE
the Ubuntu 22.04 installer misbehaves on <3GB RAM

### ISSUE THREAD

**Issue by divinity76** [netbootxyz/netboot.xyz#1128]
**Describe the bug**

depending on available RAM, the Ubuntu 22.04 installer will:
1GB: crash with "IO error on /dev/loop2" -errors
2GB: Hang indefinitely? screenshot below
3GB: install fine.
**To Reproduce**
try to install Ubuntu 22.04 on 1GB/2GB RAM

**Expected behavior**
.. not sure, ideally some kind of error, or at least a very large warning, saying "netboot install of ubuntu 22.04 won't work on <3GB ram"

**Screenshots**
i don't have a screenshot of 1GB RAM crashes, but i have a screenshot of the 2GB RAM hang: 
![image](https://user-images.githubusercontent.com/1874996/174193381-e147da6d-9af6-4d4f-8a91-c3aa178e372e.png)
(on 3GB ram it works fine, neither hangs nor crashes)

**Additional context**

**Comment by antonym** [comment]
Generally more RAM is better... the kernel is having to download the ISO and mount it in RAM so 3-4GB or more is usually recommended. The older legacy installer kernels did not require as much RAM as packages were just streamed over the network.

**Comment by divinity76** [comment]
@antonym yeah but it took me hours to figure out "oh the problem is not enough RAM".  Would be nice if netboot gave some kind of warning "ey this sytem doesn't have enough RAM to use the Ubiquity installer, are you sure you want to boot this installer anyway?" - before it cost another person hours to come to the same conclusion

**Comment by antonym** [comment]
System requirements added to the docs: https://netboot.xyz/docs/quick-start#system-requirements
