### ISSUE TITLE
Add Fedora Workstation?

### ISSUE THREAD

**Issue by tobiashochguertel** [netbootxyz/netboot.xyz#1129]
There are lot of Fedora Variants available but "Fedora Workstation" is missing.

https://getfedora.org/de/workstation/download/

It's available as a Live Linux via ISO. Can that be added to netboot?

**Comment by antonym** [comment]
If you use the Live Fedora 36 Gnome version, that should be Workstation:

https://github.com/netbootxyz/fedora-assets/blob/36/settings.sh#L1
