### ISSUE TITLE
ESXi is listed in "Linux Network Installs"

### ISSUE THREAD

**Issue by hfuller** [netbootxyz/netboot.xyz#1135]
Hi, I love netboot.xyz but I continually forget to look in the "Linux Network Installs" section for ESXi. Could it be moved to a more appropriate section or its own section? Thanks for reading!

**Comment by antonym** [comment]
Thanks! I'd move it if there was a bit more real estate on the main menu but i'm trying to keep the top level a bit light for now for future options. If there are more hypervisors in the future, it might make sense to break them out into their own section again. I will keep that in mind though in case of a future restructure!
