### ISSUE TITLE
(Ubuntu) Could not verify: Permission Denied

### ISSUE THREAD

**Issue by Reinitialized** [netbootxyz/netboot.xyz#1136]
When attempting to perform either a `Live Install` or `Live CD` of Ubuntu via the netboot.xyz ISO, the following errors occur:
![image](https://user-images.githubusercontent.com/20674500/180663744-48edff1d-f16f-4bf9-9182-745169b09f4e.png)

Based on #347, this seems to be related to keys expiring and needing to be regenerated.

**Comment by antonym** [comment]
Was unable to reproduce with the latest build ISO, please make sure you have the latest build and ensure your time is set correctly too.

**Comment by ebauman** [comment]
I am having the same issue. Time is correct on my esxi hosts but can't boot Ubuntu.

**Comment by Reinitialized** [comment]
Ensured I downloaded the latest ISO and verified my time is correct (I have my time synced by GPS and distributed as stratum 1). Still unable to start Ubuntu, but the other distros I use work fine (AlmaLinux and Debian).

**Comment by antonym** [comment]
Any luck now? I pushed the latest release out yesterday.

**Comment by acidflash** [comment]
I have the same issue. If i change signature checks it works out. So any clue?
![image](https://user-images.githubusercontent.com/1126336/183116795-a58757b0-1697-4168-9b9d-0193310d551e.png)

**Comment by ebauman** [comment]
Confirmed working in my environment. Thanks @antonym !

**Comment by antonym** [comment]
Great, I had refactored some of the CI a few weeks ago and I think it had broke the Ubuntu menu sigs, hopefully it's all fixed now.

**Comment by antonym** [comment]
Closing as this should be fixed.

**Comment by indistinctTalk** [comment]
~~I'm seeing this error currently.~~ Disregard, it was an old image 🙃

**Comment by dylode** [comment]
I have the same issue with new image I just downloaded:
![image](https://user-images.githubusercontent.com/78496445/227564006-7662aef4-de22-4fce-af29-8dede55950ef.png)

**Comment by antonym** [comment]
Make sure time is correct on machine or try and validate that you can download the URL manually to a machine from your location.
