### ISSUE TITLE
Ubuntu 22.04 menu blank in v2.x iPXE build iso - regression

### ISSUE THREAD

**Issue by willmcginnis** [netbootxyz/netboot.xyz#1143]
**Describe the bug**
"Ubuntu Live 22.04" menu doesn't load anything
"Ubuntu Live 20.04" loads fine

**To Reproduce**
Distributions -> Live CDs -> Ubuntu -> "Ubuntu Live 22.04"

**Expected behavior**
Should load a similar menu to "Ubuntu Live 20.04"

**Screenshots**

**Additional context**
Bug is not in v2.0.60, SHA256:
7640d44f4c31828ae4137860ff95052c61ca89fe4517a081b78efd74262bc451

Problem present in iso built on Sat_Aug_13_04_52_32_UTC_2022, SHA256:
f0be74376979a3edda1d86b6c61f099a4bd4d59a2733e63eb6582ab8549d8a3f

**Comment by antonym** [comment]
Thanks, found some issues with the Ubuntu menu generation and the latest versions and have corrected them in rolling, they should be fixed in the next release.
