### ISSUE TITLE
Manjaro Live doesn't load in v2.0.60 or v2.x Aug 13 iso

### ISSUE THREAD

**Issue by willmcginnis** [netbootxyz/netboot.xyz#1144]
**Describe the bug**
Manjaro grabs vmlinuz and initrd fine, then very quickly errors out

Transcribed output:

:: running hook [miso pxe_http]
:: running hook [miso_pxe_nbd]
:: running hook (miso_pxe_nfs]
:: running hook [keymap]
:: Loading keymap...done.
:: Mounting /run/miso/httpspace (tmpfs) filesystem, size=' 75%'
:: Mounting /run miso/copytoram (tmpfs) filesystem, size=75%
:: Mounting /run/miso/cowspace (tmpfs) filesystem, size=256M
:: Mounting overlay root (tmpfs) filesystem, size=75%...[        11.442592] overlayfs: unrecognized mount option "lowerdir=" or missing value
mount: /new_root: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program or other error.
:: running late hook [miso_pxe_common]
:: running cleanup hook [miso_shutdown]
:: running cleanup hook [udev]
ERROR: Failed to mount the real root device
Bailing out, you are on your own. Good luck.

sh: can't access tty: job control turned off
[rootfs ]#

**To Reproduce**
Distributions -> Live CDs -> Manjaro -> "Manjaro Current Stable (21.x)" -> "Manjaro current architect"

**Expected behavior**
Manjaro should load and boot normally

**Screenshots**
<img width="1792" alt="Screen Shot 2022-08-18 at 1 51 58 PM" src="https://user-images.githubusercontent.com/40506393/185501898-a83f3d9c-0330-4219-b7d5-cc64c95ae798.png">

**Additional context**
Tested on KVM and VMware with 8 GiB of memory for both VMs.
Tested on ISOs:
SHA256(/var/lib/vz/template/iso/netboot.xyz_Jul_25__2022__7_20_AM_PDT_2.0.60.iso)= 7640d44f4c31828ae4137860ff95052c61ca89fe4517a081b78efd74262bc451
SHA256(/var/lib/vz/template/iso/netboot.xyz_Sat_Aug_13_04_52_32_UTC_2022.iso)= f0be74376979a3edda1d86b6c61f099a4bd4d59a2733e63eb6582ab8549d8a3f

**Comment by antonym** [comment]
Manjaro should be fixed on development branch, thanks for the bug report.

**Comment by dedene** [comment]
I still observe the same error with the [v2.0.63](https://github.com/netbootxyz/netboot.xyz/releases/tag/2.0.63). Should this be resolved in that version or is the development branch not merged in that release yet?

**Comment by antonym** [comment]
Architect was dropped as it's not maintained, but the latest versions should work for the other Manjaro releases.
