### ISSUE TITLE
Issue with NC Intel X550-AT2 ?

### ISSUE THREAD

**Issue by MiloDino88** [netbootxyz/netboot.xyz#1146]
Hello,

I contact you to know if the Intel X550-AT2 NICs are managed by the version of iPXE provided with netbootxyz?

I can netboot iPXE, but after network interface seems not detected :

netboot.xyz - v2.0.60
Network Configuration:                
Available interfaces...

With debug shell :

Type "exit" to return to menu
iPXE> ifstat
iPXE> 

I tested my configuration on a Proxmox VM with e1000 interface => it works!

So I was wondering if the problem is not related to the type of NIC Intel X550-AT2? if so what solution is available to me to add support for this type of NIC?

Thank you !

**Comment by antonym** [comment]
We always use the latest version of iPXE when building our binaries.  I would try and see how regular upstream iPXE behaves and open a ticket upstream if your NIC is not being detected in iPXE. Our project does not do anything with the drivers, just the scripting for now.

**Comment by ITJamie** [comment]
I have also experienced this on an x550-at2.
