### ISSUE TITLE
Incorret text install parameter on RHEL-based distros

### ISSUE THREAD

**Issue by ArclightMat** [netbootxyz/netboot.xyz#1154]
**Describe the bug**
RHEL and its clones have changed the installer parameters, they must be prefixed with "inst." now. 
The current configuration uses "text" instead of "inst.text", and support for the old flag is deprecated.

**To Reproduce**
1. Go to "Linux Network Installs"
2. Select any RHEL-based distro on the list, like CentOS or Rocky Linux
3. Pick the latest release and select the text installer option.
4. Anaconda will show a warning and won't start the text-installer environment.

**Expected behavior**
Anancoda would show the text-based installer options.

**Screenshots**
![Screenshot from 2022-09-13 15-40-18](https://user-images.githubusercontent.com/4731163/189986661-ad6965c1-e7ae-4cc2-92f0-b7b089269813.png)

**Additional context**
I'm using the ARM64 version, but I believe the problem also affects x86.
Fedora also uses Anaconda, and it seems to have the correct flag set:
![Screenshot from 2022-09-13 16-11-03](https://user-images.githubusercontent.com/4731163/189989303-19b55a21-247d-4829-9f96-8ea742ecad7b.png)

**Comment by antonym** [comment]
Thanks!
