### ISSUE TITLE
oracle cloud install Ubuntu 22.04 LTS Jammy Jellyfish and Ubuntu 20.04 LTS Focal Fossa (Subiquity) error

### ISSUE THREAD

**Issue by caojtop** [netbootxyz/netboot.xyz#1171]
**Describe the bug**
The following are the problems found during the installation of 22.04, there are similar problems in 20.04, but there is no problem in installing 22.10

BusyBox v1.30.1 (Ubuntu 1:1.30.1-7ubuntu3) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/enp0s3/02:00:17:00:ff:88
Sending on   LPF/enp0s3/02:00:17:00:ff:88
Sending on   Socket/fallback
DHCPDISCOVER on enp0s3 to 255.255.255.255 port 67 interval 3 (xid=0xc0f6a81d)
DHCPOFFER of 10.0.0.145 from 169.254.169.254
DHCPREQUEST for 10.0.0.145 on enp0s3 to 255.255.255.255 port 67 (xid=0x1da8f6c0)
DHCPACK of 10.0.0.145 from 169.254.169.254 (xid=0xc0f6a81d)
bound to 10.0.0.145 -- renewal in 42399 seconds.
Begin: Running /scripts/casper-premount ... done.
done.
Begin: Trying netboot from 10.0.0.1: ... Begin: Trying to download and mount http://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.1-live-server-arm64.iso ... wget: bad address 'cdimage.ubuntu.com'
done.
Unable to find a live file system on the network

**To Reproduce**
1.
![1667372075924](https://user-images.githubusercontent.com/19676224/199423739-131687f5-318f-4eb4-9fee-f57a35bf2a6f.png)
2.
![1667372100545](https://user-images.githubusercontent.com/19676224/199423777-3e3f22f7-daab-48eb-9c92-0b52ec1fcdbb.png)
3.
![1667372118336](https://user-images.githubusercontent.com/19676224/199423823-a224e8b4-660e-40e3-ad4d-2b9ba095f220.png)
4.
![1667372132496](https://user-images.githubusercontent.com/19676224/199423852-19ccd042-93b1-4a14-a3b8-629b3cbec998.png)
5.
![1667372192647](https://user-images.githubusercontent.com/19676224/199423887-bf632b65-fb4c-4342-b701-93f10628966f.png)

**Comment by antonym** [comment]
Sounds like your DNS may not be set correctly as it's unable to resolve cdimage.ubuntu.com.

**Comment by caojtop** [comment]
> Sounds like your DNS may not be set correctly as it's unable to resolve cdimage.ubuntu.com.

I don't think it's a dns problem, it's more a network problem at boot, because the installation of ubuntu22.10 was successful
![1667400033356](https://user-images.githubusercontent.com/19676224/199522150-22f98b9e-3047-4ec4-b80d-5094cdeffebe.png)

**Comment by antonym** [comment]
Closing as it sounds like software is working but maybe a race condition getting networking working on instance.
