### ISSUE TITLE
Flagged has a malware

### ISSUE THREAD

**Issue by VoXaN24** [netbootxyz/netboot.xyz#1181]
the http://boot.netboot.xyz/wimboot is flagged has a malware by ESET

![image](https://user-images.githubusercontent.com/30030208/207032562-c3f218a6-fcd9-4b5d-b9f9-3eef8dc3fd50.png)

**Comment by antonym** [comment]
More than likely it's a false positive, sha256 of https://boot.netboot.xyz/wimboot is `2a62a7362df29f35d12a3d7a69fe5d8bbcd5c49a244d12ff00f8a1e4eb0744e0` and matches upstream of https://github.com/ipxe/wimboot/releases/download/v2.7.4/wimboot v2.7.4 (2022-01-20).
