### ISSUE TITLE
Mint LiveCD doesn't work

### ISSUE THREAD

**Issue by coaxial** [netbootxyz/netboot.xyz#1184]
**Describe the bug**
When selecting the Mint option from the LiveCDs menu, none of the Mint options boot.

**To Reproduce**
1. Go to LiveCDs
2. Pick Mint
3. Pick Mint 21
4. Pick XFCE
5. Get an error message:
```
Could not boot: No such file or directory (https://ipxe.org/2402808e)
Could not boot: No such file or directory (https://ipxe .org/2402808e)
Error occured, press any key to return to menu
```

**Expected behavior**
Should boot the selecting Mint LiveCD.

**Screenshots**
```
Could not boot: No such file or directory (https://ipxe.org/2402808e)
Could not boot: No such file or directory (https://ipxe .org/2402808e)
Error occured, press any key to return to menu
```

**Additional context**

**Comment by antonym** [comment]
Can you try loading from the development endpoint from the Utility menu? There are some changes that haven't fully made it to rolling to fix the latest release version.

**Comment by coaxial** [comment]
Using the development endpoint works, I was able to start the Mint 21 Cinnamon LiveCD.

**Comment by antonym** [comment]
Great, I'm cutting a release today so that should fix up soon!
