### ISSUE TITLE
Can't install vyox with linux network installers

### ISSUE THREAD

**Issue by Kagamigawa** [netbootxyz/netboot.xyz#1188]
Can't install vyox with linux network installers
choose vyos and it got an error 

<img width="870" alt="截屏2023-01-02 19 33 24" src="https://user-images.githubusercontent.com/10486858/210226509-22ab3c4b-4077-4fca-aa1e-591dd37e59a2.png">

**Comment by antonym** [comment]
I was unable to reproduce using proxmox. I tested the rolling and latest release builds and both are able to load VyOS. Can you try downloading the files directly to see if there are any permission issues?

![Screenshot 2023-01-02 at 5 50 07 PM](https://user-images.githubusercontent.com/245007/210285539-15b0b006-54a7-4398-b114-069a9435ca8d.png)

**Comment by Kagamigawa** [comment]
> I was unable to reproduce using proxmox. I tested the rolling and latest release builds and both are able to load VyOS. Can you try downloading the files directly to see if there are any permission issues?
> 
> ![Screenshot 2023-01-02 at 5 50 07 PM](https://user-images.githubusercontent.com/245007/210285539-15b0b006-54a7-4398-b114-069a9435ca8d.png)

yes it is not project bug , platfrom may not upgrade new version
