### ISSUE TITLE
Filesystem.squashfs not generated for ubuntu-netboot

### ISSUE THREAD

**Issue by tredger** [netbootxyz/netboot.xyz#1192]
**Describe the bug**

The master `endpoint.yml` points 1ubuntu-netboot-22.04.11 to https://github.com/netbootxyz/ubuntu-squash/releases/22.04.1-e4c114c4/ but `filesystem.squashfs` is not generated in this release and it instead has four other squashfs filesystems.

https://github.com/netbootxyz/netboot.xyz/blob/589c06246e1690125394f83730e5549cec1aaabe/endpoints.yml#L1567-L1578

**To Reproduce**
Steps to reproduce the behavior as above
1. PXE boot netboot.xyz
2. select live installs -> ubuntu -> 22.04
3. fails to download the filesystem, netboot fails

**Expected behavior**

The `filesystem.squashfs` file to be generated and available, and ubuntu-netboot 22.04 to boot and install.

**Additional context**

It looks like this was addressed for the 20.04 netboot recently.

**Comment by antonym** [comment]
ubuntu-netboot images are used purely for the Linux Network Installs so they don't pull filesystem.squashfs down.
