### ISSUE TITLE
Unable to install Ubuntu newer than 19.10

### ISSUE THREAD

**Issue by zacekjakub** [netbootxyz/netboot.xyz#1199]
**Describe the bug**
Can't see Ubuntu 22.04 in any menu.

**To Reproduce**
I just start the docker container in Portainer using docker-compose.

**Expected behavior**
Despite the changelog, Ubuntu 22.04 was added so I supposed the item in the Ubuntu menu, but the newest release there is 19.10, which can't be even installed, because the online repo is gone.

**Screenshots**
![image](https://user-images.githubusercontent.com/10409208/217022171-783f8a5d-a3ca-46bb-a9bb-34052723f207.png)

**Comment by antonym** [comment]
Sounds like you are running an older release... make sure you are on 2.0.66.
