### ISSUE TITLE
XenServer outdated

### ISSUE THREAD

**Issue by cschmittiey** [netbootxyz/netboot.xyz#120]
XenServer has been updated to [7.0.0](http://xenserver.org/open-source-virtualization-download.html) as a stable version, mind fixing that in the menu?

**Comment by antonym** [comment]
Yeah, I have a request into Citrix to upload the bits for 7.0 to their CDN.  They currently host the bits for us.  Once they are uploaded, I'll update the menu for them.

**Comment by abitrolly** [comment]
Fixed by https://github.com/antonym/netboot.xyz/commit/a741b932029ea99074202dbf7acb878c31b3af92 ? Also, 7.2 is available by the link above.

**Comment by antonym** [comment]
XenServer support was pulled as they don't provide a place with the extracted ISO.
