### ISSUE TITLE
Chanloading from normal PXE Booting

### ISSUE THREAD

**Issue by finlstrm** [netbootxyz/netboot.xyz#121]
Not sure where else to go for support, if this is not the right place please point me in the right direction and close this issue. 

As the title says I have a normal legacy PXE boot environment already setup, I'd like to add netboot.xyz as one of the options and chainload to it - mostly for migration purposes. At some point I'll convert all our system images to this method and replace the legacy PXE with netboot.xyz.

I have the following added to my default menu file:
```
label 7
menu label ^7) iPXE Boot
kernel pxelinux.netboot/generic-ipxe.lkrn
append initrd=pxelinux.netboot/initrd
```

and the following (temporary) initrd:
```
#!ipxe
set net0/ip=dhcp
set dns 10.100.100.242
ifopen net0
####       boot.netboot.xyz initial loader       ####
#### see http://netboot.xyz for more information ####
set conn_type https
chain --autofree https://boot.netboot.xyz/menu.ipxe || echo HTTPS failed... attempting HTTP...
set conn_type http
chain --autofree http://boot.netboot.xyz/menu.ipxe || echo HTTP failed, localbooting...
```

It begins to work, but it keeps timeing out while retrieving menu.ipxe and cannot find out why. For testing I placed it on an unrestricted network and dropped the outgoing firewall but the issue remains.

Any help would be much appreciated!!!

**Comment by finlstrm** [comment]
Hi all,

I just figured out how to accomplish this. I simply changed the append portion of my menu entry to `append dhcp && chain --autofree https://boot.netboot.xyz` and netboot.xyz appears to be loading as desired.

**Comment by antonym** [comment]
Sorry, just saw this, glad you got it working!

**Comment by TechnologyClassroom** [comment]
I got this working with SYSLINUX 6.03.  I extracted the IPXE.KRN file from the [ISO](https://boot.netboot.xyz/ipxe/netboot.xyz.iso).  I placed the file into my tftp at tools/netboot.xyz.  I added this entry:

```
LABEL NETBOOTXYZ
  MENU LABEL netboot.xyz
  KERNEL tools/netboot.xyz/IPXE.KRN
```

**Comment by antonym** [comment]
Should be able to use https://boot.netboot.xyz/ipxe/netboot.xyz.lkrn as well.

**Comment by TechnologyClassroom** [comment]
I was going to try that next, but those files have matching sha512sums.

```
LABEL NETBOOTXYZ
  MENU LABEL netboot.xyz
  KERNEL netboot.xyz.lkrn
```

**Comment by businessBoris** [comment]
> Should be able to use https://boot.netboot.xyz/ipxe/netboot.xyz.lkrn as well.

Sorry to butt-in @antonym, @TechnologyClassroom ;  simply as "KERNEL https://boot.net.." ? 
[ SYSLINUX/EXTLINUX ]

**Comment by djuarezg** [comment]
Sorry for pingin on such an old issue but:

That works for a syslinux menu, but how can the same be accomplished for a `grub.cfg` menuentry?

**Comment by TechnologyClassroom** [comment]
@djuarezg Try placing the file in `/boot/` and try booting with something like this:

```
menuentry 'netboot.xyz' {
    KERNEL netboot.xyz.lkrn
}
```

I have not tested this.  Report back with your findings.

**Comment by djuarezg** [comment]
@TechnologyClassroom Cannot use `KERNEL` as it states it cannot find such command. Using `linux netboot.xyz.lkrn` reports a blank screen and [using `efi` files does not work either.](https://github.com/netbootxyz/netboot.xyz/issues/639)

**Comment by TechnologyClassroom** [comment]
@djuarezg If you know syslinux works, you could always chain to syslinux that just has that entry as the default.  It is not glamorous, but it would probably work.

**Comment by TechnologyClassroom** [comment]
@djuarezg You are also trying this with the web address which is different than what I proposed in this thread.  I did not want to use the web address as the security of upstream could be compromised without visible changes to the user.

**Comment by djuarezg** [comment]
@TechnologyClassroom  I do not mind having them locally, both web address and local files are fine for me. I guess that this is not strictly related as my issues are with GRUB for my UEFI machines.

**Comment by TechnologyClassroom** [comment]
@djuarezg Did you test them locally in the above report?  According to the other issue, the tests used the web addresses.

I was also using legacy boot last time I did this.  I have never tested it with UEFI.

I would still recommend chaining to syslinux if you cannot get pure grub to work.

**Comment by djuarezg** [comment]
> @djuarezg Did you test them locally in the above report? According to the other issue, the tests used the web addresses.

Yes, I actually left it using local files and updated my other issue so it does not mix both. I will try to see if chaining to syslinux works for me. Thanks!

EDIT: chaining to syslinux does not seem to work in our case
