### ISSUE TITLE
Netboot Squashfs of some Ubuntu Versions not found

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1210]
**Describe the bug**
I cant download Netboot SquashFS Files on Github. I get a 404 for 22.04 and 22.10. 20.04 works.

**To Reproduce**
1. Open Browser
2. try to download https://github.com/netbootxyz/ubuntu-squash/releases/download/22.10-1d3aa38b/filesystem.squashfs

**Expected behavior**
A download start

**Screenshots**
![image](https://user-images.githubusercontent.com/17622063/223849268-a5f3c761-48b1-499c-beb9-de60b58552dd.png)

**Additional context**
Nothing more to say.

**Comment by dansou901** [comment]
I can reproduce that. Also, Ubuntu 22.04.2 got released and should be added to the list/updated.

**Comment by oe3gwu** [comment]
This happens with almost all new Ubuntu Versions and variants. It starts downloaded and then crashes.

![IMG_2166](https://user-images.githubusercontent.com/17622063/224492296-712f4601-53dc-4be0-aa03-2c2ee67de48a.jpeg)

**Comment by antonym** [comment]
The netboot images are mainly used for the Linux Installers portion for vmlinuz, initrd, and then download of the ISO, the others are used for Live boot and use the squashfs. I've dropped the squashfs off the netboot images.

**Comment by oe3gwu** [comment]
Thank you!
