### ISSUE TITLE
Pulled Assets still load from the Internet

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1212]
**Describe the bug**
I pulled down KDE Neon for example. When checking my router I still get the traffic and items from the internet

**To Reproduce**
1. Pull KDE Neon
2. Try to boot the Live CD
3. When the CURL Fetch operation starts check the internet traffic --> still downloads from the internet

**Expected behavior**
Fetching local data

**Screenshots**
I can provide if needed.

**Additional context**
None - all said,

**Comment by oe3gwu** [comment]
Test is made with Ubuntu 20.04 KDE:

Downloaded Assets:
![image](https://user-images.githubusercontent.com/17622063/224532924-0912855b-7d5c-4f76-934b-12a0345c5ae7.png)

View from my VM and my Router. As you can see it got quite an incoming traffic while downloading - though assets are pulled.
![image](https://user-images.githubusercontent.com/17622063/224533033-43ccd5f4-f746-46a7-89f9-fb8a18c08b10.png)

My Docker Host is idle in the meantime.
![image](https://user-images.githubusercontent.com/17622063/224533075-ac472c06-ceea-4543-a462-bce46baa0cca.png)

I guess that is a bug. If it is not, why can I pull assetts?

**Comment by antonym** [comment]
You will need to modify the boot.cfg to pull assets locally:

```
set live_endpoint http://netboot.weninger.local:8080
```

**Comment by oe3gwu** [comment]
Yeah I saw this, therefore I closed the call. Sometimes RTFM works.
