### ISSUE TITLE
UBCD Download doesnt work

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1216]
**Describe the bug**
Download of http://mirror.sysadminguide.net/ubcd/ubcd538.iso doesnt work.

**To Reproduce**
1. Try to start UBCD. (x64)

**Expected behavior**
UBCD downloads

**Screenshots**
![image](https://user-images.githubusercontent.com/17622063/224812460-bbaaf09c-60e6-49b0-b025-f892f5617a3f.png)

**Additional context**
None

**Comment by antonym** [comment]
I was having problems downloading 538 too but I noticed theres a 539 that was downloading, so I switched it over to that.

**Comment by oe3gwu** [comment]
Thank you!
