### ISSUE TITLE
squashfs for Ubuntu 22.0.4.1-ddfea88f doesn't exist

### ISSUE THREAD

**Issue by JHarding86** [netbootxyz/netboot.xyz#1217]
**Describe the bug**
Attempting to load Ubuntu 22.0.4.1-ddfea88f, vmlinuz and initrd load, attempting to load squashfs and a failure occurs. Turns out when looking at that release within netboot.xyz it points to [this address](https://github.com/netbootxyz/ubuntu-squash/releases/download/22.04.1-ddfea88f/filesystem.squashfs), which does not exist.

**To Reproduce**
1. Attempt to boot into Ubuntu from PXE boot menu

**Expected behavior**
Squashfs should load properly

**Screenshots**

**Additional context**
I am a complete noob at PXE boot and netboot.xyz. Been doing this for a total of 20 minutes.

**Comment by blitzaxt** [comment]
I am seeing the same issue here it would appear that 22.04.1 is no longer hosted here: https://releases.ubuntu.com/jammy/. It would appear that only ubuntu-22.04.2-desktop-amd64.iso is being hosted at this point.

**Comment by blitzaxt** [comment]
@JHarding86  It would appear to me the correct assets have been generated for netbooting (https://github.com/netbootxyz/ubuntu-squash/releases/tag/22.04.2-ddfea88f) but the menu has not yet been updated to that version. Going into the netbootxyz menu and editing the ubuntu.ipxe menu I was able to update the asset address and it worked. It should look like the below example. 

```
#set kernel_url ${live_endpoint}/ubuntu-squash/releases/download/22.04.1-ddfea88f/
set kernel_url ${live_endpoint}/ubuntu-squash/releases/download/22.04.2-ddfea88f/
set codename jammy
#set version_number 22.04.1
set version_number 22.04.1

**Comment by antonym** [comment]
If the main branch doesn't have the release yet, you can always load from the development menu via the Utility menu. I should be cutting a new release soon.
