### ISSUE TITLE
Add support for VMware ESXI efi pxe booting

### ISSUE THREAD

**Issue by Dedsec1** [netbootxyz/netboot.xyz#122]
Hey, 

could you add support to allow pxe booting of netboot for EFI enabled vm's on Vmware ESXI if its possible,  the reason i ask is i work for an hosting company that deploys Vm's for customers that is hosted on our ESXI servers. we want to setup netboot.xyz for our customers so they can install different Linux dists easily if they choose to do so.

Thanks 

Dedsec1

**Comment by antonym** [comment]
I've been wanting to add more EFI support, just don't really have a good environment to test on yet.  I'll see if I can get an ESXi server set up somewhere and toy around with it.

**Comment by Dedsec1** [comment]
oh ok, sounds good and i  will be testing on my end as well

**Comment by antonym** [comment]
EFI should work so closing this out.

**Comment by azrdev** [comment]
My test with `netboot.xyz-efi.iso` failed, while `netboot.xyz.iso` booted fine. What setup did you get it working on? ESXi version, emulated Hardware version, e1000/vmxnet NIC?

**Comment by antonym** [comment]
You'll probably need to ensure the VM is booting in EFI mode, think there's either a setting in the VM or in the vmx config file for that.

**Comment by rancerbeta** [comment]
In case this helps anyone else: I was able to get the netboot.xyz EFI ISO booting on vSphere 6.7 using the iso off https://www.netboot.xyz/downloads/#uefi-ipxe-bootloaders. However, I could not get it to work with Secure Boot Enabled, which was on by default.
