### ISSUE TITLE
FreeDOS Full doesnt boot

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1224]
**Describe the bug**
FreeDOS Full doesnt find all files on the mirror to boot. FreeDOS Lite does work.

**To Reproduce**
1. Go to FreeDOS
2. Select FreeDOS Full

**Expected behavior**
Booting the Installer

**Screenshots**
![image](https://user-images.githubusercontent.com/17622063/227767795-702ce28e-6515-483a-a2a3-7394d18a1417.png)

**Additional context**
FreeDOS Lite does work fine. I guess the File got renamed, or it is the wrong file.

**Comment by antonym** [comment]
Both boot for me, potential connection or mirror issue?

**Comment by oe3gwu** [comment]
I tried today again, now it works. But whole yesterday it wasnt booting. No idea what the error is.
