### ISSUE TITLE
Ubuntu 20.04 fails to netboot

### ISSUE THREAD

**Issue by frct1** [netbootxyz/netboot.xyz#1225]
**Describe the bug**
Currently releases.ubuntu.com shows only 20.04.6, but not a 20.04.5 (it's moved to old-releases branch)

**To Reproduce**
1. Boot with netboot.xyz
2. Select ubuntu Focal Fossa 20.04 (Subiquity)

**Expected behavior**
Smooth netboot as always

**Comment by antonym** [comment]
Should be able to use the Development menu under Utilities until the next release happens.
