### ISSUE TITLE
Please add Lubuntu as Ubuntu Flavor to Live CD's

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1227]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Lubuntu is missing as Ubuntu Flavor in the Live CD's
https://lubuntu.me/

**Describe alternatives you've considered**
I am a KDE guy and thought, I want to try out some other QT Desktop Environment. Thought you have it on board, but it is missing.

**Additional context**
Not much to tell.

**Comment by antonym** [comment]
It should be there already, but under LXDE. LXDE is actually Lubuntu but it was switched a while back to LXQT now. I'll make that change to reflect that in the Menu.

___

LXDE was the standard desktop environment in [Lubuntu](https://help.ubuntu.com/community/Lubuntu), an Ubuntu derivative which received official endorsement in 2011, up to and including Lubuntu 18.04 LTS (Lubuntu switched to LXQt starting Lubuntu 18.10). Please see the [Lubuntu documentation](https://help.ubuntu.com/community/Lubuntu/Documentation) for support regarding LXDE in Ubuntu.
