### ISSUE TITLE
Partition Wizard x64 iso given on x86 netboot.xyz boot

### ISSUE THREAD

**Issue by scottlinux** [netbootxyz/netboot.xyz#123]
A menu option of Partition Wizard is given with a 64bit iso when booting on a 32bit CPU.

This results in an error of unable to boot into the 64bit Partition Wizard on an i686 system.

Please consider kindly adding an option for the 32bit Partition Wizard iso when booting 32bit:

www.partitionwizard.com/download/pwfree91-x86.iso

**Comment by ghost** [comment]
@antonym: Tried something like this:
```
iseq ${arch} i386 && set arch_partition_x86 x86 || set arch_partition_x86 ${arch_p}
iseq ${arch} x86_64 && set arch_partition_x64 x64 || set arch_partition_x64 ${arch_p}
set util_path www.partitionwizard.com/download/pwfree91-${arch_p}.iso
```

But failed miserably :-P

**Comment by antonym** [comment]
Looks like they dropped the linux free version.
