### ISSUE TITLE
Decluttering Network Install and LiveCD

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1235]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Almost Every Linux can be installed from the LiveCD. The Network Install Option should only be there for Netinstalls (mostly CLI only or Server). GUI's should be installable via LiveCD Variant.

**Describe alternatives you've considered**
There are none. It is just a mess.

**Comment by antonym** [comment]
Network installs are more lightweight installers used for low memory/bandwidth and speed. It provides multiple options for many types of users. Not everyone wants to load up a bloated LiveCD.
