### ISSUE TITLE
Unable to boot Fedora, CentOS, Rocky-linux

### ISSUE THREAD

**Issue by Heidistein** [netbootxyz/netboot.xyz#1236]
The bootlaoder downloiads the kernel and initramfs, however the initramfs is stuck at downloading its OS. It does not start, after a very longtime it timeouts and drops me to an emergency shell. Happens om vmware/proxmox/plain qemu/hardware in different networks.

![image](https://user-images.githubusercontent.com/5512589/231978422-0da63df3-149f-4d14-8963-32b5df19fdb6.png)

**Comment by antonym** [comment]
Unable to reproduce, could be environmental, memory, DNS/DHCP.

**Comment by 31KM** [comment]
I have the same issue. dracut-initqueue seems do hang at first, but after a few minutes a download line pops up, but after ~440/1895M nothing happens anymore.
Sometimes dracut-initqueue fails and I'm dropped to a rescue shell.

**Comment by immelrikt** [comment]
I have had the same issue. For me the solutions was to change BIOS to UEFI and boot file on DHCP server from `netboot.xyz.kxpe` to `netboot.xyz.efi`. Dracut-initqueue doesn't show any progress and takes some time to load the image, but works.
