### ISSUE TITLE
Can't download "ubuntu-netboot-22.04-amd64 (22.04.2-7d91a596)" under Local Assets in version 2.0.68

### ISSUE THREAD

**Issue by figaw** [netbootxyz/netboot.xyz#1237]
**Describe the bug**
Navigating to Local Assets, choosing the files from "ubuntu-netboot-22.04-amd64" (22.04.2-7d91a596) and downloading these, doesn't download the files.

It does create the folder locally.

~I suspect it's because the files are missing in the <https://github.com/netbootxyz/ubuntu-squash/releases?q=7d91> repository.~

**Update:**

I was able to find the release here: <https://github.com/netbootxyz/ubuntu-squash/releases/tag/22.04.2-7d91a596> 

I was also able to download the `initrd` and `vmlinuz`-files, but the `filesystem.squashfs` isn't part of the release.

**To Reproduce**
1. Run the docker container, version `2.0.68`
2. Navigate to "Local Assets"
3. Select files from "ubuntu-netboot-22.04-amd64"
    ```
    ubuntu-netboot-22.04-amd64	22.04.2-7d91a596/filesystem.squashfs	
    ubuntu-netboot-22.04-amd64	22.04.2-7d91a596/initrd	
    ubuntu-netboot-22.04-amd64	22.04.2-7d91a596/vmlinuz
    ```
5. Click "Pull Selected"

**Expected behavior**
Files are pulled to the local filesystem.

**Actual behavior**

1st attempt: empty folder was created
2nd attempt: folder was created with `initrd` and `vmlinuz`-files

**Comment by figaw** [comment]
Huh, it looks like the current ubuntu netboot menu `ubuntu.ipxe` isn't even using `filesystem.squashfs` right now, because it's just downloading the ISO from the Ubuntu mirrors, so.. maybe this is more of an issue that it shows up in the UI, and it's a bit unclear what needs to be hosted locally.

I ended up downloading the ISO and putting it in the `assets` folder, and make a couple of changes to the `.ipxe`-file.

So I'm not stuck, I was just a little confused.

**Comment by antonym** [comment]
The Ubuntu netboot kernels are not really intended to be used off-line in the app but they show up there because they are pulled down and maintained by the endpoints.yml. They probably just need a flag so that the app doesn't display them.

**Comment by figaw** [comment]
Thank you for the answer @antonym, can you elaborate a bit? It takes ~1 hr to download the netboot images from the official mirrors. What's the intended way of using the Ubuntu netboot kernels?
