### ISSUE TITLE
Add option for Fedora Everything netinstall iso

### ISSUE THREAD

**Issue by scottlinux** [netbootxyz/netboot.xyz#124]
Fedora has a special netinstall iso called Everything. This would be an awesome option to have in netboot.xyz

Location is:

mirror /fedora/linux/releases/25/Everything/i386/iso/
mirror /fedora/linux/releases/25/Everything/x86_64/iso/

Example:

http://mirrors.oit.uci.edu/fedora/linux/releases/25/Everything/i386/iso/Fedora-Everything-netinst-i386-25-1.3.iso
http://mirrors.oit.uci.edu/fedora/linux/releases/25/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-25-1.3.iso

**Comment by antonym** [comment]
This should get it added: 

https://github.com/antonym/netboot.xyz/commit/dfa5939e396e38df9426cf30273e68ee7cb558dc

**Comment by antonym** [comment]
This has been deployed out, thanks!
