### ISSUE TITLE
DELL PowerEdge R210 II hangs

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1246]
**Describe the bug**
Using a DELL PowerEdge R210 II with a Broadcom Dual Gigabit Ethernet NIC hangs on boot using iPXE. This is the only Broadcom System I have got. All my Intel work perfect, but this one not. I suspect a Bug somehwere. Using a WDS the card work perfect, so I suspect it in iPXE.

No special hardware installed. Only a USB Quadport PCIe Card. Rest is stock. I can provide the Service Tag if needed.

**To Reproduce**
1. Boot the DELL Server
2. Press F12 for Network Boot
3. iPXE Preboot Sequence is shown
4. Select a System to boot from Netboot
5. See the Screenshot.

**Expected behavior**
Working Bootprocess

**Screenshots**
![IMG_2650](https://github.com/netbootxyz/netboot.xyz/assets/17622063/2cacf721-dd1c-4922-8315-3d00c64085a5)
![IMG_2651](https://github.com/netbootxyz/netboot.xyz/assets/17622063/6beea23e-1565-464e-9b9c-c2b637bca896)
![IMG_2652](https://github.com/netbootxyz/netboot.xyz/assets/17622063/6ec16b9c-85d9-43bc-9b15-2ad5e866ded3)

**Additional context**
Using a DELL PowerEdge R610 with an onboard Intel Dual Gigabit NIC, Netboot works too. System has a Celeron CPU und 8GB RAM. 2 Disks (Windows Dynamic Disks) with a Software RAID 1.

**Comment by oe3gwu** [comment]
Same with Windows. It downloads all files needed but doesnt begin to boot.

![IMG_2669](https://github.com/netbootxyz/netboot.xyz/assets/17622063/8b0826e2-5b35-48c2-b75e-31ef044d2579)

**Comment by antonym** [comment]
Hardware specific issues I'd raise upstream to iPXE.

**Comment by Tampa** [comment]
Here with the same issue.

@oe3gwu Did you find a workaround? 

I'm gonna try the undionly image next as someone on FOG mentioned that those may work better, but I don't have high hopes for it. Guessing some config thing or missing module, but without any info on what it hangs on hard to say.

**Comment by oe3gwu** [comment]
No I did not. Even the classic PXE Image didnt work. I dropped the project.
