### ISSUE TITLE
netboot.xyz not loading in Equinix Metal

### ISSUE THREAD

**Issue by enkelprifti98** [netbootxyz/netboot.xyz#1255]
**Describe the bug**
Deploying Equinix Metal instances with custom ipxe and `https://boot.netboot.xyz` does not work. It gets stuck chainloading the netboot.xyz image.

**To Reproduce**
1. Deploy Equinix Metal server instance with Custom iPXE operating system. Under the URL field use `https://boot.netboot.xyz`

**Expected behavior**
The netboot.xyz image should load.

**Comment by vielmetti** [comment]
Happy to provide support for anyone interested in looking into this.

**Comment by antonym** [comment]
Any particular machine type this is occurring on or specific architecture? Have you tried loading older releases instead of rolling? Was it working before?

**Comment by enkelprifti98** [comment]
@antonym Seems to be mainly the m3.small.x86 instance type affected. Others like the c3.small seem to work fine.

**Comment by antonym** [comment]
if the implementation is working on other instance types of the same arch, I don't see why it wouldn't work unless there is something new with the hardware. If it was working previously, it could be an iPXE change upstream that rolled in, and then we could try booting older releases to see if anything works on that type.

**Comment by jackson-tim** [comment]
This also seems to be happening on the n3.xlarge instances, maybe it's a common NIC type? e810s maybe?

**Comment by vielmetti** [comment]
@antonym I have added some credits to your Equinix account, to assist in any testing. Unclear to me at this point what the scope of this problem is right now.

**Comment by enkelprifti98** [comment]
Hi @antonym @vielmetti ! I did some more testing and I believe this is an issue with nodes that have the Intel E810 NIC.

I deployed 5x m3.small.x86 instances. The ones with Mellanox NICs get to the netboot.xyz menu just fine. The ones with the Intel E810 NIC get stuck on the following screen seen through the Out-of-Band serial console.

```
Updated version of netboot.xyz is available:

Running version.....1.0.0+
Updated version.....2.x

Please download the latest version from netboot.xyz.

Attempting to chain to latest version...
http://boot.netboot.xyz/ipxe/netboot.xyz-metal.efi... ok
iPXE initialising devices...
```

**Comment by antonym** [comment]
I saw this link https://github.com/ipxe/ipxe/issues/498 but not sure if there was any resolution. Any idea what the firmware of the NIC might be on and if there is a newer rev available from Intel?

**Comment by antonym** [comment]
Also found this thread:

https://github.com/ipxe/ipxe/issues/937

I'll try and create some snp efi images this weekend and we can see if it provides a better result.

**Comment by antonym** [comment]
Try this url for custom_url to see if you have any issues:

```
https://s3.amazonaws.com/dev.boot.netboot.xyz/854df13acc3969f659f2fd3aa973c60d736a82e7/menu.ipxe
```

I've added building of the snp EFI kernels and also have set the default to use snp kernels as the default on everything as it should avoid using the built in iPXE drivers that are not always kept up to date as newer hardware is deployed. 

I've tested on one machine that was having the issue and it seemed to start loading after that. I'm not sure of the wider impact on other machine types yet, but it should be a more reliable path to go.

https://github.com/netbootxyz/netboot.xyz/commit/854df13acc3969f659f2fd3aa973c60d736a82e7
https://github.com/netbootxyz/netboot.xyz/commit/da3e1d9243a42999b5a022d50fecbb1c1479ecb1

This is mainly in development now and not pushed to production yet, will give it a bit of time to bake so others can test with.

**Comment by antonym** [comment]
Closing this out as I think this should be resolved and work better going forward, please ping me if you notice any oddness. Thanks to @vielmetti for the testing credits!

**Comment by vielmetti** [comment]
Thanks @antonym for checking this out - the credits should be ample for any reasonable test setup that is necessary now or in the future.

**Comment by enkelprifti98** [comment]
Tested an E810 node with `https://boot.netboot.xyz` and it works fine now. I guess the change is live in production at this point. Thanks for addressing the issue!
