### ISSUE TITLE
antergos installer broken

### ISSUE THREAD

**Issue by blessedbiped** [netbootxyz/netboot.xyz#126]
I tried to install antergos, looks like a link is broken. 
```http://antergos.x86innovations.com/iso/release/antergos-minimal-2016.10.23.x86_64.iso... No such file or directory```...
```Could not boot: no such file or directory (http://ipxe.org/2d0c613b)```

**Comment by antonym** [comment]
Yeah, looks like they changed the url location and versioning.  Deploying this fix:

https://github.com/antonym/netboot.xyz/commit/5f4403d26145d39854c38b65169fdd96eb2404dc

Thanks!
