### ISSUE TITLE
RHEL Distros broken?

### ISSUE THREAD

**Issue by o0-o** [netbootxyz/netboot.xyz#1260]
**Describe the bug**

CentOS Stream 8, 9 and Fedora 38 appear to fail while retrieving vmlinuz and initrd files. Possible more RHEL distributions are affected, I did not test exhaustively. I am able to install other distributions and I was able to install CentOS Stream 8 a couple days ago on the same system. I have tested across several systems now at 2 different locations.

**To Reproduce**

Attempt to install CentOS Stream using netboot.xyz.iso.

**Expected behavior**

vmlinuz and initrd files should load and installation should proceed as usual.

**Screenshots**

![Screenshot 2023-06-23 at 12 07 15 PM](https://github.com/netbootxyz/netboot.xyz/assets/17324878/a04796d5-61bb-4c43-98fd-20619c02f301)

**Comment by antonym** [comment]
It appears that mirror.stream.centos.org is using TLS 1.3 and iPXE does not at this time support it. It was working at one point so I suspect they dropped TLS 1.2 on Cloudfront. I also noticed that they still list http in their list of mirrors, but it automatically does a redirect to https now too.

https://mirrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64

```
curl http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

I'll have to switch mirrors to get it to work. Fedora 38 seemed to work for me tho.

**Comment by antonym** [comment]
I reached out to a contact at Red Hat to see if they see if they could dig into it.

**Comment by antonym** [comment]
Updating the mirror for now, will continue to monitor if we can get it fixed to work with us upstream.

**Comment by o0-o** [comment]
> iPXE does not at this time support it

And apparently won't anytime soon.

https://github.com/ipxe/ipxe/issues/787

Thanks for the fix though @antonym
