### ISSUE TITLE
Current UBCD mirror not working - Redirecting to HTTPS

### ISSUE THREAD

**Issue by Darkhand81** [netbootxyz/netboot.xyz#1263]
Hello!

Attempting to boot UBCD currently fails:

![image](https://github.com/netbootxyz/netboot.xyz/assets/1334381/71f0d46e-7293-451c-894d-fd6c3f225d74)

I confirmed that the .iso is still available, but the http link redirects to https:

![image](https://github.com/netbootxyz/netboot.xyz/assets/1334381/3f7b838c-9e06-4970-840d-533da1e2288a)

**Comment by bforcier299** [comment]
I don't know if it's related but any bistro selection will generate similar errors, currently unable to install from scratch using Netbook.xyz.

**Comment by chris18890** [comment]
Possibly a similar issue to #1260?
