### ISSUE TITLE
Can't boot Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ghost** [netbootxyz/netboot.xyz#1267]
**Describe the bug**
Trying to boot Ubuntu 22.04 LTS from Linux Network Installs on an Oracle Cloud ARM instance fails.
```
Listening on LPF/enp0s6/02:00:17:03:0e:5b
Sending on   LPF/enp0s6/02:00:17:03:0e:5b
Sending on   Socket/fallback
DHCPDISCOVER on enp0s6 to 255.255.255.255 port 67 interval 3 (xid=0x451f8937)
DHCPOFFER of 10.0.0.236 from 169.254.169.254
DHCPREQUEST for 10.0.0.236 on enp0s6 to 255.255.255.255 port 67 (xid=0x37891f45)
DHCPACK of 10.0.0.236 from 169.254.169.254 (xid=0x451f8937)
bound to 10.0.0.236 -- renewal in 37652 seconds.
Begin: Running /scripts/casper-premount ... done.
done.
Begin: Trying netboot from 10.0.0.1: ... Begin: Trying to download and mount http://cdimage.ubuntu.com/releases/22.04.2/release/ubuntu-22.04.2-live-server-arm64.iso ... wget: bad address 'cdimage.ubuntu.com'
done.
Unable to find a live file system on the network
```

**To Reproduce**
1. Boot netboot on a Oracle Cloud ARM instance
2. Select Linux Network Installs from the menu
3. Select Ubuntu
4. Select Ubuntu 22.04 LTS Jammy jellyfish

**Expected behavior**
I expected it to boot into the Ubuntu installer, instead it fails.

**Screenshots**
![image](https://github.com/netbootxyz/netboot.xyz/assets/51136374/80611698-4d6d-4a9d-b463-fb7922c84b1f)

**Comment by pvdemael** [comment]
I have no solution yet but the issue is that ubuntu-22.04.2-live-server-amd64.iso should be changed to ubuntu-22.04.3-live-server-amd64.iso which is available on the website

![image](https://github.com/netbootxyz/netboot.xyz/assets/37624277/6172eab7-89ac-4770-ae1f-ac89e5fb6ce4)

**Comment by antonym** [comment]
Try the development menu and see if it works there. You can select it via Utility and endpoints.

**Comment by antonym** [comment]
They drop that version once they increment, so if you are running an older version of netboot.xyz referencing that, it'll fail. Both the development endpoint and rolling endpoints usually pick up those versions within a day.
