### ISSUE TITLE
Please provide .efi builds

### ISSUE THREAD

**Issue by stove-panini** [netbootxyz/netboot.xyz#127]
I'd love it if you would provide a pre-built netboot.xyz.efi! You already provide a .lkrn file, so why not something for us with an EFI bootloader? :)

When compiling your project myself (using your prep-release.sh), I always run into cert not found issues during the build which causes the menu entries in the resulting .efi to not function.

**Comment by antonym** [comment]
I have one built, but not linked to the main page yet as I have not tested it.

https://boot.netboot.xyz/ipxe/netboot.xyz.efi

SHA256: https://boot.netboot.xyz/ipxe/netboot.xyz-sha256-checksums.txt

You are free to test it if you want.

**Comment by stove-panini** [comment]
Unfortunately your build runs into the same issues that mine did.

I can get to the main menu, but selecting any entry returns:
`http://boot.netboot.xyz/sigs/security.ipxe.sig... ok`
`Could not verify: Permission denied (http://ipxe.org/0216eb8f)`
`Error occured, press any key to return to menu...`

If I disable signature and image checking via the two bottom options on the main menu, I can access submenus. However, any entry returns the same message:
`http://boot.netboot.xyz/memdisk... ok`
`Could not select: Exec format error (http://ipxe.org/2e008081)`
`Could not boot: Exec format error (http://ipxe.org/2e008081)`
`Error occured, press any key to return to menu...`

**Comment by antonym** [comment]
memdisk won't work with EFI unfortunately so there's probably a bunch of logic to write to remove those options in those scenarios.  A lot of the images rely on being able to use memdisk and the original location of the ISO to boot, so I'd probably need to reduce the amount of options available when running EFI.

**Comment by stove-panini** [comment]
Hey, even though it didn't work out, I just wanted to say thanks for being so accommodating and providing me with your own build!
