### ISSUE TITLE
Netboot ConnectX NIC support

### ISSUE THREAD

**Issue by themikeambrose** [netbootxyz/netboot.xyz#1295]
**Describe the bug**
Netboot.xyz ISO doesn't work with Mellanox ConnectX-4 Lx network card.

**To Reproduce**
Boot Netboot.xyz UEFI on a system with ConnectX4LX card.

**Screenshots**
https://i.gyazo.com/e3991161e098971b922cab8c0e718556.png

**Additional context**
I have some systems with ConnectX 25G NICs and Netboot doesn't appear to support them. Shows NIC port as "down" but all OS installers directly work fine. Configuring IPs on it does not work, but works in other images like SystemRescueCD or Almalinux ISO directly.

**Comment by themikeambrose** [comment]
I grabbed an older Netboot ISO from someone who tested and had no issue, it seems like a slightly older one (both just say Version 2.X) and it works perfectly fine as expected. So it seems the latest ISO from the Netboot.xyz site is problematic but I'm not sure why.

**Comment by antonym** [comment]
I would try and reproduce in iPXE and see if you get similar results. netboot.xyz is mainly just a scripted menu and doesn't really touch the hardware drivers.

**Comment by o0-o** [comment]
While booting some systems into netboot.xyz via PXE using their onboard NIC, those with a ConnectX4 PCIe card installed would hang on the `boot` command (on all operating systems). Using `netboot.xyz-undionly.kpxe` works but I'm not sure if there's any workaround for UEFI (I'm not familiar with SNP).

Seems like @antonym is correct and there is an incompatibility between iPXE network drivers and ConnectX4 (even if it is not being actively used).

**Comment by antonym** [comment]
Closing as this is probably something upstream with iPXE and compatibility with that card.
