### ISSUE TITLE
Fedora (arm64) - Could not boot: No such file or directory

### ISSUE THREAD

**Issue by afzl-wtu** [netbootxyz/netboot.xyz#1300]
I am using latest version on arm64. Fedora Core OS works fine . But when loading any Fedora distribution it gives error:
```
Could not boot: No such file or directory (https://ipxe.org/2d02808e)
Could not boot: No such file or directory (https://ipxe.org/2d02808e)
Error occured, press any key to return to menu ...
```
I have switched to dev rolling and stable but in vain.

**Comment by antonym** [comment]
Pretty sure this is the issue, try and build from development endpoint and see if it works.

**Comment by afzl-wtu** [comment]
> Pretty sure this is the issue, try and build from development endpoint and see if it works.

I LOADED from Development end point as mentioned above but it does not work. If this is still an issue why are closing the issue

**Comment by antonym** [comment]
Because it loads now when it wasn't before:

![Screenshot 2023-10-12 at 8 12 02 AM](https://github.com/netbootxyz/netboot.xyz/assets/245007/d58bc37a-ed11-44b7-a1f1-92b4d418fff4)
