### ISSUE TITLE
Broadcom LAN Cards (from DELL 10th and 11th Generation) fail to boot

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1302]
**Describe the bug**
DELL R600, R210 II and R310 fail to boot when the onboard LAN Card is a Broadcom NIC. Using a PCIe Intel NIC gives an workaround but it seems that the old Broadcom PXE Firmware isnt supported or buggy. 12th to 15th Generation work fine. Interesting is that even older DELL PowerEdge 2950 Server boot fine too.

**To Reproduce**
1. Get an old 10th or 11th Gen DELL Server
2. Try to PXE Boot
3. See the Error message

**Expected behavior**
Successful PXE Boot

**Screenshots**
![IMG_3942](https://github.com/netbootxyz/netboot.xyz/assets/17622063/0ce12190-59c7-41bd-b2a4-b92595bedd1a)

![IMG_3946](https://github.com/netbootxyz/netboot.xyz/assets/17622063/4f9038db-ffe0-4e8f-a11a-7a04aac2e33c)

**Additional context**
I know those old servers are not something everyone has at home. But I can test changes on my hardware if needed.

**Comment by antonym** [comment]
Have you tried the undionly images? I used to have issues on R710s and had to use the undionly images for them to work.

**Comment by oe3gwu** [comment]
No i havent tried. Do you have a link to a guide how you sovled this?

**Comment by antonym** [comment]
Undionly images loaded over the network will occasionally bypass issues with booting as it'll piggyback off the option ROM instead of relying on built in drivers.
