### ISSUE TITLE
Missing artefacts for Grml

### ISSUE THREAD

**Issue by mika** [netbootxyz/netboot.xyz#1310]
**Describe the bug**

Using the latest netbootxyz release v2.0.72 (https://github.com/netbootxyz/netboot.xyz/releases/tag/2.0.72), I get no files for all the [Grml](https://grml.org/) entries, so it's not possible to boot any of the Grml releases/editions.

**To Reproduce**

1. Boot netbootxyz release v2.0.72
2. Choose `Tools` -> `Utilities (UEFI) -> Grml` -> choose `Grml 2022.11 full` and/or `Grml 2022.11 small`,  fails for both of them

**Additional context**

E.g. the vmlinuz file for grml-full is supposed to be https://github.com/netbootxyz/debian-squash/releases/download/2022.11-af4f2941/vmlinuz but this doesn't seem to exist. Related commit seems to be https://github.com/netbootxyz/netboot.xyz/commit/d100aa488d6038a7cc060035b8f9efe0ddc6c3db

Thanks for netboot.xyz! :) Would love to see Grml working again, also with my Grml project project lead hat on. :)

**Comment by antonym** [comment]
grml artifacts were regenerated, should be in the next 2.0.73 release.

**Comment by mika** [comment]
@antonym great, thanks! :)
