### ISSUE TITLE
Problem in initrd file 9990-mount-http.sh

### ISSUE THREAD

**Issue by lordrasmus** [netbootxyz/netboot.xyz#1313]
Some OS's split the RootFS file in more than 2 Files 

- gruda blackarch
- ubuntu-22.04-studio-squash

in 9990-mount-http.sh the files are downloaded and the part2 is attached to the first file
but part3 ist not downloaded 

so the OS can't boot

the Code is in Line 40
                                                  
log_begin_msg "Trying wget ${url} -O ${dest}/$(basename ${url})"
         /bin/curl -L "${url}" -o "${dest}/$(basename ${url})"
         if [ ! -z "$(/bin/curl -sI "${url}".part2 | grep "200 OK\|302 Found" || :)" ]; then
                          /bin/curl -L "${url}".part2 -o ->> "${dest}/$(basename ${url})"
         fi
         ;;

**Comment by antonym** [comment]
I've adjusted the mod layers to account for a third part but given the size of Studio, the job is not completing as it's running out of space in CI, so I'm probably going to drop it. Garuda Blackarch is also no longer maintained so I dropped that one as well.
