### ISSUE TITLE
docs seem to be missing examples of `user_overrides.yaml`

### ISSUE THREAD

**Issue by rod7760** [netbootxyz/netboot.xyz#1318]
**Is your feature request related to a problem? Please describe.**

It is unclear to me how to override the defaults in the ansible role. I referenced the [self-hosting docs](https://netboot.xyz/docs/selfhosting/), but there does not seem to be any clear explanation. 

**Describe the solution you'd like**

The docs mention a `user_overrides.yaml`  [here](https://netboot.xyz/docs/selfhosting#local-overrides) and state:

> If you want to override the defaults, you can put overrides in user_overrides.yml. See user_overrides.yml for examples.

It is unclear to me if there should be a link to an example or if `user_overrides.yaml` is somewhere in the repo. Regardless, I can't seem to find the examples.

**Comment by rod7760** [comment]
Ah, I feel a bit foolish now.  I see`user_overrides.yaml` at the top level of the project. I still would appreciate a link in the docs. I will follow up with the change.

**Comment by hellmind** [comment]
Where should be user_overrides.yml in  the docker container ?

**Comment by rod7760** [comment]
Fixed by [cfd9c41](https://github.com/netbootxyz/netboot.xyz-docs/commit/cfd9c4171f9bf0f8a40d3ba5d8e5a6891dfa0b19)
