### ISSUE TITLE
Multi-part live images aren't downloaded correctly (again)

### ISSUE THREAD

**Issue by iay** [netbootxyz/netboot.xyz#1321]
**Describe the bug**

If you download the assets for a large live image (e.g., current Kali or Debian 12 Cinnamon) only the first part of the `filesystem.squashfs` is downloaded, the `.part2` with the rest of the image is not.

This causes running the image from a locally downloaded copy to fail, whereas it works if you download from `github.com` each time.

**To Reproduce**

Download the assets for Debian 12 Live Cinnamon. Observe that the `filesystem.squashfs` is 2.0GB in size. Observe that the release contains an additional asset of 700MB which has not been downloaded.

**Expected behavior**

All assets should be downloaded.

**Additional context**

It looks like this happened in the past when the assets moved from one server to another, see #1068. That variant of the problem was apparently fixed in web UI 0.6.6. I am using the current Docker container 0.6.9, however, so it looks like it has "come back" in some sense.

As with #1068, though, if I manually download the `.part2` asset and place it alongside the other one, and set its ownership and permissions appropriately, I can boot from it correctly.

**Comment by antonym** [comment]
Think I found the issue, I think I broke this when I was switching it to the fetch library. This should fix the part2 downloads.

https://github.com/netbootxyz/webapp/commit/64ded80728f1f34d85c495b786c7e94c06563b16

I'll look at getting it released soon.

**Comment by antonym** [comment]
This should be fixed now in: [0.7.0-nbxyz1](https://github.com/netbootxyz/docker-netbootxyz/releases/tag/0.7.0-nbxyz1)

**Comment by iay** [comment]
Confirming that the Debian 12 Live Cinnamon case works for me with the latest container. Thank you!

**Comment by antonym** [comment]
No prob, thanks for calling out the issue!
