### ISSUE TITLE
Fedora 39 and 38 cannot be installed

### ISSUE THREAD

**Issue by CyborTronik** [netbootxyz/netboot.xyz#1322]
**Describe the bug**
Using [netboot.xyz.efi](https://boot.netboot.xyz/ipxe/netboot.xyz.efi) with PXE and it loads perfectly fine. 
However the Fedora 39 and Fedora 38 fails to load, from the linux network installers.

**To Reproduce**
1. Load the latest version of the [netboot.xyz.efi](https://boot.netboot.xyz/ipxe/netboot.xyz.efi) into PXE server
2. Boot from it on PC
3. Select Linux network installers
4. Select Fedora
5. You will see few versions of fedora listed, select Fedora 39
6. You will get an error: `Could not boot: No such file or directory (https://ipxe.org/2d02808e)

**Expected behavior**
Fedora Installer to be launched

**Screenshots**

**Additional context**

**Comment by antonym** [comment]
Thanks for the bug report, once this deploys out you can try the development menu from Utilities for now until the next release, the graphical boot type was mislabeled but should be corrected now.
