### ISSUE TITLE
Fedora 39 Everything missing

### ISSUE THREAD

**Issue by tifasoftware** [netbootxyz/netboot.xyz#1327]
When doing Fedora 39 Everything, it says

Could not boot: No such file or directory (https://ipxe.org/2d02803b)
Could not boot: No such file or directory (https://ipxe.org/2d02803b)
Error occured, press any key to return to menu...

**Comment by antonym** [comment]
This should be resolved on the development endpoint accessed via utilities. Should go out in the next 2.0.74 release.
