### ISSUE TITLE
Clonezilla won't start

### ISSUE THREAD

**Issue by borekon** [netbootxyz/netboot.xyz#1342]
**Describe the bug**
Unable to boot clonezilla nor Debian version neither Ubuntu version

**To Reproduce**
1. Go to _Utilities_
2. Go to _Clonezilla_
3. Select  _CloneZilla Debian based_
4. Go with the stable branch

**Expected behavior**
Clonezilla should boot

**Screenshots**
![image](https://github.com/netbootxyz/netboot.xyz/assets/9289539/83e502bf-9b5c-4681-b244-85a9d5501c83)

**Additional context**
curl is not found and the boot process cna't continue

**Comment by ddybing** [comment]
Do you get the same error with the current release? (3.1.1-27 of Clonezilla Debian branch, it seems)

**Comment by borekon** [comment]
The same happens with both releases.
Tried also with Ubuntu resleases, but it stuck at boot, so no Clonezilla is possible

**Comment by ddybing** [comment]
That's weird, it works just fine here on all releases, including both branches of Clonezilla. Does it actually download the filesystem.squashfs file, or does it jump immediately to curl not found? 

Not entirely sure what the problem could be though.

**Comment by borekon** [comment]
![image](https://files.vivancos.eu/clonezilla.gif)

**Comment by ddybing** [comment]
You're right, it doesn't work in Virtualbox here either. I tested in VMware earlier. Could be a virtual network card problem? I'll let you know if I find something out.

**Comment by antonym** [comment]
Try the latest build from rolling or development endpoints. If you see the curl not found, it's from a bad build where curl didn't compile correctly in the modlayer we use to inject the netboot logic for the image.

I've been regenerating the Debian and Ubuntu releases to correct the curl issue. The Ubuntu Clonzilla also currently doesn't work due to some changes that happened with Mantic I'm still seeing if I can sort. Debian should work though.

**Comment by borekon** [comment]
> You're right, it doesn't work in Virtualbox here either. I tested in VMware earlier. Could be a virtual network card problem? I'll let you know if I find something out.

It's a _binary not found_ problem instead of a network error. I tried in a laptop as well with no luck

**Comment by antonym** [comment]
The latest working build is going to be the Debian version of Clonezilla [here](https://github.com/netbootxyz/netboot.xyz/blob/development/endpoints.yml#L1048). It's going to only work on rolling or development endpoints until the next 2.0.75 release is cut. We use curl to retrieve the rootfs and in the process of updating the curl version we use to the latest build, the binary was missing some static libraries so I had to regenerate some of the images.
