### ISSUE TITLE
DHCPDISCOVER then netboot tries from gateway

### ISSUE THREAD

**Issue by troyBORG** [netbootxyz/netboot.xyz#1347]
**Describe the bug**
Tried to boot both in a VM and on Bare Metal for KDE Neon (I noticed in other live ones as well)

**To Reproduce**
Attempt to boot Live CD KDE Neon
After DHCP Discovery happens it will try netboot from your network gateway IP.

**Expected behavior**
Continue booting from the netboot.xyz IP

**Screenshots**
![IMG_20231128_151856](https://github.com/netbootxyz/netboot.xyz/assets/10406330/55bd5dd7-d0fe-49be-9357-c0b4c6dda150)

**Additional context**

**Comment by antonym** [comment]
Should be resolved in latest development/rolling, will be cutting 2.0.75 today to include the fixed images as well.
