### ISSUE TITLE
ProxMox menu always downliads iso from download.proxmox.com

### ISSUE THREAD

**Issue by jmedin1965** [netbootxyz/netboot.xyz#1350]
**Describe the bug**

File: netboot.xyz/roles/netbootxyz/templates/menu/proxmox.ipxe.j2

All the entries for proxmox ISO are hard coded. Example;

    kernel ${kernel_url}vmlinuz vga=791 video=vesafb:ywrap,mtrr ramdisk_size=16777216 rw quiet ${params} {{ kernel_params }}
    initrd ${kernel_url}initrd
    initrd http://download.proxmox.com/iso/proxmox-ve_${proxmox_version}.iso /proxmox.iso

So do not have the option to user ${live_endpoint} for local hosting.

But the  "netboot.xyz/endpoints.yml" file does have the isos listed and will download then and rename it as proxmox.iso. See example below;

  proxmox-ve:
    path: /asset-mirror/releases/download/8.0-2-e021922f/
    files:
    - initrd
    - proxmox.iso
    - vmlinuz
    os: proxmox-ve
    version: 8.0-2

So the downloaded iso will never be used on local hosting of netboot.xyz

**To Reproduce**

* localy host netboot.xyz
* download all assets listed in endpoints.yml and alter live_endpoint to point to these local assets
* disconnect network from internet, attempt to iPXE boot and load proxmox boot-pve.
* go to Distributions>>Linux Network Installs>>Linux Distributions>>Proxmox>>Proxmox VE 8.0-2

ISO download will fail while trying to download from http://download.proxmox.com/iso/proxmox-ve8.0-2.iso

But there is a local asset downloaded as;

    ${live_endpoint}/asset-mirror/releases/download/8.0-2-e021922f/proxmox.iso

**Expected behavior**
either alter netboot.xyz/roles/netbootxyz/templates/menu/proxmox.ipxe.j2 to user ${live_endpoint};
    initrd ${kernel_url}proxmox.iso /proxmox.iso
or remove the mention of the iso from netboot.xyz/endpoints.yml

**Screenshots**

**Additional context**
Sorry, not sure how to handle this. I can edit the proxmox.ipxe file manually and I can script the change to be applied afer an update but this doesn't help everyone else. I would create a pull request but not sure where to fix or if it really is a simple fix on not.

**Comment by antonym** [comment]
Switching to use the asset location: https://github.com/netbootxyz/netboot.xyz/commit/292da465d083f6af4fef9f1fa450b890b09a99a1
