### ISSUE TITLE
404 when downloading proxmox iso

### ISSUE THREAD

**Issue by jhofker** [netbootxyz/netboot.xyz#1351]
**Describe the bug**
Proxmox iso download urls may have changed.

**To Reproduce**
1. Boot netboot.xyz (I'm using an imaged USB drive)
2. `Live Network Installs (64-bit)
3. Proxmox
4. Proxmox VE 8.1-1
5. Receive error `No such file or directory (https://ipxe.org/2d0c618e)`
6. Appears to be a 404 on downloading the proxmox iso 

**Expected behavior**
The download is successful

**Screenshots**

**Additional context**
On proxmox.com, it appears the download urls are (now?) https://enterprise.proxmox.com/iso/proxmox-ve_8.1-1.iso rather than http://download.proxmox.com/iso/proxmox-ve_${proxmox_version}.iso as listed in https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/proxmox.ipxe.j2#L108

**Comment by antonym** [comment]
Have updated ISO urls.

**Comment by jhofker** [comment]
Thank you!
