### ISSUE TITLE
Outdated download links on main site?

### ISSUE THREAD

**Issue by queenkjuul** [netbootxyz/netboot.xyz#1353]
**Describe the bug**
When I download the ISO release from [the  download page](https://netboot.xyz/downloads/) (which points to [this file](https://boot.netboot.xyz/ipxe/netboot.xyz.iso)), I get errors trying to load most OSes. At one point I saw a reference to github.com/netbootxyz/asset-mirror/releases/download/6.6.2-2023.11.24-1cb5e1c9 which does not seem to exist.

When I download the latest ISO from the github releases page, I have no issues. 

**To Reproduce**
1. Download the ISO file from the main downloads page https://netboot.xyz/downloads
2. Boot it
3. Try to run a Linux Live CD (such as Backbox 7 or Bluestar Current)
4. File not found error

**Expected behavior**
Download and boot image

**Screenshots**
![image](https://github.com/netbootxyz/netboot.xyz/assets/58961215/c77546d0-7408-4e7b-8fd7-af7ec88b508e)

**Additional context**

**Comment by antonym** [comment]
Let me know if you continue to see the missing releases, I've been doing cleanup and regeneration of some of the images today and they should now be in development/rolling.
