### ISSUE TITLE
Support make -j switch for concurrent jobs

### ISSUE THREAD

**Issue by markusreil** [netbootxyz/netboot.xyz#1361]
**Is your feature request related to a problem? Please describe.**

generate_disks tasks can be sped up by using make's -j switch.

**Describe the solution you'd like**

Add a variable to user_overrides.yml to specify the number of concurrent jobs.

**Comment by markusreil** [comment]
Raised #1362 
Please let me know if you think is a good idea and/or what else would be required to get this merged. Thanks.

**Comment by antonym** [comment]
Finally got around to configuring this, wanted to say thanks, looks like it was an easy 6-7 minutes knocked off the build!
