### ISSUE TITLE
Change default mirror from rackspace.com to something different

### ISSUE THREAD

**Issue by mbugert** [netbootxyz/netboot.xyz#137]
[boot.cfg](https://github.com/antonym/netboot.xyz/blob/master/src/boot.cfg) currently specifies mirror.rackspace.com as the default mirror site. What's annoying about this is that linux distributions provided by Rackspace have modified `/etc/apt/sources.list` files, which again point to mirror.rackspace.com instead of official mirrors.

So how about the default mirror site is set to an official/independent mirror site?

For the time being, I work around this issue by manually changing the  `mirror` variable via the iPXE shell.

**Comment by antonym** [comment]
I'm open to suggestions on this.  I have the Rackspace mirrors by default as they are geo load balanced and gives me consistent folder structure.  From what I understand, the Rackspace mirror is literally just synced down and unmodified, so the reason they are probably getting those repos is because I add this in the kernel command line in order to prevent the user from having to set their mirror:

    mirror/suite=${debian_version} mirror/country=manual mirror/http/hostname=${mirror} mirror/http/directory=/debian

I could probably drop those and force the user to set them.

I'd actually like to start moving mirrors to official mirrors for each project, but I also want to avoid having to specify the mirror for every country code and worry about differing folder structures on other mirrors.

**Comment by mbugert** [comment]
I see it's not as easy as I first thought.

> I also want to avoid having to specify the mirror for every country code

Debian and Ubuntu (at least those, I haven't checked other distros) provide mirrors with predictable URL patterns, i.e. `ftp.<country>.debian.org` and `<country>.archive.ubuntu.com`. An idea might be to allow users to specify their country, otherwise rackspace is chosen as a default mirror.

**Comment by antonym** [comment]
First step might be just to drop the auto mirror assignment on those OS and just let the user pick it during install when the installer has an easy list to pick from.  For those you have to manually type it in, I'd prefer to keep something in there to make the experience more user friendly.  It might mean a slower install but at least it'll happen.

Each OS handles their mirror differently so it can spiral into a time consuming task pretty quickly having to deal with mirrors, especially when the mirrors break or older versions get dropped to free up space.

**Comment by ghost** [comment]
What of https://www.mirrorservice.org?

**Comment by nicoonoclaste** [comment]
@antonym For Debian mirrors, I think the best, officially-supported option is `deb.debian.org`.
It's administered by DSA (the Debian Systems Administration team) and backed by Fastly and Cloudfront so it should be fine pretty much anywhere.
PS: I haven't checked yet if it's a thing, but an easy way to set distro mirrors would be convenient; for instance, on our LAN I definitely want to automatically use our local mirror.

**Comment by antonym** [comment]
See https://github.com/antonym/netboot.xyz/pull/193 I'm working on using official mirrors where possible and making them more configurable from boot.cfg.  Would love feedback/testing on it.

**Comment by antonym** [comment]
Closing this out since a bunch of the main distros are now tunable and available in boot.cfg.  If there are any missing or better mirror locations, please feel free to put up a PR.  Thanks!
