### ISSUE TITLE
CentOS 8 stream mirror error

### ISSUE THREAD

**Issue by cuddylier** [netbootxyz/netboot.xyz#1380]
**Describe the bug**
None of the CentOS 8 stream boot methods work, they all error with "http://mirror.centos.org//images/pxeboot/vmlinuz... No such file or directory"
![Screenshot of error](https://github.com/netbootxyz/netboot.xyz/assets/1634957/0c3b0ba9-640b-4745-a520-5d59133c37fa)

**Comment by antonym** [comment]
Found an issue and pushed a fix up that should correct, you can check the development endpoint until Utilities and try again in a while once it completes the build.

https://github.com/netbootxyz/netboot.xyz/commit/f55b31d95bf9362a8c81a5f949f16b5e6fd75481
