### ISSUE TITLE
Not working for Dell Latitude E7480

### ISSUE THREAD

**Issue by guerby** [netbootxyz/netboot.xyz#139]
I'm trying netboot.xyz on a dell latitude E7480 laptop (UEFI network stack enabled, Secure boot disabled), I see the tftp happens but then just after a screen flicker the BIOS proposes F1 to retry boot, etc...
On the exact same setup another (noname) laptop netboot.xyz works just fine
Is there any way to debug what's happening?

**Comment by antonym** [comment]
It sounds like it's attempting TFTP but never picking up iPXE after that.    Could be many different things.  netboot.xyz is really just a compiled version of iPXE that reaches out to some scripts, so if you are having problems getting on the network, I'd probably post something in the iPXE forums to see if anyone else has had issues with that laptop or NIC.

**Comment by guerby** [comment]
Once you've posted could you put the URL here so I can follow? Many thanks for netboot.xyz :)

**Comment by guerby** [comment]
Sorry I probably misunderstood, trying to register on forum.ipxe.org

**Comment by robinsmidsrod** [comment]
Discussion continued here: http://forum.ipxe.org/showthread.php?tid=9428
