### ISSUE TITLE
Unable find a live file system on the network

### ISSUE THREAD

**Issue by vawaver** [netbootxyz/netboot.xyz#1399]
**Describe the bug**

It is impossible to install LiveCDs :
- Linux Mint Cinnamon 21
- Linux Mint Xcfe 21
- PopOS! 22.04

The installation process halted due to an error - Unable to find a live file system on the network. It appears that only 75-76% of the installation images from the server have been downloaded.

I attempted to download images for local installation, but encountered the same issue, with only 75% downloaded from the source. An intriguing observation is that regardless of the operating system I download, the file size of the downloaded image remains constant at 1999 MB.

**Screenshots**

![netboot-issue](https://github.com/netbootxyz/netboot.xyz/assets/52236863/2812007a-ed58-4bf0-bf58-a5cc84836024)

**Comment by jkoelker** [comment]
How much memory does your vm have?

**Comment by vawaver** [comment]
My VM has 4096 MB assigned.

**Comment by jkoelker** [comment]
Have you tried with more? All of these are booting for me with 8gb.

**Comment by vawaver** [comment]
You were correct; everything is working fine after upgrading the memory to 6 GB.
It would be beneficial to include this information in the official documentation.
The client should have a minimum of 6 GB RAM for LiveCD to operate smoothly.
