### ISSUE TITLE
Running Local?

### ISSUE THREAD

**Issue by Ttech** [netbootxyz/netboot.xyz#140]
I love the work you've been doing on this project. 

I was wondering if I could run it locally though, because I'd like to use this in a lab. Is there a way to mirror the current work without rebuilding everything?

Thanks

**Comment by antonym** [comment]
Thanks, happy it's useful!  

Yeah, I had some ideas about doing that where you'd run an Ansible playbook to get it all set up on a local machine.  I just need to find some time to dig into that.  It's on my long TODO.

**Comment by webairnetboot** [comment]
This seems like a duplicate of [Self-hosting Instructions #26](https://github.com/antonym/netboot.xyz/issues/26 )
