### ISSUE TITLE
Could you add the arm version of Proxmox from Proxmox-Port?

### ISSUE THREAD

**Issue by fengyang0317** [netbootxyz/netboot.xyz#1404]
https://github.com/jiangcuo/Proxmox-Port provides the arm version of Proxmox. Could you add https://mirrors.apqa.cn/proxmox/isos/proxmox-ve_7.4-1-arm.iso to the arm install menu?

**Comment by antonym** [comment]
This doesn't seem to be an official version of Proxmox, and while it sounds great that it works on arm64, I'd rather wait for an official version to be provided by Proxmox.

**Comment by fengyang0317** [comment]
https://www.proxmox.com/en/about/company-details/press-releases/proxmox-virtual-environment-launches-official-arm64-support

Shall we reopen this issue?
