### ISSUE TITLE
Docker compose on docker hub not requesting all ports

### ISSUE THREAD

**Issue by geekmoto13** [netbootxyz/netboot.xyz#1409]
**Describe the bug**
Ports 69 and 8080 are not being exposed when run on qnap devices
**To Reproduce**
1. Use container station 3 to build NetBoot.xyz using the docker image on docker hub.  The ports have to be manually specified on the second page of configuration 

**Expected behavior**
All ports requested for container do not show up with default config. 

**Screenshots**

**Additional context**
This may also be a qnap specific problem but there is no way to upload files to the server for things like windows pxe

**Comment by geekmoto13** [comment]
have confirmed this behavior also happens on self hosted docker instances and the ports have to manually specified

**Comment by antonym** [comment]
The services in the container are set to 80 (http), 3000 (webapp), and 69/udp (tftp). You'll need to set those in your configuration and make sure there isn't anything using those existing ports on your qnap. If you need to upload files, you would copy them to the assets folder you have defined or download them via the webapp.

**Comment by geekmoto13** [comment]
@
![qnap default config netbootxyz](https://github.com/netbootxyz/netboot.xyz/assets/22135972/c83998b7-a36d-4140-b61e-65a8adb4e8f4)

![portqry results](https://github.com/netbootxyz/netboot.xyz/assets/22135972/101a862d-b282-436b-8d40-1f51906ae453)
thats the thing, when the qnap and self hosted docker instances pull the compose, 3000 is the only one set, 8080 and 69 dont show up under the container config and have to be manually added in a NAT config for networking.

**Comment by antonym** [comment]
I'm guessing it's relying on the EXPOSE settings in the Dockerfile and currently I only have 3000 set. I'll enable EXPOSE for 80 and 69/udp as they seem to mainly just document which ports can be opened to docker but they can still overridden if needed.

https://docs.docker.com/engine/reference/builder/#expose

**Comment by geekmoto13** [comment]
sorry if my initial post didnt indicate that, I should have provided screenshots on the initial post.  thats my bad.

**Comment by antonym** [comment]
No worries, screenshot helps for sure, so many implementations out there. Give the latest container a try once it deploys out and let me know if the behavior is working better.

**Comment by geekmoto13** [comment]
yeah the qnap device seems to have pulled the new config and has all the ports listed at least, qnap has a strange docker implementation, but it now seems to work as intended and is responding to portqry

this has now been fixed

**Comment by antonym** [comment]
Sweet, I see them listed in docker inspect:

```       
 "NetworkSettings": {
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3000"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "3000"
                    }
                ],
                "69/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "69"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "69"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8080"
                    }
                ]
            },

**Comment by geekmoto13** [comment]
Also what I meant with not being able to get stuff on
To the server is that the container is so isolated (likely qnap specific logic) that the container isn’t allowed to access any files on the host system to allow the user to pull in files. I have gotten a container setup on a proxmox box after my qnap nas nearly took down my network during a reboot. Might be an idea to implement a built in ftp client to allow file management for devices that isolate containers but will need to do some testing with proxmox to see how far that extends if it’s a docker thing or just qnap specific
