### ISSUE TITLE
FreeDOS support

### ISSUE THREAD

**Issue by tidux** [netbootxyz/netboot.xyz#141]
ISO link: http://www.freedos.org/download/download/FD12CD.iso

This is especially helpful for firmware-flashing issues if you have a FAT32 USB stick (FreeDOS includes FAT32 drivers and can address large disks) since the process of creating a FreeDOS boot stick involves virtual-machine fuckery and takes over an hour from Linux.

**Comment by antonym** [comment]
FreeDOS install support is already available.
