### ISSUE TITLE
Cannot boot memtest86+ in UEFI mode - efi_setup() failed

### ISSUE THREAD

**Issue by TimoVerbrugghe** [netbootxyz/netboot.xyz#1417]
[X]: This bug persists when memory is increased beyond 8GB.

**Describe the bug**
When trying to boot memtest86+ 6.20 on menu 2.0.76 (latest one available while writing this) in EFI mode, I'm getting errors after the efi file of memtest86+ is downloaded (see screenshot).

**To Reproduce**
1. Boot netbootxyz in EFI mode
2. Go to Utilities (UEFI)
3. Try to boot memtest86+ 6.20

**Expected behavior**
Memtest86+ boots

**Screenshots**
![image](https://github.com/netbootxyz/netboot.xyz/assets/7707120/af93af10-ef5b-4823-b30b-258da1d9fc1b)

**Additional context**
- Using netbootxyz docker container, latest tag feom ghcr.io
- Computer that is trying to boot memtest86+ has following specs: Ryzen 5 3600, 64 gb DDR4 ram, GA-AB350-DS3H motherboard
- Memtest86 does work while booting netbootxyz in BIOS
- Other options in EFI mode (linux network installs or other utilities) do work normally (did not test every single one but proxmox installer, ubuntu live cd and system rescue CD all boot normally.
- Tried both with preloaded memtest86+ assets as non-preloaded ones
- Already tried fully deleting the docker container and its volumes and redeploying it with a freshly pulled image

**Comment by Firminator** [comment]
[On a sidenote v7.00 was released recently: https://github.com/memtest86plus/memtest86plus/releases which I'm not sure would or would not fix this issue.]

**Comment by antonym** [comment]
Did you happen to try 7.x series. I saw different behaviors on Proxmox vs VMWare between versions so I left them both as available.
