### ISSUE TITLE
Ubuntu 23.04 squash fs file is missing

### ISSUE THREAD

**Issue by MarekTran** [netbootxyz/netboot.xyz#1418]
[]: This bug persists when memory is increased beyond 8GB.

**Describe the bug**
Being unable to pull ubuntu-23.04-default-squash file.

**To Reproduce**
1. Go to "Local Assets"

**Expected behavior**
Asset is pulled.

**Screenshots**

**Additional context**
Following the link:
[23.04-295fa1c0/filesystem.squashfs](https://github.com/netbootxyz/ubuntu-squash/releases/download/23.04-295fa1c0/filesystem.squashfs)

Leads to 404:
https://github.com/netbootxyz/ubuntu-squash/releases/download/23.04-295fa1c0/filesystem.squashfs

**Comment by chris18890** [comment]
23.04 is EOL as of the end of January 2023 - https://lists.ubuntu.com/archives/ubuntu-announce/2023-December/000297.html

**Comment by fpetry** [comment]
This is already reported here: #1338
It affects also other, still supported distribution versions. In the linked issue, there is also a theory whats going on...
