### ISSUE TITLE
LiveCD Ubuntu 23.10 crashes with a 3 Minute hang waiting for Network, Ubuntu 22.04 works

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1419]
[x]: This bug persists when memory is increased beyond 8GB.
I got 512GB RAM - it should be enough.

**Describe the bug**
When booting Ubuntu 23.10 the system hangs at the screenshot. Ubuntu 22.04 works and begins downloading the files

**To Reproduce**
1. LiveCD
2. Ubuntu 23.10 GNOME
3. Enjoy the hang

**Expected behavior**
Booting to Live CD

**Screenshots**
Ubuntu 23.10
![IMG_4784](https://github.com/netbootxyz/netboot.xyz/assets/17622063/d43d44ba-037d-47e9-9d33-bb080dd82a43)

Ubuntu 22.04
![IMG_4785](https://github.com/netbootxyz/netboot.xyz/assets/17622063/ade386d9-a048-44a4-9d19-59de59b83f7b)

**Additional context**
NetbootXYZ is on latest build on my Docker.

Also Ubuntu 23.10 Installer doesnt work at my system, but this can be something else.

**Comment by njinco** [comment]
happens to me as well. good thing i looked if there are any open about this. Will try 22.04

**Comment by putnam** [comment]
Same issue. Every time I come back to netboot I run into stuff like this. I wish it just had the mainline iso images that worked. I'm not sure if all the images in the menus are regularly tested.

**Comment by njinco** [comment]
never got anything to work. maybe just me but i just went with buying a usb just to install ubuntu for now.

**Comment by antonym** [comment]
23.10 EOL, closing
