### ISSUE TITLE
Ubuntu 22.04.3-7e94379b/filesystem.squashfs missing

### ISSUE THREAD

**Issue by ImaginaryResources** [netbootxyz/netboot.xyz#1425]
**Describe the bug**
Currently unable to pull the selected asset [22.04.3-7e94379b](https://github.com/netbootxyz/ubuntu-squash/releases/download/22.04.3-7e94379b/filesystem.squashfs) as github shows it is not found.

**To Reproduce**
1. Locate asset 22.04.3-7e94379b in Local Asset tab and attempt to pull.

**Expected behavior**
To be able to pull the selected asset, [22.04.3-7e94379b](https://github.com/netbootxyz/ubuntu-squash/releases/download/22.04.3-7e94379b/filesystem.squashfs).

**Additional context**

Webapp Version: 	0.7.1
Menus Version:	2.0.77

**Comment by smoonlee** [comment]
Found this today as well, There is also a new image update for 22.04.04 released so missions the vmlinux and initrd files.

**Comment by antonym** [comment]
Old issue, version out of date, closing
