### ISSUE TITLE
Ubuntu 23.10 - /cow format specified as 'overlay' and no support found

### ISSUE THREAD

**Issue by mazlumtoprak** [netbootxyz/netboot.xyz#1429]
[X]: This bug persists when memory is increased beyond 8GB.

**Describe the bug**

When booting from netboot.xyz `http://boot.netboot.xyz/ipxe/netboot.xyz-snponly.efi` and selecting Ubuntu 23.10 as Live CD, i get an error: `/cow format specified as 'overlay' and no support found`. This was recently also described in the ubuntu [launchpad](https://bugs.launchpad.net/ubuntu/+source/casper/+bug/2055021) bug tracker.

Edit: Booting the Ubuntu 23.10 Network installer from netboot.xyz works

**To Reproduce**
1. Boot from iPXE and netboot.xyz
2. Select Live CDs > Ubuntu > Ubuntu 23.10 > KDE version
3. wait until all files have been loaded and the error appears

I've also tried to use the fix recommended in the bug (in my lab enviroment - removing the panic in scripts/casper in initrd) but that just fails too.

kernel parameters as of now are:
```
kernel ${kernel_url}vmlinuz${sas_token} ip=dhcp boot=casper netboot=url url=${squash_url} initrd=initrd locale=${language} ${cmdline}
```
**Expected behavior**

The boot is successful with these current settings.

**Screenshots**

Default iPXE boot from netboot.xyz
![image](https://github.com/netbootxyz/netboot.xyz/assets/17855960/bbf54453-09a3-4056-9325-02c5eed7a393)

Issue with modified scripts/casper according to the launchpad bug:
![image](https://github.com/netbootxyz/netboot.xyz/assets/17855960/6e20bbc3-104c-466a-8c30-5a2ae1db9917)

Edit: booting the network installer for Ubuntu 23.10:

![image](https://github.com/netbootxyz/netboot.xyz/assets/17855960/7f7a978b-1427-4dc7-bc1d-9e0d220bbdeb)

**Additional context**

I have a seperate lab that I can test custom kernel parameters / initrd / vmlinuz files.

**Comment by edu-vi** [comment]
also getting the same problem ubuntu 23.10

**Comment by mazlumtoprak** [comment]
This is probably not going to be resolved as the support just has been removed in main.

https://github.com/netbootxyz/netboot.xyz/commit/bd26f135f0c832dba369dc4db1cb47afeb0e4f85
