### ISSUE TITLE
Provide small VM image with PXE server that chainloads to netboot.xyz

### ISSUE THREAD

**Issue by jschwartzenberg** [netbootxyz/netboot.xyz#143]
Situation, system A is working properly, system B needs an OS installation. System B can only boot with legacy PXE, nothing else.

The quickest solution would be:
1. Install VirtualBox or another VM solution on system A
2. Bridge the virtual ethernet interface of VirtualBox to a wired ethernet port on system A
3. Set up a PXE server which chainloads to netboot.xyz inside this VirtualBox
4. Connect the wired ethernet interfaces of system A and B to each other
5. Use legacy PXE boot on system B

If the VirtualBox environment has two network interfaces, it could provide the internet connection with NAT+IP masquerading as well, but that could also be done on the host.

Would it be possible to provide one or more PXE server VM images for this purpose? It would seem like a very quick way to get up and running when no physical boot medium is available.

**Comment by Ttech** [comment]
So you want a basic DHCP server that provides the netboot stuffs? If thats it, I . could make a quick alpine ova but I'm not sure how much it helps.

**Comment by jschwartzenberg** [comment]
Exactly yep! Basic DHCP and I suppose a TFTP server that points to the netboot.xyz image. I think it would be a perfect way to bootstrap many environments.

**Comment by samip5** [comment]
@jschwartzenberg Would a docker container work?

**Comment by jschwartzenberg** [comment]
Not for all cases. If system A is an old Windows installation for instance. The solution I imagine could even be used by non-technical people to get this going if they have just two notebooks with at least one of them running any working OS plus just one UTP cable to connect the two.

An OVA would be easy enough to import in either VMware or VirtualBox on many platforms. Possibly providing an image with a few QEMU executables and a launch script would make it even easier.

**Comment by NiKiZe** [comment]
On windows, just use https://tftpd32.jounin.net/ or similar

**Comment by typecasto** [comment]
Install manjaro -> `yay -S pixiecore` -> `sudo pixiecore quick xyz`

Really any distro with the AUR will work, but manjaro is the most popular with an installer.

**Comment by jschwartzenberg** [comment]
Something that's installable through netboot.xyz itself is indeed great already if it's then set up with just one command. @thecakeisalie25 thanks a lot for the info!

**Comment by thelamer** [comment]
This image will provide TFTP endpoint and eventually a web based interface (track here: https://github.com/netbootxyz/webapp ) for customizing the files. 
https://github.com/linuxserver/docker-netbootxyz
Though no DHCP server as supporting that kind of stuff is a huge headache. 

I understand this is not exactly what you are looking for, but this will be the best solution we will be releasing unless someone outside the project decides to create something that is completely all inclusive either as a full VM or Docker Image.
