### ISSUE TITLE
SystemRescue: Alternative mode with "rootpass=MAC_ADDRESS"

### ISSUE THREAD

**Issue by lars18th** [netbootxyz/netboot.xyz#1441]
**Is your feature request related to a problem? Please describe.**
The System Rescue CD (inside the Tools menu) has the SSH server enabled by default. However, the password is not set. To enable it you can use the `rootpass` boot parameter. The idea is to set this parameter optionally as the value of the mac address.

**Describe the solution you'd like**
The solution is very straightforward, and it's described here: #1440 . We only need to enable a secondary entry in the menu that enables the parameter.

**Describe alternatives you've considered**
The alternative is to use a custom.ipxe menu. However, this seems to be unnecessary as the suggestion is simple, easy to implement, and doesn't break the security because it will add a _new_ entry, that prints the password. Therefore, it will only be enabled if the user wants it.

**Additional context**
I hope the developers agree with this suggestion and will implement it soon.

**Comment by lars18th** [comment]
Hi @antonym (and other developers),

Please could you add this simple enhancement (#1440) ?
Thank you.

**Comment by antonym** [comment]
Implemented
