### ISSUE TITLE
netboot.xyz-multiarch.iso triggers Trojan:Script/Wacatac.B!ml on Windows Defender (Windows 11

### ISSUE THREAD

**Issue by hseg** [netbootxyz/netboot.xyz#1446]
On Windows 11, https://boot.netboot.xyz/ipxe/netboot.xyz-multiarch.iso is detected as Trojan:Script/Wacatac.B!ml by Windows Defender and removed. The x86_64 image is fine, though, will be burning that for now.

**Screenshots**
![Screenshot 2024-04-02 145146](https://github.com/netbootxyz/netboot.xyz/assets/1260405/e7d30b4c-69e9-4698-83e4-a369d13e7dd5)

**Comment by antonym** [comment]
False positive that happens occasionally: https://github.com/netbootxyz/netboot.xyz/issues/1162
