### ISSUE TITLE
Documentation: Add release number to Downloads page

### ISSUE THREAD

**Issue by hseg** [netbootxyz/netboot.xyz#1447]
**Is your feature request related to a problem? Please describe.**
When opening #1446, I noticed the release number under consideration appears nowhere, so my explanation of the situation is unclear. It would make communication clearer if I could cite a version number.

**Describe the solution you'd like**
On the Downloads page (and in the links to the download images), add the release number of the images.

**Describe alternatives you've considered**
None -- did consider that one reason not to version is to avoid miscommunicating the message that the images need to be updated on each new release of the distros, but that seemed an insufficient reason to me

**Additional context**
This is in contrast to any other project I've encountered, was surprised when I realised this was the case.

**Comment by antonym** [comment]
Clarified downloads page here:

https://netboot.xyz/downloads/

All releases on that page are rolling and are updated on every commit to this repo. If you are looking for more stable versions, they can be downloaded [here](https://github.com/netbootxyz/netboot.xyz/releases).

The versions from operating systems change often so breakage does occur, so it's usually recommended to use either the latest rolling or release version to get the best experience.

**Comment by hseg** [comment]
That doesn't really address my issue - yes, the situation is clearer now, but I still have no way of determining the commit the rolling release is based on, making reporting issues more difficult.

(However, the link to the stable releases page is appreciated, and would've probably prevented me from even going down this script path to begin with!)

I see you're using static hosting, though. Is it that you don't have a way of/don't want to interpolate the commit hash into the page? In that case, is it at least possible to eh have the plain <https://boot.netboot.xyz/ipxe/netboot.xyz.iso> link redirect to <https://boot.netboot.xyz/ipxe/netboot.xyz-v42-beeffeed.iso>, perhaps by symlinking the two on the server? An alternative is to use a Content-Disposition header, but that's less clear and probably more work.
