### ISSUE TITLE
virbtualbox efi mode dose not work

### ISSUE THREAD

**Issue by IAseven** [netbootxyz/netboot.xyz#1452]
**Describe the bug**
![图片](https://github.com/netbootxyz/netboot.xyz/assets/38178039/5c269661-f799-45bb-bd34-b3697d273c67)

used iso file
![图片](https://github.com/netbootxyz/netboot.xyz/assets/38178039/92a4ddc4-514a-4123-a8e3-17ed329ad96e)

**exception**
![图片](https://github.com/netbootxyz/netboot.xyz/assets/38178039/9672d747-dd75-4c87-b94b-394d2a77932e)

**Comment by antonym** [comment]
Try a different virtual network adapter? 

https://github.com/ipxe/ipxe/issues/977#issuecomment-1987283091
