### ISSUE TITLE
Ubuntu 24.04 LTS fails to load

### ISSUE THREAD

**Issue by Thinkscape** [netbootxyz/netboot.xyz#1455]
### Steps

1. Boot into iPXE
2. Choose `Live network installs`
3. `Ubuntu`
4. `Ubuntu 24.04 LTS Noble Numbat`
5. `Install`

### Expected

Image downloads and installation starts.

### Actual

> http://archive.ubuntu.com/ubuntu/dist/noble-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/linux... Not found (https://ipxe.org/2d0c613b)
Could not boot: Not found ...

**Comment by antonym** [comment]
Give the development endpoint a try via the Utilities menu. I processed the kernels yesterday for the installer.
