### ISSUE TITLE
Ubuntu 22.04 Fails to laod

### ISSUE THREAD

**Issue by IcedZ** [netbootxyz/netboot.xyz#1459]
When installing Ubuntu 22.04 LTS, the wget command tries to download [ubuntu-22.04.3-live-server-amd64.iso](https://releases.ubuntu.com/jammy/ubuntu-22.04.3-live-server-amd64.iso)

It should in fact be downloading [ubuntu-22.04.4-live-server-amd64.iso](https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso)

This results in a 404 and inability to boot.  Ubuntu 23 seems to work fine.

**Comment by antonym** [comment]
Should be resolved with latest build.
