### ISSUE TITLE
Talos (arm64) support

### ISSUE THREAD

**Issue by ChickenIQ** [netbootxyz/netboot.xyz#1463]
Talos is already supported on x86_64, but the option is missing on arm64.
This would be great and should be possible as Talos supports pxe booting on both architectures.

**Comment by antonym** [comment]
I enabled the menu option on arm64 here: https://github.com/netbootxyz/netboot.xyz/commit/00cf90f70a22735a1ea00cd1ca7f7fbed09ba98b

I think everything is in place to handle multi arch so give it a try on the development endpoint under the utilities menu and let me know if it works.

**Comment by antonym** [comment]
Tested on arm64 server and kernels load up as expected.
