### ISSUE TITLE
QEMU Virtualization: Network Not Automatically Detected

### ISSUE THREAD

**Issue by novaTopFlex** [netbootxyz/netboot.xyz#1468]
[]: This bug persists when memory is increased beyond 8GB.

I am unable to increase my memory beyond the suggested 8GB on my system as 8GB is already the size of system memory on my system.

**Describe the bug**

On QEMU virtual machines (QEMU version 9.0.0 for i386, x86_64), the system is unable to detect the appropriate network interface(s) after a while. Eventually, the system will fail to boot `netboot.xyz v2.x` and be forced to boot the main disk image (as in `-boot c`).

**To Reproduce**
1. Enter the command `qemu-system-x86_64 -drive file=netboot.xyz.iso,format=raw,media=cdrom -drive file=AlpineTest.img,format=raw,media=disk -boot d`.

**Expected behavior**

The virtual machine is not detecting my host's network connection even though my QEMU setup successfully accesses my Internet connection between my Linux host and my Linux guests.

**Screenshots**

![Screenshot_2024-05-25_16-58-24](https://github.com/netbootxyz/netboot.xyz/assets/78602536/bbf64475-d75d-45d3-9f97-b7c5c8032a8f)

**Additional context**

I have previously been successful with booting my virtual machine to `netboot.xyz v2.x` but that was under QEMU version 6.2. I have since installed version 9.0 and now with this said version of QEMU am unable to boot this specific ISO (I have still been successful with other ISOs).

**Comment by antonym** [comment]
I tried on my Mac (M2) with QEMU 9.0 and the kernel and pulled it up without any issues:

```
qemu-system-aarch64 -cpu host -M virt,accel=hvf -m 4G \
-drive file=/opt/homebrew/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on \
-kernel netboot.xyz-arm64.efi \
-serial stdio \
-device virtio-gpu-pci \
-device nec-usb-xhci -device usb-kbd
```

It may be environmental, might also try different vnics.
