### ISSUE TITLE
Add support for ZFSBootMenu

### ISSUE THREAD

**Issue by no-usernames-left** [netbootxyz/netboot.xyz#1469]
**Is your feature request related to a problem? Please describe.**
ZFS-on-root systems are generally bootable from [ZFSBootMenu](https://github.com/zbm-dev/zfsbootmenu). This EFI image includes many useful utilities (especially the Recovery variant).

**Describe the solution you'd like**
Could you please consider the addition of [the `Recovery` image](https://get.zfsbootmenu.org/efi/recovery) (auto-redirecting URL to latest release) of ZFSBootMenu to netboot.xyz? (The regular image is a strict subset of the Recovery image, so the Recovery is an all-in-one.)

**Describe alternatives you've considered**
There is no exact alternative.

**Comment by BrianCArnold** [comment]
Here's a working iPXE script that will start ZBM if called directly, I have something similar set up in my `utils-efi.ipxe`:

```
#!ipxe

imgfree
kernel https://get.zfsbootmenu.org/efi
boot
```
