### ISSUE TITLE
Kali linux image stucks at EFI stub

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [netbootxyz/netboot.xyz#1473]
**Describe the bug**

Hello, i discovered your project and i wanted to give it a try, so i followed all steps mentioned in the documentation, 
then i tested to install debian which works, 
but when i tried kali linux image it stucks, it doesn't load and the installation process didn't start. 

**To Reproduce**

following steps : https://netboot.xyz/docs/kb/providers/oci
1.     Go to Boot Maintenance Manager
2.     Select Boot From File
3.     Select netboot.xyz.efi
4.     Kernel cmdline params set to: console=ttyS0,9600
5.     Linux Network Installs
6.     Kali Linux

**Expected behavior**
expected that it runs the install process just like debian , as kali is based on debian 

**Screenshots**
<img width="552" alt="Capture d’écran 2024-06-12 à 04 33 40" src="https://github.com/netbootxyz/netboot.xyz/assets/17873513/43fc5118-8e62-418f-9451-5cc275e2dcf4">

<img width="915" alt="Capture d’écran 2024-06-12 à 04 23 52" src="https://github.com/netbootxyz/netboot.xyz/assets/17873513/f53ecce6-3773-4e1e-86b2-c200e475c2c2">

**Comment by antonym** [comment]
You might try playing with the console settings or see what a working instances console settings are by checking /proc/cmdline once it boots. My guess is it's booting but the wrong console is going to the cloud shell so you aren't seeing any output.

**Comment by mIcHyAmRaNe** [comment]
thank you for the reply, 
i'm gonna try playing with console settings :)
