### ISSUE TITLE
grml 2024.02

### ISSUE THREAD

**Issue by crpb** [netbootxyz/netboot.xyz#1476]
Hi,

as i couldn't make heads or tails on how to create a correct pull-request i will just ask.

Could you please update the [GRML Release](https://grml.org/changelogs/README-grml-2024.02/) to the latest version?

cheers

@mika :wave:

**Comment by antonym** [comment]
Done!

https://github.com/netbootxyz/debian-squash/commit/e064bb326e6d30cde2689818edbbd23d99cf3003
