### ISSUE TITLE
centos 7 - no such file or directory

### ISSUE THREAD

**Issue by yulemir** [netbootxyz/netboot.xyz#1483]
Hey,
Centos has changed where it stores its old systems.
Will this be included in the new version?

**To Reproduce**
1. Go to Centos 7.x
No such file or directory.
Could not boot.
Thanks.

**Comment by chris18890** [comment]
CentOS 7 is EOL, so URLs may no longer work - https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule

**Comment by antonym** [comment]
CentOS 7 is EOL and has been removed.
