### ISSUE TITLE
Installing CentOS Stream 9 through ipxe on an Equinix Metal aarch64 mtjade hypervisor fails

### ISSUE THREAD

**Issue by stratakis** [netbootxyz/netboot.xyz#1484]
On Equinix Metal, after choosing custom_ipxe and using https://boot.netboot.xyz/ I'm able to boot to the menu to choose an OS.

However on selecting either the graphical or the text based network installer for CentOS Stream 9 I receive this error:

>>Checking Media Presence......
>>Media Present......
 Downloading NBP file...

  NBP file downloaded successfully.
iPXE initialising devices...ok

iPXE 1.21.1+ (g0cc8) -- Open Source Network Boot Firmware -- https://ipxe.org
Features: DNS HTTP HTTPS NFS TFTP VLAN EFI Menu
Welcome to Neverland!
Booting from net0...                     
<snip> (Ethernet) [open]
  [Link:down, TX:0 TXE:1 RX:0 RXE:0]
  [Link status: Unknown (https://ipxe.org/1a086194)]
  [TXE: 1 x "Network unreachable (https://ipxe.org/28086090)"]
Configuring (<snip>)... ok
net0: <snip>gw <snip>
net0: <snip> gw <snip>
net1: <snip> (inaccessible)
net2: <snip> (inaccessible)
Next server: 147.28.152.140
Filename: nonexistent
tftp://147.28.152.140/nonexistent... No such file or directory (https://ipxe.org/2d12608e)
Checkpoint 92
Checkpoint 92
Checkpoint 92
Checkpoint 92
Checkpoint A0
Checkpoint 92
Checkpoint 92
Checkpoint A0
Checkpoint 92
Checkpoint 92
Checkpoint 92
Checkpoint 92
Checkpoint 92
Checkpoint A0
Checkpoint A0
Checkpoint DA
ERROR: Boot option failed

I've also tried to used the developer endpoints through the utilities menu to no avail.

**Comment by stratakis** [comment]
Same happening for AlmaLinux 9

**Comment by antonym** [comment]
I tried CentOS 9 Stream and Almalinux (text) with a c3.large.arm64 on Equinix Metal and it booted up without any issues. I was able to get all the way to the text mode install prompts.

**Comment by stratakis** [comment]
The issue was the APEI setting in the BIOS. After disabling it it was possible to proceed with the installation.
