### ISSUE TITLE
Wrong endpoint for Ubuntu 22 LTS netboot

### ISSUE THREAD

**Issue by thundervm** [netbootxyz/netboot.xyz#1490]
**Describe the bug**
Trying to install ubuntu 22 lts fails due to an erroneous endpoint for the image.
The default url is https://releases.ubuntu.com/jammy/ubuntu-22.04-live-server-amd64.iso
The correct one is https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso

**Comment by antonym** [comment]
Make sure you are using the latest version of netboot.xyz. The latest version accounts for that:

```
curl https://boot.netboot.xyz/ubuntu.ipxe | grep 22.04.4
...
set kernel_url ${live_endpoint}/ubuntu-squash/releases/download/22.04.4-295657f3/
set version_number 22.04.4
set kernel_url ${live_endpoint}/ubuntu-squash/releases/download/22.04.4-32a0e326/
set version_number 22.04.4
```
