### ISSUE TITLE
unable to boot the almalinux 9 installs

### ISSUE THREAD

**Issue by KansasNet** [netbootxyz/netboot.xyz#1491]
[]: This bug persists when memory is increased beyond 8GB.
only running with 4gb but throws the error right away.

**Describe the bug**
unable to boot into almalinux network install

**To Reproduce**
try and boot any almalinux 9 network install.
fails with no such file or directory.

**Expected behavior**
boots network installer
**Screenshots**
![image](https://github.com/user-attachments/assets/d0e587be-9870-4cb3-a7c0-f529a7887d74)

love the software, thanks for the hard work.

**Comment by antonym** [comment]
Wasn't able to reproduce this, the latest build works and that file is currently present at that URL. I'd try again, its possible the mirror was down at the time
