### ISSUE TITLE
 Integrating OpenMediaVault

### ISSUE THREAD

**Issue by uselibrary** [netbootxyz/netboot.xyz#1492]
- OpenMediaVault (OMV) is designed for **network-attached storage** (NAS). 
- OMV is based on the Debian licensed through the GNU GPL v3.

Integrating OMV is straightforward because it is based on Debian, which minimizes adaptation challenges. Additionally, OMV effectively fills the gap as a NAS operating system.

**Comment by jamess60** [comment]
+1

**Comment by antonym** [comment]
Looks like the Debian image may be missing live boot, so currently unable to live boot it. Open to adding if support is added.

<img width="882" alt="Screenshot 2024-08-11 at 10 10 48 AM" src="https://github.com/user-attachments/assets/9c2f4e60-4bfb-4e1c-9a9a-1b8ae87ec3a2">
