### ISSUE TITLE
Booting Ubuntu 24.04 on Proxmox fails.

### ISSUE THREAD

**Issue by justsem** [netbootxyz/netboot.xyz#1496]
[X]: This bug persists when memory is increased beyond 8GB.

**Describe the bug**
When trying to boot an Ubuntu 24.04 installer on a Proxmox environment, the installer hangs on the Intial Cloudinit job (metatada service crawler). This doesn't happen when using an Ubuntu ISO from a virtual CD drive.

It doesn't make a difference to whether Cloud-init is configured on the VM or not.
I've tested a bunch of different settings.

Since this error appears on Netboot.xyz this can mean either of 2 things:
1. The issue is a netboot.xyz problem and needs to be fixed here.
2. This issue is an ubuntu issue, but isn't present in the ISO version.

**To Reproduce**
1. Spin up an EFI based machine on Proxmox
3. Netboot the latest Netboot.xyz
4. Boot the Ubuntu 24.04 netinstall (without any additional settings)
5. Wait and see..

**Expected behavior**
The installer booting past the cloud-init job like it does on 22.04.

**Screenshots**
![image](https://github.com/user-attachments/assets/94ee51dd-609f-4289-b9ca-1bbf55e7c373)

**Comment by Linuxsmurfen** [comment]
Had the same type of issue and had to change the kernel parameters in the "ubuntu.ipxe" to get it working.
- Increase the ramdisk_size
- Add cloud-config-url=/dev/null

```
echo Loading Ubuntu Subiquity Network Installer...
#kernel ${kernel_url}vmlinuz root=/dev/ram0 ramdisk_size=1500000 ${netboot_params} ${install_params} initrd=initrd.magic ${cmdline}
kernel ${kernel_url}vmlinuz root=/dev/ram0 ramdisk_size=3500000 ${netboot_params} cloud-config-url=/dev/null ${install_params} initrd=initrd.magic ${cmdline}
```

**Comment by antonym** [comment]
I ran into a hang that appeared to last several minutes on cloud init but it finally went through, these were the logs I got from cloud-init:
![Screenshot 2024-08-08 at 10 18 34 PM](https://github.com/user-attachments/assets/44bc0eed-485f-44b0-9099-679638f1783f)

**Comment by antonym** [comment]
Pushed some changes up per the recommendations, lets see if that improves things, it did seem to boot faster.
