### ISSUE TITLE
Local Boot of Assets fail

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1499]
**Describe the bug**
I changed the life endpoint to an HTTP Address on my network.

set live_endpoint http://192.168.1.22

Then I downloaded the Kubuntu 20.04 and 22.04 Live CD stuff. And when trying to boot, it fails on the 3rd download.

**To Reproduce**
1. Change Endpoint
2. Boot Kubuntu Live 22.04

**Expected behavior**
A clean boot

**Screenshots**
![IMG_5461](https://github.com/user-attachments/assets/e97e2747-f260-4ec4-93ce-ed16a7e70551)

![IMG_5460](https://github.com/user-attachments/assets/df9bb1d0-2ac3-427a-8568-e6f80f0b8f3e)

**Comment by vanyell** [comment]
What is the RAM configuration of the machine? 8GB minimum

**Comment by antonym** [comment]
The downloaded sizes of your first part is 1.6GB when it should be ~1.9GB. Probably have a bad download:

https://github.com/netbootxyz/ubuntu-squash/releases/tag/22.04.4-36909c4f
