### ISSUE TITLE
Windows 8.1/10 support

### ISSUE THREAD

**Issue by Manouchehri** [netbootxyz/netboot.xyz#15]
https://technet.microsoft.com/en-ca/library/dn594399.aspx - WIMBoot Overview
https://technet.microsoft.com/en-ca/library/dn621983.aspx - Create WIMBoot Images

> Windows image file boot (WIMBoot) lets you set up a PC so that it runs directly from a compressed Windows image file (WIM file).

Source: http://labalec.fr/erwan/?p=1078

With Windows 8.1/10, it's now possible to boot a _full_ system from WIMBoot instead of just an install image. Seems like it might be possible to do this over a network as well.

Any thoughts/attempts yet?

Related: #8

**Comment by antonym** [comment]
Still need to test this before merging:

https://github.com/antonym/netboot.xyz/pull/105

**Comment by Manouchehri** [comment]
Thanks for the update, this looks great!

**Comment by antonym** [comment]
This is now merged, hopefully this provides some usefulness.
