### ISSUE TITLE
Kubuntu 20.04 and 22.04 online boot fails

### ISSUE THREAD

**Issue by oe3gwu** [netbootxyz/netboot.xyz#1500]
**Describe the bug**
When booting Kubuntu 20.04 or 22.04, following error comes after the download

**To Reproduce**
Just boot up Kubuntu 22.04 or 20.04

**Expected behavior**
A clean boot

**Screenshots**
![IMG_5462](https://github.com/user-attachments/assets/125a910a-155b-49da-9a52-e1c1cc369ca6)

**Comment by antonym** [comment]
Ubuntu Live KDE 20.04 and 22.04 both booted fine for me, make sure you are on latest 2.0.80 build and have the latest versions.

**Comment by oe3gwu** [comment]
I am on 2.0.80 and it doesnt work. I can recreate it with a new PXE install and also on Proxmox and Bare Metal!

But I am too annoyed of netboot.xyz for now. It is messy and totally  buggy. I go to iVentoy PXE. Do with the issues I created what you want. I am off.
