### ISSUE TITLE
Tails assets missing

### ISSUE THREAD

**Issue by Kreeblah** [netbootxyz/netboot.xyz#1507]
[x]: This bug persists when memory is increased beyond 8GB.

**Describe the bug**
I recently installed netboot.xyz 2.0.81 and had it cache all the assets.  However, it seems that the Tails image leads to a 404.  It looks like the same asset location is in the current repo, so I'm guessing it's not just a matter of the link being outdated.

**To Reproduce**
1. Go to https://github.com/netbootxyz/asset-mirror/releases/download/6.5-cfd50f75/tails-amd64-6.4.iso

**Expected behavior**
The asset should exist there and begin downloading.

**Comment by antonym** [comment]
Yeah, there was a bug that was merging in multiple versions of the files. The 6.5 iso is there but the 6.4 iso shouldn't be there or be listed. Should be corrected next release, the change is already put into development.

Thanks!
