### ISSUE TITLE
direct IP for download server

### ISSUE THREAD

**Issue by divinity76** [netbootxyz/netboot.xyz#1546]
**Is your feature request related to a problem? Please describe.**

Rarely I need to boot a HP ILO server or a Dell iDRAC server with broken DNS, 
where I can pick a URL to boot a ISO from, then I have to set up a server with direct IP access. Right now I have set up http://130.162.215.57/netboot.xyz.iso to be able to mount netboot.xyz on a HP ILO without DNS, but about a year ago I had to do the exact same thing.

**Describe the solution you'd like**

a netboot.xyz download server supporting direct ip access and http (non-https) listed on https://netboot.xyz/downloads/

**Describe alternatives you've considered**

setting up my own netboot.xyz download server with direct ip access: http://130.162.215.57/netboot.xyz.iso

http://185.223.30.65/dedicatedisos

**Additional context**

![image](https://github.com/user-attachments/assets/fcfac990-939d-494f-adf6-e2f17471b650)

**Comment by antonym** [comment]
Currently not looking at doing a single IP to host the binaries, it can lead to abuse. It is very easy however to set up a container on a server to host the latest binaries. I'd suggest doing that instead with an IP you own:

https://netboot.xyz/docs/docker

**Comment by divinity76** [comment]
>it can lead to abuse

can you elaborate on that? what kind of abuse would a direct ip download allow, which won't work when the http host-header is present?
