### ISSUE TITLE
please move grml to liveCDs section

### ISSUE THREAD

**Issue by ttyS4** [netbootxyz/netboot.xyz#1549]
**Is your feature request related to a problem? Please describe.**
When looking for grml I was unable to find it. (Later I was told to look in the Utilities section where I found it.)

**Describe the solution you'd like**
Please move grml under the Live CDs section.

I discussed with the grml developers and they agree it would be better in the Live CDs.

Thanks in general, i am happy with netboot,xyz

**Comment by mika** [comment]
Thanks @antonym! :heart:
