### ISSUE TITLE
[Request] Add new category Firmware Update ISOs for (NVMe) drives

### ISSUE THREAD

**Issue by Firminator** [netbootxyz/netboot.xyz#1552]
Antonym, is it possible to PXE-load SSD FW update ISOs? Through memdisk or whatever is being used these days? In the long distance past Crucial used to have ISOs that were PXE-bootable. It was a TinyCore distro with the FW update autostarting, but that's like 10 years ago. Idk if they still do or if they moved away, however Samsung has been offering for years now ISOs to update the firmware of SSDs.
This is important for Linux users due to Samsung not offering FW updates for consumer drives for Linux (only Windows is supported by their Magician Toolbox). LVFS doesn't support consumer drives either (see https://fwupd.org/lvfs/search?value=samsung )

Here are some links to 3 of their newish drives
* https://download.semiconductor.samsung.com/resources/software-resources/Samsung_SSD_990_PRO_4B2QJXD7.iso
* https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_980_PRO_5B2QGXA7.iso
* https://download.semiconductor.samsung.com/resources/software-resources/Samsung_SSD_980_3B4QFXO7.iso

They have about a dozen more @ https://semiconductor.samsung.com/consumer-storage/support/tools/

Seagate also has linux support, albeit no bootable FW afaik, just the goold old trusty bootable Seatools ISO @ https://www.seagate.com/content/dam/seagate/migrated-assets/old-support-files/seatools/USBbootSetup-SeaToolsBootable.zip
I remember a discussion here somewhere years ago where this was requested and you showed interest in adding a new category for Firmware. Basically I'm trying here to bring this back on the table for discussion.

Btw WD: support for Linux not existant for consumer drives

**Comment by antonym** [comment]
Firmware tends to change pretty rapidly and it would probably go out of date often. I agree it'd be a great option but the maintenance of it and the breadth of the hardware would make it unmanageable.

If there are generic tools out there made by vendors that can detect versions and select firmware like what Dell has and boot over the network in Linux, I'm more open to those. Updating one tool that will manage mange versions and hardware is significantly easier to maintain.

**Comment by Firminator** [comment]
One more comment before I get off your back :)

> Firmware tends to change pretty rapidly

Usually yes and I agree this would create a never-ending stream of work. However the FW update ISOs I'm proposing to add into the netboot.xyz menu are Samsung consumer drives, not enterprise (also the DELL SUU ISO for example last time I used it several years was 8 GB, so unbootable over internet really). The FW on these SSDs drives doesn't change as often as Dell/HP server branded drives. There are maybe one or two updates after market release and then a third or fourth over the life span of those consumer drives... if at all (depending how severe an issues is and if there is significant enough public pressure/negative press).

> breadth of the hardware would make it unmanageable.

There are only 22 drives w/ available FW listed on the Samsung site. Only 8 are possible candidates for future updates as some of Samsung's more or less recent SSD lineup doesn't even have FW updates available. The rest of them are EOL/EOS and won't receive updates anymore (so there is no maintenance here involved).
Also Samsung is the only vendor I know of who actually has publically linkable ISOs that could be booted with memdisk which is yet to be tested. So currently there is no risk that this would become unmanageable (albeit wishful thinking that other vendors do create bootable ISOs or join the LVFS .

Given that there is a market for used SSD drives for use in a spare linux laptop/desktop and/or hand downs to relatives or family members after an upgrade to a newer drive, I'd argue that easy accessible FW updates through a PXE boot menu are a thing and would make this a breeze.


SATA drives (only 1 drive that is not yet EOL/EOS, so no maintenance really)

- (2009-??) SSD-470               (3 yrs warranty) - [AXM09B1Q.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_470_AXM09B1Q.iso)
- (2011-09) SSD-830               (3 yrs warranty) - [CXM03B1Q.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_830_CXM03B1Q.iso)
- (2012-10) SSD-840 PRO           (5 yrs warranty) - [DXM06B0Q.iso](https://semiconductor.samsung.com/resources/software-resources/DXM06B0Q.iso) 
- (20??-??) SSD-840               (? yrs warranty) - [DXT09B0Q.iso](https://semiconductor.samsung.com/resources/data-sheet/DXT09B0Q.iso)
- (2013-08) SSD-840 EVO/EVO mSATA (3 yrs warranty) - [EXT0DB6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_840_EVO_EXT0DB6Q_Win.iso)
- (2014-07) SSD-850 PRO           (10 yr warranty) - [EXM04B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_850_PRO_EXM04B6Q_Win.iso)
- (2014-12) SSD-850 EVO           (5 yrs warranty) - [EMT02B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_850_EVO_EMT02B6Q_Win.iso)
- (2018-01) SSD-860 PRO           (5 yrs warranty) - [RVM02B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_860_PRO_RVM02B6Q_Win.iso)
- (2018-01) SSD-860 EVO           (5 yrs warranty) - [RVT04B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_860_EVO_RVT04B6Q_Win.iso)
- (2018-01) SSD-860 EVO M.2       (5 yrs warranty) - [RVT24B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_860_EVO_M.2_RVT24B6Q_Win.iso)
- (2018-01) SSD-860 EVO mSATA     (5 yrs warranty) - [RVT44B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_860_EVO_mSATA_RVT44B6Q_Win.iso)
- (2018-12) SSD-860 QVO           (5 yrs warranty) - [RVQ02B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_860_QVO_RVQ02B6Q_Win.iso)
- (2019-01) SSD-870 EVO v5        (5 yrs warranty) - [SVT02B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_870_EVO_SVT02B6Q_Win.iso)
- (2019-01) SSD-870 EVO v6        (5 yrs warranty) - no FW update released
- (**2020-06**) SSD-870 QVO           (**5 yrs** warranty) - [SVQ02B6Q_Win.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_870_QVO_SVQ02B6Q_Win.iso)


NVMe drives (7 drives that are not EOL/EOS where maintenance would be needed; 3 of which with no FW updates released yet)

- (2015-10) SSD-950 PRO           (5 yrs warranty) - [2B0QBXX7.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_950_PRO_2B0QBXX7.iso) (no more changes)
- (2016-10) SSD-960 PRO           (5 yrs warranty) - [2B6QCXP7.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_960_PRO_2B6QCXP7.iso) (no more changes)
- (2016-10) SSD-960 EVO           (5 yrs warranty) - [3B7QCXE7.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_960_EVO_3B7QCXE7.iso) (no more changes)
- (2018-05) SSD-970 PRO           (5 yrs warranty) - no FW update released
- (2018-05) SSD-970 EVO           (5 yrs warranty) - [2B2QEXE7.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_970_EVO_2B2QEXE7.iso) (no more changes)
- (2019-02) SSD-970 EVO Plus v5   (5 yrs** warranty) - no FW update released yet
- (**2021-??**) SSD-970 EVO Plus v6   (**5 yrs** warranty) - no FW update released yet
- (**2020-09**) SSD-980 PRO           (**5 yrs** warranty) - [5B2QGXA7.iso](https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_980_PRO_5B2QGXA7.iso)
- (**2020-09**) SSD-980 v5            (**5** yrs warranty) - [3B4QFXO7.iso](https://download.semiconductor.samsung.com/resources/software-resources/Samsung_SSD_980_3B4QFXO7.iso)
- (**2023-12**) SSD-980 v6            (**5 yrs** warranty) - no FW update released yet [v6 is using a revised manufacturing process that doesn't require FW update (yet)?]
- (**2023**-??) SSD-990 PRO v7/v8     (**5 yrs** warranty) - [4B2QJXD7.iso](https://download.semiconductor.samsung.com/resources/software-resources/Samsung_SSD_990_PRO_4B2QJXD7.iso)
- (**2024-09**) SSD-990 EVO Plus      (**5 yrs** warranty) - [2B2QKXG7.iso](https://download.semiconductor.samsung.com/resources/software-resources/Samsung_SSD_990_EVO_PLUS_2B2QKXG7.iso)
- (**2024-??**) SSD-990 QVO           (**5? yrs** warranty) - no FW update yet

If you can show me how and where to implement those in the menu I could give it a try. I'm not a coder really (although I did manage to create my own custom working PXE menu years ago chainloading off your menu thanks to your work @ https://github.com/netbootxyz/netboot.xyz-custom ) but updating a few links is easy enough. Having those drives available in the menu would be start. Maybe put it in the development or Testing branch to get the ball rolling, and then we can see how it plays out updating the links to the ISO throughout the lifecycle of the drives?

Not a problem if you still disagree and close this out. I'm just trying to clarify what the workload would look like from my understanding.
