### ISSUE TITLE
Grml-(full|small) 2024.12 has incorrect URLs and paths

### ISSUE THREAD

**Issue by zeha** [netbootxyz/netboot.xyz#1554]
Pull requests to fix the 2024.12 version bump, hopefully:

- https://github.com/netbootxyz/debian-squash/pull/2
- https://github.com/netbootxyz/debian-squash/pull/1

**Comment by antonym** [comment]
Give the development endpoint a try and see if it looks good now, will work on adding arm64 versions next.

**Comment by zeha** [comment]
@antonym sorry, I messed up the names in the ISO. I imagine you noticed while adding arm64...

The layout unfortunately is inconsistent and looks like this, with grml-small arm64 as an example:

```
./live/grml-small-arm64/grml-small-arm64.squashfs
./boot/grmlsmallarm64/initrd.img
./boot/grmlsmallarm64/vmlinuz
```

We should fix this in the next release :(

**Comment by antonym** [comment]
Yeah no worries, if y'all end up changing it, just let me know or the bot will fail the next time it runs. Arm versions up in devel too now.
