### ISSUE TITLE
Architect is no more

### ISSUE THREAD

**Issue by ghost** [netbootxyz/netboot.xyz#157]
Architect Linux entry in linux boot options fails

**Comment by antonym** [comment]
Looks like the option still works but it looks like their boards are down.  It does give the appearance of a dead project as there haven't been any releases in a while.  I'll see about getting this option pulled.  Thanks!

**Comment by antonym** [comment]
https://github.com/antonym/netboot.xyz/commit/1d8cf72e0d03c1b7c9b00dabbbc66e1fb831718c

Dropped for now.
