### ISSUE TITLE
Addition of pfsense?

### ISSUE THREAD

**Issue by kurobeats** [netbootxyz/netboot.xyz#165]
I don't know if it's feasible but would love to see a pfsense option.

**Comment by jolebole** [comment]
It would be really nice to have pfSense as an option :)

**Comment by ehuggett** [comment]
will it be a problem that the usb/iso images on the mirrors are gzip compressed?

The 4 mirrors linked from the [download page](https://www.pfsense.org/download/) are

https://nyifiles.pfsense.org/mirror/downloads/
https://atxfiles.pfsense.org/mirror/downloads/
https://frafiles.pfsense.org/mirror/downloads/
https://sgpfiles.pfsense.org/mirror/downloads/

It appears every time a new release is made the previous release is removed from the mirror, however the first two mirrors have an "old" subdirectory from which previous versions could be fetched.

**Comment by antonym** [comment]
Memdisk can extract a gzip'd image in some cases. I'd love to add it but I tried this out a few weeks ago and didn't have much success using memdisk with it.  It has issues mounting the actual img/iso data from memdisk once the kernel loads up.

**Comment by antonym** [comment]
Might be worth a revisit with hosted images.

**Comment by orange888** [comment]
Please support pfsense and OPNsense. Thanks.

**Comment by MaxPeal** [comment]
+1

**Comment by diwu1989** [comment]
+1 for OpnSense
