### ISSUE TITLE
RHEL support

### ISSUE THREAD

**Issue by pgera** [netbootxyz/netboot.xyz#173]
Since Centos works, RHEL should be quite similar. RHEL isos are publicly available at https://developers.redhat.com/products/rhel/download/ . One issue is that RHEL doesn't have a public mirror. So an intermediate step would be needed to go from ISO to vmlinuz, initrd etc. 

Edit: Looks like the isos also need registration. So it probably won't work as is. Maybe a general template, where the user can provide a url to the mounted iso would be a better idea ? A generic template would also work for other RHEL products since they all use RHEL as the base system.

**Comment by antonym** [comment]
Yeah, the licensed distros are tricky, so I had thought about doing RHEL and even VMware ESX the same way Windows is done, where you just specify the location of the extracted ISO and then it can kick off the installer for you without having to boot a CD.

If that would be useful, I can see about adding that.

**Comment by pgera** [comment]
Yes, that would be useful. I was already able to use this by editing the centos template. So hopefully, it should be straightforward.

**Comment by antonym** [comment]
Support added: https://github.com/antonym/netboot.xyz/pull/184
