### ISSUE TITLE
Build Intructions

### ISSUE THREAD

**Issue by kurobeats** [netbootxyz/netboot.xyz#175]
Just wondering if you might be able to provide build instructions for development and alike, such as:

1. install dependencies
2. git clone
3. make changes to code
4. run ./build_script.sh

**Comment by MitchRatquest** [comment]
It went like this for me (on debian 9):
sudo apt-get install liblzma-dev
git clone https://github.com/antonym/netboot.xyz.git
cd netboot.xyz
cp script/prep-release.sh .
./prep-release.sh

**Comment by webairnetboot** [comment]
This seems like a duplicate of [Self-hosting Instructions #26](https://github.com/antonym/netboot.xyz/issues/26 )

**Comment by dszidi** [comment]
This is not quite correct. Running the prep-release.sh fails because there are no .crt files in the repo.
