### ISSUE TITLE
GParted boot signature broken

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#177]
The GParted boot no longer works with image signature checks enabled.

The sha256 hash of the netboot.xyz iso: 31fe9dffa917ccb4b1ebfd5f3ac80d661d8d89d1f6c6688861e9b1b281f0f7f6

**Comment by antonym** [comment]
Updated the signature for this so give it a try in a bit once it gets through CI.

**Comment by necrophcodr** [comment]
Confirmed to be resolved.

Verification of this failed initially due to #183
