### ISSUE TITLE
Arch Linux 2017.06.01 boot broken.

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#178]
The boot fails with "No such file or directory"

All newer versions appear to boot and verify correctly.

The sha256 hash of the netboot.xyz iso: 31fe9dffa917ccb4b1ebfd5f3ac80d661d8d89d1f6c6688861e9b1b281f0f7f6

**Comment by antonym** [comment]
2017.06.01 dropped off the mirror so dropped it off the menu and grabbed the latest one.

https://github.com/antonym/netboot.xyz/commit/a963028a0c3cca7e0dbcce3bcb1a582429e98f19
