### ISSUE TITLE
Gentoo Linux boot initrd broken

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#179]
The Gentoo Linux initrd fails with "No such file or directory" and "Operation not permitted"

The sha256 hash of the netboot.xyz iso: 31fe9dffa917ccb4b1ebfd5f3ac80d661d8d89d1f6c6688861e9b1b281f0f7f6

**Comment by antonym** [comment]
URL is fixed for now with https://github.com/antonym/netboot.xyz/pull/355 but I'll probably need to get around to regenerating a newer image.
