### ISSUE TITLE
WindowsRE Support

### ISSUE THREAD

**Issue by zQueal** [netbootxyz/netboot.xyz#18]
A Windows recovery environment would be a huge help and a great addition, I think. I like to keep a RE disk/USB drive around somewhere because we all know unexpected issues happen with Windows every now and again. This would free up my USB drive from the RE to just netboot and I'd still be able to use the RE any time I needed it.

If you need a disk image, it can be arranged. I checked out the code in an attempt to do it myself, but it's a bit out of my range of expertise.

**Comment by antonym** [comment]
Yeah, I'd love suggestions on a disk or what you'd like to see built.  I had a basic WinPE environment based on Windows 10 that works but I need to find a place to also host the disks so I don't have to think about bandwidth issues.  I pulled it down this morning until I can find a better place with more unlimited bandwidth to host the disks.

**Comment by zQueal** [comment]
> but I need to find a place to also host the disks so I don't have to think about bandwidth issues. I pulled it down this morning until I can find a better place with more unlimited bandwidth to host the disks.

I actually may be able to help with this. Could you send me the image, and I'll give it a test and see if it works. What kind of bandwidth issues were you dealing with? Do you have any concrete numbers? 1TB/mo, 5TB/mo?

As for the WindowsRE, ~~I'm making an ISO right now.~~[Here's the ISO.](https://drive.google.com/file/d/0B8k_4qN8q8fOU0IxLVRJWG82bHM/view?usp=sharing) As far as I know, though, it's x86_64 only and you cannot roll both into the same image. Additionally, because I'm working with x86_64, I cannot get the image for 32-bit.

**Comment by antonym** [comment]
I'll probably be able to find a spot to host them this week.  Do you have any build instructions or links you might be able to post that would provide a useful tool?  The image I had was just a basic Windows 10 WinPE disk.  I'd probably build some automation to regenerate the image and then figure out how to make that public facing so the actual build can be trusted to a degree.

**Comment by awiddersheim** [comment]
The Hanlon and Razor projects have some nice scripts to generate these:

https://github.com/csc/Hanlon/blob/master/scripts/winpe/build-winpe.ps1
https://github.com/puppetlabs/razor-server/tree/master/build-winpe

I also have one that is based on their work that is slightly trimmed down and adds a few things:

https://gist.github.com/awiddersheim/fa7bbce450df57e35af3

**Comment by alebcay** [comment]
iPXE already provides some information on how to boot WinPE/WinRE by using the [`wimboot`](http://ipxe.org/wimboot) bootloader right [here](http://ipxe.org/howto/winpe).
