### ISSUE TITLE
AVG Rescue CD boot signature broken

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#180]
The AVG Rescue CD fails when downloading signature with the error "No such file or directory".

With image signature check disabled, it boots as intended.

The sha256 hash of the netboot.xyz iso: 31fe9dffa917ccb4b1ebfd5f3ac80d661d8d89d1f6c6688861e9b1b281f0f7f6

**Comment by antonym** [comment]
Updated the signature as it was out of date.

Thanks

**Comment by chris18890** [comment]
apologies, that was my bad, I bumped the version but didn't regenerate the sigs, sorreh! :(

**Comment by antonym** [comment]
No worries... I need to invest sometime into getting the signatures better... it's not ideal right now as it's a bit of maintenance.

**Comment by necrophcodr** [comment]
Confirmed to be resolved.
