### ISSUE TITLE
CloneZilla signature fails

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#181]
CloneZilla signature check fails with "No such file or directory".

When image signature check is disabled, it boots as intended.

The sha256 hash of the netboot.xyz iso: 31fe9dffa917ccb4b1ebfd5f3ac80d661d8d89d1f6c6688861e9b1b281f0f7f6

**Comment by antonym** [comment]
Clonezilla bumped to 2.5.2-31 and signatures regenerated for that version.

https://github.com/antonym/netboot.xyz/commit/9a9292c5438d6d6abe4a650d57773a77dc1adab0

Thanks

**Comment by chris18890** [comment]
apologies, that was my bad, I bumped the version but didn't regenerate the sigs, sorreh! :(

**Comment by necrophcodr** [comment]
Confirmed to be resolved.
