### ISSUE TITLE
Hardware Detection Tool boot fails

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#182]
The Hardware Detection Tool fails booting with error "No such file or directory".

The sha256 hash of the netboot.xyz iso: 31fe9dffa917ccb4b1ebfd5f3ac80d661d8d89d1f6c6688861e9b1b281f0f7f6

**Comment by antonym** [comment]
Looks like http://www.hdt-project.org/ is no longer hosting the project so I'll remove it unless I get an updated/trusted source.

https://github.com/antonym/netboot.xyz/commit/eef9a191c59528bfe8b8fb4cd478e8666039b9bc

Thanks!
