### ISSUE TITLE
Sourceforge.net not properly mirroring data

### ISSUE THREAD

**Issue by necrophcodr** [netbootxyz/netboot.xyz#183]
It appears that a lot of the issues I've reported (where more was to come) can be a result of Sourceforge.net having a really broken data mirror, where a lot of data may not be mirrored everywhere, and thus may return that the file is unavailable.

I suggest using a different host or mirroring service that actually provides the data.

**Comment by abitrolly** [comment]
Is it possible to write test for this issue to confirm?

**Comment by thelamer** [comment]
Closing as this is resolved
