### ISSUE TITLE
issue with vlan?

### ISSUE THREAD

**Issue by o0-o** [netbootxyz/netboot.xyz#185]
Having an issue that appears to be caused by vlan tagging, or maybe a DHCP quirk.

netboot.xyz loads to the point of connecting to boot.netboot.xyz/menu.ipxe and then fails.

I am only seeing this in when vlans are in play. The traffic is being tagged by the switch (not a trunk or anything), so should be invisible to netboot...

The odd thing is that if I manually enter the network info exactly as the DHCP server would assign it, then everything works. I was able to install CentOS without any problems. Once netboot loads the CentOS installer, the DHCP address is picked up and everything is normal.

The attached screenshot is from vm but I am also seeing this on physical servers.

Any ideas?

![screen shot 2017-09-26 at 3 45 01 pm](https://user-images.githubusercontent.com/17324878/30881310-60c32f48-a2d3-11e7-8c05-ef3466d73269.png)

**Comment by o0-o** [comment]
After further testing, I found an issue with my DNS configuration on my DHCP server.

The only issue here is that netboot.xyz will not use a secondary DNS server provided by a DHCP server. This is why it was failing while installed OS's were not having issues.

**Comment by antonym** [comment]
Cool, glad you got it fixed.  Yeah, I think iPXE will only use the first DNS server provided.
