### ISSUE TITLE
memtest doesn't start

### ISSUE THREAD

**Issue by abitrolly** [netbootxyz/netboot.xyz#191]
Memtest+ 4.20 and 5.01 just returns to menu.

**Comment by antonym** [comment]
Both run for me testing in Virtual Box (x86).  Are you running EFI by chance?

**Comment by abitrolly** [comment]
It is amd64 system for sure. How to check if it is EFI?

**Comment by timwsuqld** [comment]
Same issue. Laptop running in legacy bios mode, amd64
I also tried select i386 in netboot, and turning off signature checking, no difference. If an error is shown, it's too quick to see.

**Comment by matti** [comment]
It doesn't work on physical hardware (it seems) - it has something to do with this page (maybe) http://ipxe.org/err/460381

see: http://ipxe.org/cfg/vram for a working version

here's my config:
```
#!ipxe
dhcp
chain http://boot.ipxe.org/memtest.501
```

**Comment by LukeHandle** [comment]
Looks like it moved to `http://boot.ipxe.org/memtest.0` , but this runs via the iPXE shell 👍

I got http://ipxe.org/err/460381 for both 4.20 and 5.01 (XenServer 7.2 / Xen 4.7.2 guest)

**Comment by antonym** [comment]
I updated the binary to the one from ipxe.org, give it a try and let me know if you have any success with it.  It appears to work in Vbox for me.

**Comment by LukeHandle** [comment]
LGTM

**Comment by antonym** [comment]
Closing this out as it appears to be resolved.  Feel free to reopen if there are still issues.

**Comment by dadatuputi** [comment]
I'm having this issue at the moment. No error message, but it works using the ipxe shell and the command `chain http://boot.ipxe.org/memtest.0`.
