### ISSUE TITLE
Void Linux Support

### ISSUE THREAD

**Issue by antonym** [netbootxyz/netboot.xyz#195]
Investigate Void Linux (https://www.voidlinux.eu/) and see if they are iPXE friendly, looks like they have some scripts for netbooting:

https://github.com/voidlinux/void-mklive

**Comment by samip5** [comment]
They have renamed their repo, it can be found here: https://github.com/void-linux/void-mklive. You'll probably thank me later when you get around to adding it.

**Comment by antonym** [comment]
Investigating adding as Live OS: https://github.com/void-linux/void-mklive/issues/97
