### ISSUE TITLE
DBAN Support

### ISSUE THREAD

**Issue by asmartin** [netbootxyz/netboot.xyz#20]
Would it be possible to add [DBAN](http://www.dban.org/) to the list of supported distros?

**Comment by antonym** [comment]
Let me know if you run into any issues with it.  Thanks for the suggestion!

**Comment by asmartin** [comment]
Thanks for implementing this so quickly! I'll test it out and report if I
encounter problems

**Comment by asmartin** [comment]
Thanks for implementing this so quickly! I'll test it out and report if I
encounter problems

Closed #20 https://github.com/antonym/netboot.xyz/issues/20.

—
Reply to this email directly or view it on GitHub
https://github.com/antonym/netboot.xyz/issues/20#event-512889971.

**Comment by patrickbussmann** [comment]
Its deleted now 👎
