### ISSUE TITLE
FreeBSD Installers wont boot

### ISSUE THREAD

**Issue by mcmufffin** [netbootxyz/netboot.xyz#205]
Hello Netboot Team,

first of all, impressive project! Thank you very much for your work! Its realy an time-saving project.

However, in the latest versions the freebsd-installered stopped working.
I can reproduce this issue on different systems with different hypvervisors. Unforechently i dont have any pysical system free which i could use for testing. 

The installer loads but you cant press any buttoms when it asks which user level to boot up.

Is there anything you guys can do about this?

Screenshot: https://imgur.com/a/TYetI

Kind regards!

**Comment by antonym** [comment]
I tested this in the newest VirtualBox (5.2.2) and it seemed to accept the input correctly.

**Comment by mcmufffin** [comment]
Thanks for your reply!

I thought the other system were a xen one (vserver) but i just looked it up and its kvm too, so both my systems were kvm (1x solusvm, 1x promox)

probabbly a bug within kvm then?


ill try another hypvervisor asap :)

thanks!

**Comment by mcmufffin** [comment]
Hello!

i can confirm that it also works in vmware player and the input gets accepted correctly. 

Seems to be a kvm related problem.

Kind regards

**Comment by antonym** [comment]
Closing this for now, but if you figure out the issue on KVM, please post it here.  Might also be worth checking the iPXE forums.

Thanks!
