### ISSUE TITLE
VLAN tagged interfaces

### ISSUE THREAD

**Issue by sumkincpp** [netbootxyz/netboot.xyz#219]
Would be great to be able to specify vlan tag(802.1q) for networking configuration during initial boot.

**Comment by willglynn** [comment]
One option: use [ROM-o-matic](https://rom-o-matic.eu) to make a custom iPXE image with an embedded script, [`vcreate`](https://ipxe.org/cmd/vcreate) your VLAN, configure the interface, and [chain into netboot.xyz](https://netboot.xyz/booting/ipxe/).

Would you be wanting to configure this interactively at boot time?

**Comment by thelamer** [comment]
This will be in the next release with https://github.com/netbootxyz/netboot.xyz/commit/67ab2b4729c9517d222a058d12e5b7b083703a3a

If you want to test it now you can pull a head build: 
https://s3.amazonaws.com/dev.boot.netboot.xyz/7047aeb500e5edbcced514d953583d84043e1851/index.html
