### ISSUE TITLE
Update wimboot to version 2.6.0

### ISSUE THREAD

**Issue by barnabyc** [netbootxyz/netboot.xyz#220]
Hi there,

Love the project. I recently wanted to use some newer features in wimboot, notably dynamic patching of winpeshl.ini and install.bat to kick-off Windows setup.

I realized wimboot 2.6.0 that enables dynamic patching is slightly newer than the one currently included in netboot.xyz. I would have opened a pull request although I wasn't entirely clear on how image signatures should be handled so in my custom menu I simply skipped verifying them.

Happy to help.
Thanks for the great project!

**Comment by antonym** [comment]
I updated wimboot back in January: https://github.com/antonym/netboot.xyz/commit/702f4851b310ecea91e1e43ea2b22a07039f7298

Let me know if it isn't pulling that version for whatever reason.

**Comment by barnabyc** [comment]
@antonym Oh thank you, so sorry, I did scroll back through commit history but missed this one. I'll give it a try today! (I think I was assuming netboot.xyz would show a version bump since I installed pre wimboot 2.6.0 - clearly I misunderstood.)

**Comment by antonym** [comment]
No problem, the versioning in netboot.xyz is related to the how the netboot.xyz iPXE bootloader is generated and really only used to pull a newer version of iPXE if it's required by the netboot.xyz code.
