### ISSUE TITLE
Unable to mount root fs with RancherOS and Set Github User menu boot

### ISSUE THREAD

**Issue by jpastuszek** [netbootxyz/netboot.xyz#224]
I am trying to get RancherOS booting with custom could-config URL using `Set Github User` feature.
When booting RancherOS form built-in menu it works OK.
If I boot using `chain` command from failsafe debug iPXE menu and point it to URL of my `custom.ipxe` it also boots OK. 
If I boot from same config file using `Set Github User` menu it fails to boot with missing root volume:
```VFS: Unable to mount root fs on unknown-block(0,0)```

Is there anything special that netboot does to the environment that could make it fail that way?

I am using Virtual Box and `custom.ipxe`:
```
#!ipxe
dhcp
set base-url https://releases.rancher.com/os/latest
kernel ${base-url}/vmlinuz printk.devkmsg=on rancher.debug=true rancher.state.dev=LABEL=RANCHER_STATE rancher.state.wait console=tty0 rancher.state.mdadm_scan console=ttyS1,115200n8 rancher.autologin=ttyS1 rancher.network.interfaces.eth*.dhcp=true rancher.cloud_init.datasources=[configdrive,ec2,gce,packet,digitalocean]
initrd ${base-url}/initrd
boot
```
I have also tried to just copy content the `archeros.ipxe` from this repository to my `custom.ipxe` but I got same problem.
I am using netboot.xyz v.1.0.4; I have also tired master branch of this repository using `Test netboot.xyz branch`.

**Comment by jpastuszek** [comment]
To reproduce OK boot:

Press `m` to get into failback mode and select `iPXE Debug Shell`. Type:
```
dhcp
chain http://goo.gl/bkF6V4
```

http://goo.gl/bkF6V4 points to https://raw.githubusercontent.com/jpastuszek/netboot.xyz-custom/master/custom.ipxe of following content:
```
#!ipxe
dhcp
set base-url https://releases.rancher.com/os/latest
kernel ${base-url}/vmlinuz printk.devkmsg=on rancher.debug=true rancher.state.dev=LABEL=RANCHER_STATE rancher.state.wait console=tty0 rancher.state.mdadm_scan console=ttyS1,115200n8 rancher.autologin=ttyS1 rancher.network.interfaces.eth*.dhcp=true rancher.cloud_init.datasources=[configdrive,ec2,gce,packet,digitalocean]
initrd ${base-url}/initrd
boot
```

You should see RancherOS login prompt.

Failed boot:

Let netboot.xyz boot full.
Go to `Utilities` -> `Set Github User` and type: `jpastuszek`.
Then go to `iPXE shell` and type same chain URL:
```
chain http://goo.gl/bkF6V4
```
Kernel will panic.

**Comment by jpastuszek** [comment]
Actually by just going to `Utilities` and coming back will cause boot failure.

**Comment by jpastuszek** [comment]
Actually going to any menu and coming back will make this OS fail to boot...

**Comment by jpastuszek** [comment]
Same issue with real Dell PC.

**Comment by antonym** [comment]
Good find, I was able to repro.  I think it might need an imgfree before loading the kernels, giving that a try.

**Comment by antonym** [comment]
This appeared to fix it: https://github.com/antonym/netboot.xyz/commit/e4d041323ae9725dd1f3476aba81495c090ab87d.  If you continue to have issues with it, please reopen.

Thanks!
