### ISSUE TITLE
Pogostick option

### ISSUE THREAD

**Issue by chris18890** [netbootxyz/netboot.xyz#23]
I think a really useful tool to have under the utilities section would be [PogoStick](http://pogostick.net/~pnh/ntpasswd/), I use it pretty often, & can PXE boot it locally, but am unsure if it can be made to work with netboot.xyz

When unpacked, the Pogostick ISO takes up about 16 MB

**Comment by chris18890** [comment]
have tested & managed to get my normal PXE server to boot a local copy of the ISO with memdisk!

Now to try opening the iso over t'internet...

The main problem is that it's stored on the website as a ZIP, do you know if that can be unpacked on the fly?

**Comment by antonym** [comment]
I gave it a try and it appears that MEMDISK decompressed the zip on the fly (learned something new) so it got to the initial menu, but then promptly kernel crashed in Fusion.  It did fully load in Virtual Box though and got to the menu.  I'll mock up an option and you can give it a try via the test branch.

**Comment by chris18890** [comment]
Great, thanks! :) Also CC'd you in on an intro email to the project owner, in the interest of keeping everyone in the loop

**Comment by antonym** [comment]
https://github.com/antonym/netboot.xyz/pull/34

**Comment by chris18890** [comment]
successfully tested on a ~3 yr Alienware, will test more thoroughly tomorrow if needed :)

**Comment by antonym** [comment]
https://github.com/antonym/netboot.xyz/pull/34
