### ISSUE TITLE
variable arch5 defined, but not used anywhere?

### ISSUE THREAD

**Issue by Firminator** [netbootxyz/netboot.xyz#230]
Just noticed this while trying to figure out how to deal w/ i386 architecture variants in download pathes (i486, i586, i686)
https://github.com/antonym/netboot.xyz/blob/0857dd317bc7dc69b5213d231b1743ada4eadfda/src/menu.ipxe#L38

**Comment by antonym** [comment]
Resolved with https://github.com/antonym/netboot.xyz/commit/a1eaf86b41446e785175bcf69590bb2e891a898a
