### ISSUE TITLE
Arch Linux i686/x86/32bit sunsetted

### ISSUE THREAD

**Issue by Firminator** [netbootxyz/netboot.xyz#231]
https://github.com/antonym/netboot.xyz/blob/0857dd317bc7dc69b5213d231b1743ada4eadfda/src/archlinux.ipxe#L22
This fails on a test laptop as they removed the i686 architecture folder and it's 64bit only these days.

see
2017-01: https://www.archlinux.org/news/phasing-out-i686-support
and
2017-11: https://www.archlinux.org/news/the-end-of-i686-support

Yet, over @ https://mirror.archlinux32.org/archisos they have 32bit and 'Dualboot' ISOs. Not sure if they boot using memdisk.

**Comment by antonym** [comment]
Yeah, if they aren't there anymore, we can probably remove that line.

**Comment by antonym** [comment]
Resolved with https://github.com/antonym/netboot.xyz/commit/a1eaf86b41446e785175bcf69590bb2e891a898a
