### ISSUE TITLE
goto error

### ISSUE THREAD

**Issue by Firminator** [netbootxyz/netboot.xyz#232]
Question for understanding:
https://github.com/antonym/netboot.xyz/blob/f1173291cfa178e25c2662557b4c99fdd56c625b/src/archlinux.ipxe#L34
Does this 'goto error' fail since there is no :error label in the archlinux.ipxe config or will it 'remember'/refer to the one and only :error label in the menu.ipxe?

**Comment by antonym** [comment]
It should circle back to the one in menu.ipxe since it's still loaded in memory.
