### ISSUE TITLE
Add an easy way to check RAM and HDD/SDD/Flash for errors

### ISSUE THREAD

**Issue by abitrolly** [netbootxyz/netboot.xyz#235]
There is no easy way to check local storage and RAM for errors before installing operating system. There is memtest, but I couldn't run last time due to some 64bit/UEFI problems, and for storage it is not clear what command to run at all. [Ubuntu SO](https://askubuntu.com/questions/14303/how-can-i-check-my-ram-and-hard-drive-for-errors) lists several alternatives, but Googling for them and trying is not easy.

Maybe there is a minimal bootable Live Linux image with very simple user interface, which contains all necessary drivers to load and check both memory and hardware, which could be included as an easy option into `netboot.xyz`?

**Comment by gmiranda** [comment]
I'd recommend google's stressapptest (https://github.com/stressapptest/stressapptest). As far as I know, there's no live distro that includes it by default, but it's easily installed in Debian, Mint, Ubuntu and others.

As for storage, Gnome disk utility works just fine and it's already loaded by default in most distros.

**Comment by thelamer** [comment]
Base general purpose live CDs are coming in our next version : 
https://s3.amazonaws.com/dev.boot.netboot.xyz/999a90aa2875f9cfb51c76a7db6d94299e933322/index.html

With this range of Live CDs particularly Debian/Ubuntu you should be able to install and run any test suite you choose.

**Comment by abitrolly** [comment]
@thelamer is there a specific option you can recommend for those coming to this ticket to solve the particular problems of checking
1. memory
2. flash cards
3 ssd/hdd

**Comment by thelamer** [comment]
@abitrolly this is not really my area of expertise, you need to understand we as an organization concentrate on being able to boot existing Distributions off the internet. If you find something and it looks like a tool we should add to the menus and has a relatively low bar to getting it to boot off the internet please open a new issue. 

As a non expert though: 

https://wiki.ubuntu.com/PhoronixTestSuite (the best in open source for benchmarking and generating reports for all branches of stuff including IO) 
https://wiki.archlinux.org/index.php/Stress_testing (some info from the folks at arch on running tools to test CPU/mem)

If you are looking for something that boots runs a series of tests then gives you a green status page, I can tell you that does not exist, you would need to build it.

**Comment by abitrolly** [comment]
> If you are looking for something that boots runs a series of tests then gives you a green status page, I can tell you that does not exist, you would need to build it.

That's exactly what I am looking for. RAM and HDD/SDD/Flash tests to be exact.
