### ISSUE TITLE
Errors...?

### ISSUE THREAD

**Issue by paveldanek** [netbootxyz/netboot.xyz#236]
Hi, this is Pavel.
I tried to run the prep-release.sh script and I’ve run into some possible errors.
First of all, on line 16, the shell threw an error, that “no *.crt files exist”. When I excluded the line from the script and started compiling the iPXE, I’ve got some additional errors, like “error opening certificate ca-netboot-xyz.crt” (which may be related) and also some errors within iPXE, which, of course, don’t have anything to do with you, like an error compiling crypto/rootcert.c (invalid suffix “x” on integer constant), or a fatal error in util/zbin.c (lzma.h: no such file or directory), etc.
Are those known errors and what can I possibly do to get past them?
Thank you for your answer.
-Pavel.

**Comment by antonym** [comment]
The prep-release script is mainly used for prepping the main netboot.xyz site so I wouldn't recommend using that for day to day.

If you just want to compile iPXE, I'd recommend visiting the iPXE forums if you're running into compiling errors.  If you want to chain to netboot.xyz from your version, make sure you enable HTTPS.

For the lzma.h error, you'll probably need liblzma-dev (Debian) or the equivalent for the OS you're running.
