### ISSUE TITLE
Generate Certificates

### ISSUE THREAD

**Issue by burn2delete** [netbootxyz/netboot.xyz#237]
Hello,

Can we please get some instructions on how to generate certificates for netboot.xyz?

Currently I cannot build my own version using the existing script.

**Comment by dszidi** [comment]
I'm trying to work around this as well. It looks like the pre-release script is tailored for the netboot.xyz site. It looks like there are references to the netboot.xyz certificate authority. So my first guess for a place to start is create a CA and make sure the pre-release script only references your CA.

**Comment by thelamer** [comment]
This is coming in full self hosting, and automated building with Ansible. 
When Version 2.x is released we will have documentation on self hosting locally and hosting a Website endpoint with signatures. 
General preview: 
https://github.com/netbootxyz/netboot.xyz/tree/development

**Comment by thelamer** [comment]
Please see these instructions for self hosting: 
https://netboot.xyz/selfhosting/
If you are looking for a local only type thing we also have a web application for configuring one: 
https://hub.docker.com/r/linuxserver/netbootxyz

**Comment by antonym** [comment]
There's also a deep dive into setting up the certs on the iPXE site.  https://ipxe.org/crypto 

You can generate the certs needed there and then there are options in the Ansible for specifying cert locations so that it will build the images for you.
