### ISSUE TITLE
Centos 7.4 booting

### ISSUE THREAD

**Issue by sirdeiu** [netbootxyz/netboot.xyz#239]
Hi,

Centos 7.4 installer doesn't boot, after loading kernel and initramfs it dies with a timeout that it can't mount root. 

![1](https://user-images.githubusercontent.com/1190237/39862825-875de8e2-544d-11e8-9ee5-3e130c0457c5.jpg)
![2](https://user-images.githubusercontent.com/1190237/39862826-88b978a0-544d-11e8-826c-42ece839c0cb.jpg)

Anyone else seeing this?

**Comment by antonym** [comment]
It worked for me using Virtual Box, anything unique about your networking?  If it's a VM, does it have enough memory, etc?  It's trying to load the installer rootfs at that point, so during the kernel boot up it attempts to light up a NIC, get an address and retrieve the image.  It looks like in your case it's not getting to that point.
