### ISSUE TITLE
snponly.efi boot image

### ISSUE THREAD

**Issue by andrew-stclair** [netbootxyz/netboot.xyz#240]
Hello,

i have attempted to roll my own .efi image for netbooting that is small enough to fit on a router running OpenWRT (4MB flash, only have about 300k to work with, ~91k will be used for the kpxe image)

the resulting image did not function at all

is it possible to get an image made for the following Platform, Driver and Boot type?

`bin-i386-efi/snponly.efi`

i followed the build targets appnote on the ipxe.org site here:
https://ipxe.org/appnote/buildtargets

**Comment by thelamer** [comment]
All of our boot binaries provide all the tool chains we can (one of the biggest and core ones being https support) 
I think you would be better off hosting a small tftp server on something local outside of your router and pointing to the bins with these config options: 
```
uci set dhcp.@dnsmasq[0].dhcp_match=set:bios,60,PXEClient:Arch:00000
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:bios,netboot.xyz.kpxe,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi32,60,PXEClient:Arch:00006
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi32,netboot.xyz.efi,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi64,60,PXEClient:Arch:00009
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi64,netboot.xyz.efi,,YOURSERVERIP
uci commit
/etc/init.d/dnsmasq restart
```
