### ISSUE TITLE
After downloading the Windows installation file, wimboot prompts 'bad cpio magic'

### ISSUE THREAD

**Issue by ghost** [netbootxyz/netboot.xyz#247]
Hello, when I use ipmi to mount netboot.xyz.iso and restart to download the Windows installation file, wimboot prompts 'bad cpio magic'. Why is this?Thank you!

**Comment by ghost** [comment]
But the windows image I provide can work on the vultr machine via netboot.xyz.
I tried it twice on the machine that prompted 'bad cpio magic', but the same prompt appeared.

**Comment by ghost** [comment]
My server hardware is:
Processor: ATOM D525
Memory: 4G DDR2
Hard Disk: 120G SSD
Ipmi is Supermicro's

**Comment by ghost** [comment]
My iso name is cn_windows_10_multi-edition_version_1709_updated_dec_2017_x64_dvd_100406696.iso
Mounted to /var/www/html/x64
Web server is apache (httpd) installed via yum

**Comment by antonym** [comment]
May be resolved with recent commit: https://github.com/netbootxyz/netboot.xyz/commit/cef54a2ac3a288c1727fdd3da5c0bbb135f928b1
