### ISSUE TITLE
Improvements to boot method / TFTP / Edgerouter doc

### ISSUE THREAD

**Issue by ravens** [netbootxyz/netboot.xyz#249]
Hi,

reading the excellent https://netboot.xyz/booting/tftp/edgerouter/, I would propose the following enhancement:

- don't install any new package (tftpd) that will likely not survive any firmware update, use the TFTP server embedded into dnsmasq (DNS server of edgerouter) for this
- save PXE payload into the user data section of the firmware to survice firmware update (/config/user-data)

So my proposal:
- upon configuring the router (ssh, then configure); introduce the following commands:
```
set service dns forwarding  options enable-tftp
set service dns forwarding  options tftp-root=/config/user-data
set service dhcp-server global-parameters "option client-arch code 93 = unsigned integer 16;"
edit service dhcp-server shared-network-name LAN subnet 10.10.2.0/24
set bootfile-server 10.10.2.1
set bootfile-name netboot.xyz.kpxe
commit
save
```
 - perform the curl command in the following directory:
```
sudo curl -o /config/user-data/netboot.xyz.kpxe https://boot.netboot.xyz/ipxe/netboot.xyz.kpxe
```

Tested fine on my edgerouter lite 3 with 1.10.5 software version.

**Comment by antonym** [comment]
Sounds good to me, would you like to make a PR towards the docs here?

https://github.com/antonym/netboot.xyz-site/blob/master/content/booting/tftp/edgerouter/_index.md

I'm in the process of moving the docs out of the main repo to a doc site.

Thanks!

**Comment by ravens** [comment]
Tentative PR https://github.com/antonym/netboot.xyz-site/pull/1 . Closing this thread.
