### ISSUE TITLE
https://boot.netboot.xyz/ipxe/netboot.xyz.usb is broken

### ISSUE THREAD

**Issue by marcmerlin** [netbootxyz/netboot.xyz#252]
md5sum: f8243cfa1fe384b245cd50aad596ba5c  netboot.xyz.usb
It gives me this when I copy it to a USB key on linux:
[8485557.262586] sd 11:0:0:0: [sde] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[8485557.270013]  sde: sde3 sde4

Command (m for help): p
Disk /dev/sde: 14.3 GiB, 15376318464 bytes, 30031872 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start   End Sectors  Size Id Type
/dev/sde3          32  2047    2016 1008K e0 unknown
/dev/sde4  *     2048  6143    4096    2M eb BeOS fs

Neither partition is mountable, the BeOS one is not even mountable as befs

Note that even freshly downloaded, the file has the wrong partitions it seems (so it's not an issue with my USB key):
file netboot.xyz.usb
netboot.xyz.usb: DOS/MBR boot sector; 
partition 3 : ID=0xe0, start-CHS (0x0,1,1), end-CHS (0x0,63,32), startsector 32, 2016 sectors; 
partition 4 : ID=0xeb, active, start-CHS (0x1,0,1), end-CHS (0x2,63,32), startsector 2048, 4096 sectors

**Comment by abitrolly** [comment]
Your image is too big. Perhaps you've did something to it. Here is the latest dump.
```
$  md5sum netboot.xyz.usb 
10f28984666d1e836f7b650615088708  netboot.xyz.usb`
$ fdisk -l netboot.xyz.usb 
Disk netboot.xyz.usb: 1.4 MiB, 1409024 bytes, 2752 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device           Boot Start   End Sectors  Size Id Type
netboot.xyz.usb3         32  2047    2016 1008K e0 unknown
netboot.xyz.usb4 *     2048  6143    4096    2M eb BeOS fs
```

**Comment by rzr** [comment]
Image is no more published in "usb" form


https://boot.netboot.xyz/ipxe/netboot.xyz.usb

it was convenient to use also new partitions
