### ISSUE TITLE
Neither of the 2 EFI images seem to provide a config file option to set a custom menu

### ISSUE THREAD

**Issue by marcmerlin** [netbootxyz/netboot.xyz#253]
https://boot.netboot.xyz/ipxe/netboot.xyz-efi.iso
and
https://boot.netboot.xyz/ipxe/netboot.xyz.efi
only provide bootx64.efi
they do not come with a config file to change where the menu is downloaded from.
Online documentation I looked at does not seem to show how to put a config file at the same level that hopefully gets loaded by default (I don't know what the magic name is, if any is supported)

**Comment by Zoddo** [comment]
Same issue here.

I'm interested in downloading the menu from an alternative URL, but there is not any configuration file to change in the ISO.

**Comment by marcmerlin** [comment]
apparently you need to burn in the config file in the binary, so you have to check out the source and build your own with a new static config burnt in. This is a bit disappointing.

**Comment by thelamer** [comment]
This is coming in Version 2.x, on top of having detection for a local tftp server to host boot files out of: 
https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/disks/netboot.xyz.j2#L52-L55

We will also have a web interface with baked in webserver/tftp endpoint that allows you to modify the files. 
https://github.com/netbootxyz/webapp

I will update this issue upon release.

**Comment by thelamer** [comment]
The self hosted Docker container is now live with all the tools you need to customize your local menus and localize our github bootable assets. 

https://hub.docker.com/r/linuxserver/netbootxyz

This will be the officially supported method of full local customization. Documentation on all aspects of this and running an netboot.xyz clone from templated files is coming, but in the meantime it is fully functional.
