### ISSUE TITLE
Self-hosting Instructions

### ISSUE THREAD

**Issue by asmartin** [netbootxyz/netboot.xyz#26]
Would it be possible to provide instructions for how to create your own self-hosted version of http://boot.netboot.xyz (where ipxe chainloads to) for situations where you cannot access the Internet website (e.g slow connection, firewall, etc)?

**Comment by antonym** [comment]
Really it's just a matter of grabbing the src directory, dropping it on a webserver, editing boot.cfg and it's done.  I'll try and add something to the docs sooner or later.

**Comment by asmartin** [comment]
That would be fantastic! Thanks!

**Comment by antonym** [comment]
Just one thing to note, if you can't access the internet, you probably aren't going to have much success installing anything since it's all on the internet. :)

**Comment by asmartin** [comment]
True, but for my use case I am just interested in self-hosting for security rather than pointing pxe at the cloud

**Comment by chris18890** [comment]
@antonym in addition to modifying boot.config, do you have to recompile ipxe to point at your own url?

**Comment by DavidVentura** [comment]
"Big images" such as gparted take a very long time to load for me, debian8-text takes ~1 min. Debian graphics takes <3 min (I came back 3 min later and it was loaded). Gparted takes >10min. Is this because of latency? I have a 50mbps downlink. I could mirror the ISOs locally if the problem is the bandwidth/latency.

**Comment by antonym** [comment]
I think it's probably more related to Sourceforge's mirrors where GParted hosts its builds. Their mirrors are typically overloaded and sluggish.

**Comment by DavidVentura** [comment]
How do I build the ISO? I want to point to my servers to test timings locally.

Oops. I wasn't able to build it because you can't compile iPXE on arch atm. Worked fine on Debian

**Comment by asmartin** [comment]
Any updates on this? I would really like to test out netboot.xyz, but don't want to rely on pulling down installers from online due to the possibility of mirrors being compromised (like what happened with Linux Mint)

**Comment by asmartin** [comment]
Any updates on this?

**Comment by MayhemBill** [comment]
Has this been updated at all? or still dead?

**Comment by asmartin** [comment]
I am still interested in this as well

**Comment by TechnologyClassroom** [comment]
@asmartin, @TheHeroBilly, and @DavidVentura, this can be accomplished on a LAN by serving up the images that the .ipxe files point to on a local server via http, ftp, or your file server favorite method.  The netboot menu could be modified to point to your server instead of the original source.  After that is setup, the repos would still be coming from the original source.  You could mirror repos locally and modify the images to point to your local repos.  A script to set all of that up would be nice.

**Comment by MitchRatquest** [comment]
Maybe I'm late to the party, but I've successfully done this with using buildroot on a tiny ARM computer. You can find the repo here: https://github.com/MitchRatquest/tinyNetboot

It uses Dnsmasq and python to host the files. Its a matter of tweaking the mirror locations to point to the local machine. While slow (100mbs), its powered by a USB port, and boots/serves files quicker than the target machine gets into netboot, so it works for me.

**Comment by webairnetboot** [comment]
## Self Hosted netboot.xyz - Use at your own risk!
I'm setting up an in-house netboot server, cloning the git repo to a Cent OS 6.9 server. 
Hopefully someone can use this to get their own self hosted solution working.

First let's get some basic dependencies installed:
`yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel expat-devel virtualenv gcc pyliblzma genisoimage cdw xorriso`

Next install the web server of your choice and PHP7, you may not need all of the modules I've chosen to install:
`yum install php70w.x86_64 php70w-cli.x86_64 php70w-common.x86_64 php70w-mcrypt.x86_64 php70w-bcmath.x86_64 php70w-fpm.x86_64 php70w-gd.x86_64 php70w-intl.x86_64 php70w-mbstring.x86_64 php70w-ldap.x86_64 php70w-opcache.x86_64 php70w-mysql.x86_64 php70w-pear.noarch php70w-soap.x86_64 php70w-tidy.x86_64 php70w-xml.x86_64 php70w-xmlrpc.x86_64 php70w-phpdbg.x86_64 php70w-process.x86_64 php70w-pspell.x86_64 php70w-recode.x86_64 php70w-snmp.x86_64`

Next upgrade python to latest version without breaking yum, I used the steps outlined by Daniel Eriksson with success:
[https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos/
](https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos/) 

I skipped the python 2.7 and went with only 3.6.3:
`wget http://python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz`
`tar xf Python-3.6.3.tar.xz`
`cd Python-3.6.3`
`./configure --prefix=/usr/local --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"`
`make && make altinstall`

I also opted to strip symbols from the shared library to reduce the memory footprint out of sheer geekdom:
`strip /usr/local/lib/libpython3.6m.so.1.0`

Next, install [MkDocs](https://github.com/Collizo4sky/sitepoint_mkdocs) and its pip dependencies:
`pip install mkdocs`

Then I git cloned the [netboot.xyz](url) source to /usr/local/src:
`git clone https://github.com/antonym/netboot.xyz.git`

Run the prep-release.sh script which compiles ipxe accordingly and prepares the documentation for publishing:
`cd netboot.xyz`
`script/prep-release.sh`

Now you're ready to create the site for the web server:
`mkdocs build`

Once the build completes you should have a directory named "site" which can be copied to the DocumentRoot of your custom URL.

You may need to tweak the above accordingly for your specific environment. As stated, use at your own risk! :)

**Comment by antonym** [comment]
Haven't forgotten about this... my main goal is to get some Ansible playbooks that you should just be able to run and have it set up everything for a local copy with your own settings.  Just been trying to find some time to hack on them and get them working with basic functionality.

**Comment by dragon788** [comment]
I wonder if Docker or Ansible would be the less painful route.

**Comment by asmartin** [comment]
I would advocate for ansible

**Comment by akiross** [comment]
Would be nice to have this on docker with something like this: https://jpetazzo.github.io/2013/12/07/pxe-netboot-docker/

One could run the image and configure the bridge to use a specific eth card to have it up and running.

**Comment by antonym** [comment]
For an update on this, I'm looking at switching over to Ansible for self-hosting and we should be swapping out the existing code in the repo for the Ansible templates in the coming weeks:

https://netboot.xyz/blog/2019-11-29-self-hosting-and-live-booting/

**Comment by asmartin** [comment]
That sounds great, thanks!

**Comment by antonym** [comment]
The development branch now contains the work being done with Ansible.  It's still in dev but it's in a place that can be tested if anyone wants to hack around with it:

https://github.com/netbootxyz/netboot.xyz/tree/development#self-hosting-netbootxyz

**Comment by antonym** [comment]
Docs are now up here: https://netboot.xyz/selfhosting/ and the Ansible code has made its way into netboot.xyz master.
