### ISSUE TITLE
EFI image doesn't work over libvirt + kvm/qemu

### ISSUE THREAD

**Issue by renich** [netbootxyz/netboot.xyz#268]
I'm using Fedora 28 as a host. I tried using UEFI (TianoCore) and it doens't work with your image; it drops to a shell (efilinux).

On the other hand, I try the Fedora 29 Beta ISO image and it works fine. 

Might there be something missing in the EFI iso image?

**Comment by patrakov** [comment]
The EFI iso image is just wrong. It does not contain any El Torito records. Instead, it contains BOOT/EFI/BOOTX64.EFI file, which UEFI does not even look at on optical media.

For now, you can create your own EFI iso by running these commands (assuming that you have dosfstools, cdrecord and mtools installed):

```
wget https://boot.netboot.xyz/ipxe/netboot.xyz.efi
mkdir cdrom
dd if=/dev/null of=cdrom/image.flp seek=2880
mkfs.vfat -M 0xf8  -f 1 cdrom/image.flp
mmd -i cdrom/image.flp ::efi ::efi/boot
mcopy -i cdrom/image.flp netboot.xyz.efi ::efi/boot/bootx64.efi
mkisofs -o ipxe-uefi.iso  -eltorito-platform 0xef -eltorito-boot image.flp -no-emul-boot cdrom
```

I will create a pull request later.

**Comment by antonym** [comment]
Closing this as @patrakov was kind enough to fix.  Please reopen if it's still an issue.
