### ISSUE TITLE
BOOT FAILURE when exiting FreeDOS menu

### ISSUE THREAD

**Issue by dev-zero** [netbootxyz/netboot.xyz#28]
When leaving the FreeDOS boot menu via ESC to return to the main menu, I get the following instead:

```
Could not boot: No such file or directory (http://ipxe.org/2d02803b)
Could not boot: No such file or directory (http://ipxe.org/2d02803b)
Could not boot: No such file or directory (http://ipxe.org/2d02803b)
FATAL: INT18: BOOT FAILURE
```

![freedos-back](https://cloud.githubusercontent.com/assets/11307/12291142/cead9008-b9e5-11e5-96d6-76fe35a5873f.png)

**Comment by antonym** [comment]
Thanks for finding that, fixed in https://github.com/antonym/netboot.xyz/commit/80c42b80eba2132b0be731af2ab0724dc0c6962c
