### ISSUE TITLE
Debian URL Check

### ISSUE THREAD

**Issue by andrewdunndev** [netbootxyz/netboot.xyz#286]
It looks like Debian might have moved some of their resources, there are a lot of targets not at the archive location (http://archive.debian.org/debian/dists/), for example buster/stretch/sid, that are available at the deb.debian.org CDN (http://cdn-fastly.deb.debian.org/debian/dists/).

The installers don't seem to load right now, so I'm unable to use netboot.xyz to do installs on packet.

In  #160 @antonym says "for now to use 8.9.0..." but I'm unsure of how to do that.

**Comment by antonym** [comment]
Hi, please give it another try... it looked like the stretch signature I had was failing which usually means that upstream swapped out one of the installer files for a new version.  #160 is only related to the Debian Live image which still appears to be working.

I'm using http://deb.debian.org/ as the mirror right now and it appears to be working.
