### ISSUE TITLE
Liveboot options

### ISSUE THREAD

**Issue by chris18890** [netbootxyz/netboot.xyz#29]
Would it be viable to have live boot options for ubuntu & some of the other distros?

**Comment by antonym** [comment]
Yeah, definitely something I'm thinking about.  I'd like to have a place for live booted distros like Tails, Ubuntu and others that are designed to run live in memory.

**Comment by chris18890** [comment]
have been playing around with this without much success, but I did get iPXE to boot my local PXE setup where the live distros work, & vice versa :)

**Comment by antonym** [comment]
Got this kicked off with Debian, didn't realize they publish a useable live boot release so added it.  Maybe we can get other providers to do the same.

https://github.com/antonym/netboot.xyz/pull/130
