### ISSUE TITLE
Windows XP bootmgr

### ISSUE THREAD

**Issue by GIOhnny** [netbootxyz/netboot.xyz#294]
Hello,

I'm trying to install a WinXP x86 using netboot.xyz.
I've dearchivated the ISO and there are no files named bootmgr, boot/bcd, boot/sdi, sources/boot.wim

How can I do it ?

**Comment by antonym** [comment]
XP used another installer method so those files would not be included on the XP media.  This currently supports the method used in Vista and on.

**Comment by chris18890** [comment]
Out of interest, would it be possible to boot the ISO with memdisk & kick things off that way?
