### ISSUE TITLE
Cannot reach boot.netboot.xyz eventhough dhcp response is correct

### ISSUE THREAD

**Issue by carroarmato0** [netbootxyz/netboot.xyz#301]
I'm having an issue where netboot is unable to contact http(s)://boot.netboot.xyz/menu.ipxe after configuring the network automatically.

When performing a tcpdump from my router, I can see that netboot is requesting the following:

```
00:48:30.421771 IP (tos 0x0, ttl 64, id 256, offset 0, flags [none], proto UDP (17), length 437)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 50:7b:9d:4d:70:2a, length 409, xid 0x94768433, secs 4, Flags [none] (0x0000)
          Client-Ethernet-Address 50:7b:9d:4d:70:2a
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            MSZ Option 57, length 2: 1472
            ARCH Option 93, length 2: 0
            NDI Option 94, length 3: 1.2.1
            Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
            User-Class Option 77, length 4:
              instance#1: ERROR: invalid option
            Parameter-Request Option 55, length 23:
              Subnet-Mask, Default-Gateway, Domain-Name-Server, LOG
              Hostname, Domain-Name, RP, MTU
              Vendor-Option, Vendor-Class, TFTP, BF
              Option 119, Option 128, Option 129, Option 130
              Option 131, Option 132, Option 133, Option 134
              Option 135, Option 175, Option 203
            T175 Option 175, length 57: 177.5.1.128.134.21.162.235.3.1.0.0.23.1.1.34.1.1.19.1.1.20.1.1.17.1.1.39.1.1.25.1.1.16.1.2.33.1.1.21.1.1.24.1.1.35.1.1.27.1.1.38.1.1.18.1.1
            Client-ID Option 61, length 7: ether 50:7b:9d:4d:70:2a
            GUID Option 97, length 17: 0.1.72.23.95.173.83.203.17.152.215.140.63.118.179.226.189
            END Option 255, length 0
```

After which my DHCP server gladly provides an answer and netboot accepts:

```
00:48:33.497192 IP (tos 0xc0, ttl 64, id 1425, offset 0, flags [none], proto UDP (17), length 353)
    192.168.20.1.67 > 192.168.20.107.68: [bad udp cksum 0xab1b -> 0x9bba!] BOOTP/DHCP, Reply, length 325, xid 0x94768433, secs 18, Flags [none] (0x0000)
          Your-IP 192.168.20.107
          Server-IP 192.168.20.1
          Client-Ethernet-Address 50:7b:9d:4d:70:2a
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: ACK
            Server-ID Option 54, length 4: 192.168.20.1
            Lease-Time Option 51, length 4: 43200
            BF Option 67, length 11: "pxelinux.0^@"
            RN Option 58, length 4: 21600
            RB Option 59, length 4: 37800
            Subnet-Mask Option 1, length 4: 255.255.255.0
            BR Option 28, length 4: 192.168.20.255
            Default-Gateway Option 3, length 4: 192.168.20.1
            Domain-Name Option 15, length 3: "lan"
            TFTP Option 66, length 13: "192.168.20.1^@"
            Domain-Name-Server Option 6, length 4: 192.168.20.2
            END Option 255, length 0
```

In this context:

- Default-Gateway 192.168.20.1  --> My gateway/Router
- Domain-Name-Server 192.168.20.2 --> My DNS server ( Pihole in this case )

Curiously enough, If I configure everything manually in Netboot, it works.

I press "m"
Go to Manual network configuration
I accept the default network interface
I provide it the same IP address my DHCP server would give it: 192.168.20.107
Subnet 255.255.255.0 (/24)
Gateway: 192.168.20.1
DNS: 192.168.20.2

Afterwhich netboot succesfully manages to reach the server from which it fetches the menu.

**Comment by carroarmato0** [comment]
I also noticed that https actually fails even with the manual configuration (Connection timeout), http fallback works.

**Comment by Firminator** [comment]
Same issue as https://github.com/antonym/netboot.xyz/issues/283 it appears.

**Comment by NiKiZe** [comment]
I would suggest to show the full error message you get in iPXE, including the ipxe.org url that is shown. otherwise we can only guess if is the same or not.

**Comment by carroarmato0** [comment]
Sorry for the delay.  I appear to be getting a timeout:   http://ipxe.org/err/4c0a6092
The url: https://boot.netboot.xyz/menu.ipxe

**Comment by carroarmato0** [comment]
tcpdump with netboot not working:  https://pastebin.com/UaB2bwK6
tcpdump working with manual network configuration:  https://pastebin.com/Rv8eJpdN

**Comment by carroarmato0** [comment]
What I also noticed while doing the manual network configuration is that  HTTPS fails (timeout) while what appears to be it fetching the OCSP Starfield Services Root Ce before failing over to HTTP and succeeding

**Comment by antonym** [comment]
Closing out as this appears to be environmental.
