### ISSUE TITLE
Wrong URL for mfsbsd

### ISSUE THREAD

**Issue by dszidi** [netbootxyz/netboot.xyz#302]
When I try to load any of the BSD installs it fails. After checking through the scripts I found in the file `/src/freebsd.ipxe` on line 32 the url for the image is being set. It is missing architecture level in the path. 

Currently the url it is trying to load is 

``` 
http://mfsbsd.vx.sk/files/images/${image_subdir}/mfsbsd-${image_ver}-${freebsd_arch}.img
```

It should be ...

```
http://mfsbsd.vx.sk/files/images/${image_subdir}/${freebsd_arch}/mfsbsd-${image_ver}-${freebsd_arch}.img 

```

BTW I would have done this myself and created a patch but there is a lack of build instructions currently. Also I've not had any luck using the feature that should allow me to test my own fork.

**Comment by sarcasticadmin** [comment]
Ran into this as well

Additionally I noticed that `mfsbsd.vx.sk` is redirecting `http` to `https`. So I tried to building my own custom netboot.xyz and I could not get the freebsd installer to boot

**Comment by antonym** [comment]
Yeah thanks for making an issue for this, I have a PR up for correcting the URL: https://github.com/antonym/netboot.xyz/commit/e82d679dfb7ffb94ed23b2332407814cfad6a57f

But there may be an upstream bug with iPXE https talking to Let's Encrypt certs that's causing iPXE to trigger a Permission Denied (0227e13e) when trying to talk to the https server.  I'm currently tracking a PR that's being actively worked to fix this:

https://github.com/ipxe/ipxe/pull/90

**Comment by fzipi** [comment]
Well, I made PR #309 with the url change. Also addedd FreeBSD 12. Would have commented earlier, but the title of this issue was not calling me to read it.

**Comment by fzipi** [comment]
Having label `freebsd` would be nice.

**Comment by fzipi** [comment]
Seems like https://github.com/ipxe/ipxe/pull/90 was fixed.

**Comment by patrakov** [comment]
The wrong URL is a moot point, because the SSL setup for mfsbsd.vx.sk is incompatible with iPXE due to the mismatch of supported ciphersuites. I have already notified the maintainer:

https://github.com/mmatuska/mfsbsd/issues/101

Due to their lack of response, I guess there is no other choice than removing FreeBSD from the list of systems offered by netboot.xyz.

**Comment by antonym** [comment]
Yeah, since they added https, it's been busted, thanks for opening up a ticket upstream, it might just be a good idea to reference that ticket in the BSD menu and then anyone interested in it can go poke that issue.

**Comment by thelamer** [comment]
We can just publish their assets as github releases I will be closing this tracking in https://github.com/netbootxyz/netboot.xyz/issues/31
