### ISSUE TITLE
Checksum images

### ISSUE THREAD

**Issue by avindra** [netbootxyz/netboot.xyz#31]
Would it be possible to do a checksum (preferably SHA256) of all the images after they are downloaded?

**Comment by antonym** [comment]
There's a provision in iPXE for signing images and then verifying their signatures:

http://ipxe.org/cmd/imgverify
http://ipxe.org/crypto

At some point I'll look into the feasibility of doing so, at the very least on some of the lesser known mirrors/images.

**Comment by dbohdan** [comment]
@antonym This would be excellent.

If you do implement signature checking consider doing it for all images and mirrors. The most-downloaded images may be hosted on servers that are better maintained but they also represent the most desirable target for attackers.

**Comment by avindra** [comment]
> The most-downloaded images ... represent the most desirable target for attackers.

Agree. We should be cognizant of this when making modern infrastructure tooling.

**Comment by antonym** [comment]
The groundwork is now laid out for checking all images being downloaded.  I'm currently generating signatures of the netboot.xyz sources during deployment and then verifying as each menu item is loaded.  The next step will be to verify the signatures of the remotely downloaded images which I'll probably have time for in the next week or two.

**Comment by mirabilos** [comment]
Is there any way to delegate sigining for particular images to the project responsible for them? The `imgverify` command has a `--signer` option; this would allow you to use your own main signature key for netboot.xyz itself and those images signed by you, and allow me to re-sign the MirBSD images every time I upload an updated snapshot (it’s a -current image, i.e. updated occasionally, as we’re not doing formal releases at the moment).

**Comment by antonym** [comment]
Right now I'm retrieving the binaries remotely at a point in time and signing them.  It's super rough and I haven't had a ton of time to work on it recently.  I still need to have it only resign when needed instead of every time I run the job.  The rolling releases make it more difficult because then they can potentially break and there's not really a good way to alert me about that yet other than setting up a periodic check.

My signature retrieval scripts and generators are here:

https://github.com/antonym/netboot.xyz-sigs/blob/master/generate-bsd-sigs.sh

**Comment by mirabilos** [comment]
Antony Messerli dixit:

> Right now I'm retrieving the binaries remotely at a point in time and
> signing them.

Hmm. In this case, please do _not_ do that for MirBSD, as it’ll
break when we publish newly generated images, which are done
“occasionally”.

> It's super rough and I haven't had a ton of time to work on it
> recently. I still need to have it only resign when needed instead of
> every time I run the job. The rolling releases make it more difficult

Sure, I understand it’s all on spare time, same here ☺

bye,
//mirabilos

**Comment by antonym** [comment]
Cleaning up, this was implemented a while ago for quite a few of the OS distros and additional checks will be added as needed.
