### ISSUE TITLE
Error "Loading libc6-udeb failed for unknown reasons" on Ubuntu Xenial PXE installer 

### ISSUE THREAD

**Issue by ravens** [netbootxyz/netboot.xyz#311]
I have been hitting this bug today using xenial flavor of ubuntu over PXE. The bug is mentioned in this mailing list message (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833706#45), basically it is probably better to call the netboot image from the *-updates directory for the ubuntu family in src/ubuntu.ipxe. Example : http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/ - > http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/

**Comment by antonym** [comment]
Yeah, I was running into this elsewhere this week.  I've bumped them to using the updates kernels, altho that may break signature checking more often since they rotate out those kernels and don't have that directory structure versioned.

**Comment by ravens** [comment]
So what would be the workaround when hitting this bug while using netboot.xyz ? 16.04 has been broken for more than one day now.

**Comment by ravens** [comment]
Nevermind, works great now. I missed the commit https://github.com/antonym/netboot.xyz/commit/c92ff0a934e79f464bd5492b08add9e19cb227c4

**Comment by antonym** [comment]
Ah, sorry, meant to link the commit!  Thanks for raising the issue!
