### ISSUE TITLE
Fedora Atomic URL broken

### ISSUE THREAD

**Issue by mulbc** [netbootxyz/netboot.xyz#320]
# Problem statement
It seems like the current URL for atomic is broken:
![Auswahl_146](https://user-images.githubusercontent.com/131446/56131053-c19c1980-5f86-11e9-8870-4b4af9fd84fd.jpg)

# Solution proposal
Directly - this would mean we need to update:
https://github.com/antonym/netboot.xyz/blob/25f936aee5c800f15b3ca10f057444026cc39767/src/fedora.ipxe#L29

The latest URL is:
`http://mirrors.kernel.org/fedora-alt/atomic/stable/Fedora-29-updates-20190401.0/AtomicHost/x86_64/os/images/pxeboot/`

## Additional enhancements
Also we should update the fedora mirror:
https://github.com/antonym/netboot.xyz/blob/924f7d746459ee879b08ec0c73027ec59e967e16/src/boot.cfg#L50
Using `https://download.fedoraproject.org/pub/alt/` is the same as `http://mirrors.kernel.org/fedora-alt/` - but it will randomly chose a close-by mirror.

**Comment by bam80** [comment]
Is this still working? Don't see neither Atomic nor Silverblue Fedora in the menu..
