### ISSUE TITLE
Pogostick broken

### ISSUE THREAD

**Issue by aetha** [netbootxyz/netboot.xyz#323]
Hi, attempting to boot Pogostick consistently gives a 'Connection reset' error for me. I can't figure out the cause, other images run fine, and the Pogostick uri works fine in a browser. Any help?

**Comment by chris18890** [comment]
Tah for raiseing this @aetha, I'll try to get a look at it this week :)

**Comment by antonym** [comment]
Was not able to reproduce, uri seems to load without issues using Virtual Box.
