### ISSUE TITLE
ALT Linux Rescue broken

### ISSUE THREAD

**Issue by aetha** [netbootxyz/netboot.xyz#324]
Hi again, this one looks easy to fix. The uri used seems dead, according to the website the correct uri would be: http://nightly.altlinux.org/sisyphus/tested/regular-rescue-latest-x86_64.iso

**Comment by danboid** [comment]
I have opened a PR to fix this:

https://github.com/antonym/netboot.xyz/pull/378

**Comment by danboid** [comment]
Until netboot gets updated with my PR, you can try my netboot-custom fork out by using the github user danboid.

Note however I was wanting to use netboot to boot ALT on an old netbook with only 1 GB RAM but it seems 1 GB RAM isn't sufficient to netboot ALT. If you have 2+ GB RAM then maybe my custom menu will work for you?

The other option for booting into a live Linux environment for 32 bit users that does work under the current netboot release is Slackware although it lacks many of the tools included in ALT in its default installation.

**Comment by thelamer** [comment]
Please read the notes here: 
https://github.com/netbootxyz/netboot.xyz/pull/378
The next release (2.x series) pending final polishing will be ripping out some of these distro options.

**Comment by N0rbert** [comment]
The URL http://nightly.altlinux.org/sisyphus/tested/regular-rescue-latest-x86_64.iso is alive, please add ALT Linux Rescue to netboot.xyz.
