### ISSUE TITLE
Unable to boot ubuntu-18.04.2-live-server-amd64.iso over HTTP

### ISSUE THREAD

**Issue by mrme02** [netbootxyz/netboot.xyz#333]
Using the instructions, fit to my environment,

kernel https://boot.netboot.xyz/memdisk iso raw
initrd http://10.0.0.27/erx/18.04server.iso
boot

I get, after waiting a while, once the kernel has seemingly booted,
(initramfs) Unable to find a medium containing a live filesystem.

I think I am missing something, any idea what that might be? Sorry for posting here, I had no other way of asking this question, Google doesn't yield what I am looking for.

**Comment by orange888** [comment]
> Using the instructions, fit to my environment,
> 
> kernel https://boot.netboot.xyz/memdisk iso raw
> initrd http://10.0.0.27/erx/18.04server.iso
> boot
> 
> I get, after waiting a while, once the kernel has seemingly booted,
> (initramfs) Unable to find a medium containing a live filesystem.
> 
> I think I am missing something, any idea what that might be? Sorry for posting here, I had no other way of asking this question, Google doesn't yield what I am looking for.

Did you find a solution?

**Comment by antonym** [comment]
The problem with memdisk is that:

- It has limitations as to the size of an ISO it can load into memory.
- Only works on Legacy and not EFI
- Does not always know how to mount the filesystem from the memdisk device where the ISO is loaded, some ISOs work, some don't and in general it's slow and doesn't work well.

We're working on going a different route where we'll have a lot of live options available on the netboot.xyz menu as we're working on ISO extraction, hosting of the filesystems, and then loading the kernels and squashfs directly from a repo. 

I might get a few options linked into the existing menu today for testing but our goal is to have quite a large library.

**Comment by orange888** [comment]
> The problem with memdisk is that:
> 
>     * It has limitations as to the size of an ISO it can load into memory.
> 
>     * Only works on Legacy and not EFI
> 
>     * Does not always know how to mount the filesystem from the memdisk device where the ISO is loaded, some ISOs work, some don't and in general it's slow and doesn't work well.
> 
> 
> We're working on going a different route where we'll have a lot of live options available on the netboot.xyz menu as we're working on ISO extraction, hosting of the filesystems, and then loading the kernels and squashfs directly from a repo.
> 
> I might get a few options linked into the existing menu today for testing but our goal is to have quite a large library.

preseed file is new to me. I am learning how to use it. How do I speed up its testing process?

Do you have a good ubuntu preseed template that I could look at?
Thanks.

**Comment by samip5** [comment]
@orange888 What are you currently trying to do?

You should not use memdisk, as it will have trouble booting with that.

There is server boot menu option already in the menu, you can see it here: https://github.com/antonym/netboot.xyz/blob/master/src/ubuntu.ipxe

In the actual menu, it's under "Linux Installs" -> Ubuntu

**Comment by thelamer** [comment]
as @samip5 stated you should use the network installer and select the packages you want to install. 
If you need a live CD our version 2 Currently has them at development head: (though no server one as it serves very little purpose as a live CD )
https://s3.amazonaws.com/dev.boot.netboot.xyz/999a90aa2875f9cfb51c76a7db6d94299e933322/index.html
