### ISSUE TITLE
Name resolution issue

### ISSUE THREAD

**Issue by aqwserf** [netbootxyz/netboot.xyz#338]
Hi,
after struggling with my OpenWRT to have pxe running, I now have a issue with the netboot.xyz UEFI. Everytime I try to boot with the UEFI version (netboot.xyz.efi), it fails with the following error when it tries to retrieve the squashfs file:

```bash
(initramfs) IP-Config
......
......
Creating /etc/resolv.conf
Begin: Trying wget http://cdimage.debian.org/cdimage/archive/8.11.0-live/amd64/webboot/debian-live-8.11.0-amd64-lxde-desktop.squashfs -O /live/medium/live/debian-live-8.11.0-amd64-lxde-desktop.squashfs ... wget: bad address 'cdimage.debian.org'
Unable to find a live file system on the network
(initramfs) 
```
I've tried to debug the situation by wgetting myself and the same error appears.
The problem apparently lies in the name resolution:
```
(initramfs) nslookup cdimage.debian.org
Server:       192.168.1.1
Address:    192.168.1.1

nslookup: can't resolv 'cdimage.debian.org'
(initramfs) cat /etc/resolv.conf
domain local.lan
search local.lan
nameserver 192.168.1.1
```
The `/etc/resolv.conf` file is ok and when I try the same command on my laptop, eveything works fine.
I've tried with the `netboot.xyz.kpxe` and it works fine and I've just tried with another boot install this time (Kali) and the installer starts.
Does anyone has a clue ? Is it related to the debian initrd ?

Otherwise, I have several problems with other boot image (systemrescuecd, ubcd...), same as the issue #214 :
```
..... Exec format error
```
Could it be related ?

Thank you !

**Comment by NiKiZe** [comment]
many initrds with busybox does not support name resolution,
I guess you have tried wget in a fully booted linux env, but if you enter the limited initrd environment my guess is that you will see the same thing, you can confirm with ping or some other tool if name resolution works at all or not in that case.

"Exec format error (http://ipxe.org/2e008081)"
If you get it when booting in efi mode, is most likely due to the fact that you are trying to boot a non efi compliant binary (in the case of linux kernel, it wasn't compiled with CONFIG_EFI_STUB=y)
Which you can read more about on the ipxe,org error page (the url is helpful, and always good to include)

**Comment by aqwserf** [comment]
> many initrds with busybox does not support name resolution,
> I guess you have tried wget in a fully booted linux env, but if you enter the limited initrd environment my guess is that you will see the same thing, you can confirm with ping or some other tool if name resolution works at all or not in that case.


That's right, I tried on an full Linux env. I've also tried with a ping and that's right too, it doesn't works...
But what I don't understand is that it works with kali boot install and not with a debian live. Does that means that the initrd is different ?

> "Exec format error (http://ipxe.org/2e008081)"
> If you get it when booting in efi mode, is most likely due to the fact that you are trying to boot a non efi compliant binary (in the case of linux kernel, it wasn't compiled with CONFIG_EFI_STUB=y)
> Which you can read more about on the ipxe,org error page (the url is helpful, and always good to include)

Ok, thank you for the explanation. So if I understand well, netboot.xyz propose an efi binary that can't load non-efi binary ? If so, can't they propose efi binary ?

**Comment by NiKiZe** [comment]
different distros of course have their own intrds, but it boils down to "buggy" busybox. you should ask for an update on the specific distro (they seem unlikely to fix it tho, as far as i have seen)

the simple answer is that there is no efi binary that can boot a non efi binary or wise versa.
The way that these tools are setup relies on legacy technices that shouldn't be used, but it takes loots more work to solve "correctly" and it requires EFI compatible kernels.

**Comment by aqwserf** [comment]
Ok, thank you for your answers. I close the issue as it doesn't seem to be solvable easily :)
