### ISSUE TITLE
CentOS 7 fails to install if a static IP is required

### ISSUE THREAD

**Issue by patrakov** [netbootxyz/netboot.xyz#342]
In the CentOS 7 ipxe file, "ip=dhcp" is hard-coded as a kernel option. This is a limitation, because, using a failsafe menu (m), you can in fact set a static IP address. Therefore, ideally, the ip=... parameter for the installer kernel should be generated on the fly from the information that the user entered when statically configured the network.

**Comment by xmovu** [comment]
Facing the same issue, had reported this before @patrakov .

No dice, it just won't work, did you find any solution? Perhaps @antonym can have a second look.

**Comment by xmovu** [comment]
Fixed with #343 commits.
