### ISSUE TITLE
Ubuntu: Could not verify: permission denied

### ISSUE THREAD

**Issue by theo-o** [netbootxyz/netboot.xyz#347]
(http://ipxe.org/0227e13c)

![output](https://user-images.githubusercontent.com/32401143/62321433-a0e1cc00-b470-11e9-9162-6452351978b2.png)
Hi,
It appears that the signature for Ubuntu's bionic image is off.

Related to https://github.com/antonym/netboot.xyz/issues/312

**Comment by antonym** [comment]
I regenerated the signatures so give it a try again.

**Comment by DaMatrix** [comment]
this seems to be happening again, i'm getting a similar error message to the above when trying to select Ubuntu.
