### ISSUE TITLE
Please add some distro's

### ISSUE THREAD

**Issue by jelee1988** [netbootxyz/netboot.xyz#348]
if possible :)

https://www.backbox.org/
https://antixlinux.com/
https://www.anarchylinux.org/

**Comment by thelamer** [comment]
Backbox Live cd is in our v2 and will be released alongside it: 
https://s3.amazonaws.com/dev.boot.netboot.xyz/999a90aa2875f9cfb51c76a7db6d94299e933322/index.html

antilinux/MX Linux maintain and extremely custom boot process without any support for http/pxe endpoints : 
https://github.com/BitJam/Live-initrd/blob/antiX-19/init

Also BitJam has multiple messages in their forums stating they do not support it.(pxe booting) 
If we ever do MX linux AntiX would come with it, but we would need to maintain the patches and it will always be on our minds as it is a popular distro. 

Anarchy linux is arch based so it has this hook https://github.com/rcrowley/archiso/blob/master/archiso/initcpio/hooks/archiso_pxe_http
But we would need to ingest their ISO tear it apart and maintain a custom patch for it to support https from our Github Env. As it stands right now this distro should become a bit more mature and established before we consider that workload.
