### ISSUE TITLE
Investigate possibilites of collaboration with libosinfo

### ISSUE THREAD

**Issue by patrakov** [netbootxyz/netboot.xyz#351]
Libosinfo is a project that, among other things, has to maintain locations and kernel command lines for network-based Linux distribution installations. It would be nice to check if there is something that they can install and we don't, and the other way round.

One known missing feature for netboot.xyz, supported by libosinfo, is the command line for unattended installation.

cc: @fidencio

**Comment by thelamer** [comment]
Can you give an example of how you generate network bootable kernel comand lines entries. All the docs I found are programmatic interface options for `get_network_install_resources` api class. 

The main focus of this project seems to be generating preseed and install scripts though, from a project perspective an IPXE bootloader will never support this in an automated fashion. Though we do allow users to customize their own IPXE boot entries to hook in whatever they want. 
What  do you propose would change from a codebase perspective ?

**Comment by fidencio** [comment]
@thelamer,

Firstly, I'm actually not sure whether using libosinfo would be a good fit or not for netboot.xyz and I am really glad you took some time to investigate that.

libosinfo provides:
- installation scripts with desktop / jeos profiles;
- resources information;
- supported hardware information;

Knowing that, I do believe that libosinfo may be useful in case netboot.xyz wants to start VMs and perform unattended installation on those via IPXE (in case it's feasible).

You asked for an example of how you can generate a network bootable kernel command line entry, here you can find what's done on virt-install (which is already using libosinfo): https://github.com/virt-manager/virt-manager/blob/master/virtinst/install/unattended.py#L228

I know, it may not be that easy to follow virt-install's code. If you have interest, I can cook a simple example for you in the next few days (-ETOOLATE right now on my timezone ;-)).

Please, let me know whether it'd be of your interest and we can keep the discussion happening.

Best Regards and, again, thanks for investigating this.

**Comment by patrakov** [comment]
The ground truth about kernel command lines is in this folder: https://gitlab.com/libosinfo/osinfo-db/tree/master/data/install-script. In XSL files, look for `<xsl:template match="/command-line">`.

OTOH I agree that the project goals and use cases are too different, so let's close this ticket.
