### ISSUE TITLE
Wrong with dns record.

### ISSUE THREAD

**Issue by OrvilleQ** [netbootxyz/netboot.xyz#360]
## 1. netboot.xyz can't remember dns record from manual input.

DNS record is empty in netboot.xyz's network card when I need to input DNS record manually.

## 2. DNS record can't send to kernel.

In centos and fedora's line 6

```
isset ${dhcp-server} && set ipparam ip=dhcp || set ipparam ip=${ip}::${gateway}:${netmask}:::none:${dns}
```
You can't put a dns record after `ip=`, see https://anaconda-installer.readthedocs.io/en/latest/boot-options.html#ip

It should be like this:

```
ip=... nameserver=... [nameserver=...]
```

**Comment by antonym** [comment]
^^ should fix the issues
