### ISSUE TITLE
Add option for Manjaro Architect

### ISSUE THREAD

**Issue by samip5** [netbootxyz/netboot.xyz#369]
Please add an option for Manjaro Architect, as it's the smallest ISO of Manjaro.

Download link can be found from https://manjaro.org/get-manjaro/ and going to bottom of the page. Downloaded ISO is around 600 MB's in size, which should work for memdisk.

- [ ] Try to get Manjaro team on board with supporting PXE.
- [ ] Manjaro team needs to keep at least one of the older versions available in the same kind of folder structure as everything else. Otherwise it messes things up.

Related #335

**Comment by samip5** [comment]
Okey, so I have managed to boot Architect without UEFI, but in UEFI (using the supplied .efi file, though network)  it fails so I think that memdisk is the problem?


![IMG_20191018_012007](https://user-images.githubusercontent.com/1703002/67052590-4db21800-f147-11e9-8bc2-70123bd1b3de.jpg)

**Comment by antonym** [comment]
Yeah, memdisk doesn't work unfortunately on UEFI.  I still need to put some detection to toss up an error message if a memdisk image is loaded and the platform is UEFI.  I've been poking around with chaining into grub on EFI and then doing an http loopback to get around that but it's still in progress.  This might be a good image to experiment with that on.

I'll merge the commit in for now which should at least get things working on legacy.

Thanks for digging into that!

**Comment by samip5** [comment]
Actually, I was thinking of etracting the ISO for architect and host the files, to test if that's what is needed for it to work with the current implementation.

Also, I don't know if KDE, XFCE and etc flovers work, so there's a NOT TESTED disclaimer next to them.

**Comment by samip5** [comment]
Related https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/issues/314.
Related https://github.com/manjaro/manjaro-tools/issues/177

**Comment by thelamer** [comment]
All the Manjaro live CDs are in our latest development builds. If you need this now you can use : 
https://s3.amazonaws.com/dev.boot.netboot.xyz/999a90aa2875f9cfb51c76a7db6d94299e933322/index.html

If not it is just a matter of waiting for v2 to be official released.
