### ISSUE TITLE
Cannot boot Alpine with signatures enabled

### ISSUE THREAD

**Issue by patrakov** [netbootxyz/netboot.xyz#373]
Alpine 3.10.3 was released 24 hours ago, and they replaced the kernel and initramfs files in-place. Therefore, the signatures no longer match, and boot fails unless I disable image signature checks.

**Comment by antonym** [comment]
I refreshed the sigs this morning and they seem to load now.  It looks like i'm just using the generic rolling release files for the major release from:

http://dl-cdn.alpinelinux.org/alpine/v3.10/releases/x86_64/netboot/ 

as opposed to minor revs:
http://dl-cdn.alpinelinux.org/alpine/v3.10/releases/x86_64/netboot-3.10.3/

It might be better to pull it from the minor revs but it might just involve more periodic updates and sig updates.  I'll try and think about a better way to do it that involves less maintenance in the future.

Thanks for the report tho!

**Comment by patrakov** [comment]
I confirm that it boots now.
