### ISSUE TITLE
netboot.xyz is not up to date with master

### ISSUE THREAD

**Issue by forkiesassds** [netbootxyz/netboot.xyz#374]

**Comment by antonym** [comment]
Not much info here, but there were some docs in the repo that were not being pushed anymore to the site for a while since I moved from mkdocs to hugo.  I've removed those so now https://github.com/antonym/netboot.xyz-docs is the main place for the netboot.xyz documentation.

**Comment by forkiesassds** [comment]
I ment by the iPXE part.
