### ISSUE TITLE
Improve booting from tftp instructions

### ISSUE THREAD

**Issue by danboid** [netbootxyz/netboot.xyz#379]
The instructions for booting netboot.xyz via tftp ( https://netboot.xyz/booting/tftp/ ) could be improved by including the dnsmasq configuration required to configure the `next-server` address for those who are using dnsmasq as their DHCP server as well as their TFTP server. Doing so is as simple as adding the line:

```
dhcp-option=66,0.0.0.0
```

to `/etc/dnsmasq.conf` where 0.0.0.0 means 'the address of the server running dnsmasq'. It would make sense to include at least this because the same page has instructions for configuring dnsmasq as a TFTP server.

It may also be a good idea to link to some instructions for configuring dnsmasq as a DHCP server, such as https://wiki.archlinux.org/index.php/dnsmasq#DHCP_server

**Comment by danboid** [comment]
I configured dnsmasq under Debian 10 where there is a bug in the configuration of `/lib/systemd/system/dnsmasq.service` which means I had to edit it and change:

```
After=network.target
```

to

```
After=network-online.target
```

In the [Unit] section to get dnsmasq to start at boot correctly. That could well only apply to Debian and Ubuntu users but I thought it worth mentioning here at least.

**Comment by antonym** [comment]
Good info, if you want to make a PR to the docs directly for the change, you can find that doc here:

https://github.com/antonym/netboot.xyz-docs/blob/master/content/booting/tftp/_index.md

Thanks!

**Comment by danboid** [comment]
Done

https://github.com/antonym/netboot.xyz-docs/pull/3

**Comment by antonym** [comment]
Merged
