### ISSUE TITLE
Raspberry Pi iPXE support

### ISSUE THREAD

**Issue by antonym** [netbootxyz/netboot.xyz#381]
Look into how we might be able to leverage iPXE Raspberry Pi support for netboot.xyz:

https://github.com/ipxe/pipxe

Appears to have been tested on 3B and 3B+ so far, UEFI firmware doesn't work with 4 yet.

**Comment by antonym** [comment]
Tested porting netboot.xyz bootloader to 3B+ and it works and loads the menu in Arm mode.  Will need to dig into seeing if it can actually load any installers from the menu.

**Comment by antonym** [comment]
Using the latest edk2 bits, RPI4 boots into iPXE but doesn't get networking once loaded (nothing in ifstat), looks like iPXE still needs drivers added for networking.

**Comment by rgl** [comment]
I have to inform that upstream iPXE can now successfully use the network in RPi4!

The RPi4 genet ethernet driver is working since the https://github.com/pftf/RPi4/releases/tag/v1.13 release, which is included in the latest upstream edk2 bits.

**Comment by antonym** [comment]
Great to hear, I’ll try to find some time to hack on this, that was the only hold up I had to getting the menu to function.

**Comment by antonym** [comment]
Confirmed that RPi4 network works now in iPXE.  I'll probably work on getting some RPi4 bootloaders for netboot.xyz spun up over the next few weeks.

**Comment by qdrop17** [comment]
Hi everyone.
As far as I understand the issue, we still need to boot pipxe from the SD-card right? Is there any approach to TFTP-boot the Raspberry and load the ipxe via that? Our goal would be, to get rid of the SD card entirely.
Any help is highly appreciated.

**Comment by antonym** [comment]
Hey all,

I have a netboot.xyz iPXE boot loader build that works on RPI4:

http://boot.netboot.xyz/ipxe/netboot.xyz-rpi4-sdcard.img

It should work from SD Card as well as USB Key as long as boot from USB when SD card fails is set in raspi-config.  Currently I haven't gotten any options working yet, but it does boot and load the arm specific menus.  I haven't had a lot of time to dig into it further but it should at least give an initial place to tinker with.  It's still experimental so your mileage may vary.

**Comment by blackliner** [comment]
Any updates here? I assume a PXE only solution is difficult because the raspi does not send the correct arch?

**Comment by antonym** [comment]
We have a RPi4 bootloader now so closing this out.

**Comment by rgl** [comment]
@antonym, can you please point us to the commit/PR that added the bootloader? I've browsed the commits in this repository, but did not find anything that seemed related to this. Or did that happen at https://github.com/netbootxyz/pipxe?

**Comment by antonym** [comment]
Yeah, there are download links for the bootloader on the main site.  I still need to write up some docs about it.  It leverages a fork of pipxe which I pull updates into periodically but the main code to generate is here:

https://github.com/netbootxyz/netboot.xyz/commit/e23025af2c3f155f6f42edd9eeefcd90e24f32b6

At this point, it's limited because I haven't had a lot of success porting some of the OS images over but it does load up into the menu and iPXE.

**Comment by kevinelliott** [comment]
> Hi everyone.
> As far as I understand the issue, we still need to boot pipxe from the SD-card right? Is there any approach to TFTP-boot the Raspberry and load the ipxe via that? Our goal would be, to get rid of the SD card entirely.
> Any help is highly appreciated.

We're also looking for a network-only solution here. Did anything surface?

**Comment by webdog** [comment]
>We're also looking for a network-only solution here. Did anything surface?

Same question as above, I'm (note: newb to netbooting) unclear on understanding what support netboot.xyz has for the Raspberry Pi as a client via network-only booting.

The website indicates there's a DHCP-based EFI available for the Pi4 at this link : [netboot.xyz-rpi4-snp.efi](https://boot.netboot.xyz/ipxe/netboot.xyz-rpi4-snp.efi)

When I place the EFI file on my TFTP instance (Synology NAS), set it as the boot file in DHCP (On a UDM Pro, setting the values of 'DHCP Netboot Server' with the TFTP server, and this filename, and pointing 'DHCP TFTP Server' to the same value), the rpi4 doesn't request the EFI file, it looks for a subset of files from the rpi4's /boot directory, which are not present on the TFTP server.

```log
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/XXX/start4.elf, No Such File/No Access
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/XXX/start.elf, No Such File/No Access
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/config.txt, No Such File/No Access
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/vl805.sig, No Such File/No Access
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/pieeprom.sig, No Such File/No Access
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/recover4.elf, No Such File/No Access
[05-Jun-22 12:00:56] Client /volume4/pxe/tftp/recovery.elf, No Such File/No Access
[05-Jun-22 12:00:57] Client /volume4/pxe/tftp/start4.elf, No Such File/No Access
[05-Jun-22 12:00:57] Client /volume4/pxe/tftp/start.elf, No Such File/No Access
```

As a validation, I can request the EFI file all day long from other TFTP clients.

Since the PR for experimental support is closing in on two years old, no documentation, and the maintainer(s) having not replied or updated except for closing the workstream, I'm assuming that general support for rpi4 clients via netboot.xyz is not a priority given constraints? (No maliciousness/snarkiness intended in this comment 😄 )

**Comment by antonym** [comment]
2.0.57 was the last release I was building an RPI4 EFI for:

https://github.com/netbootxyz/netboot.xyz/releases/download/2.0.57/netboot.xyz-rpi4-snp.efi

I pulled it because it had started failing when building the latest and there wasn’t a lot of options that worked within the small footprint of memory. We can always bring it back but just need to have better support for it and it can be time consuming working on it just myself.

Also the last sdcard image:

https://github.com/netbootxyz/netboot.xyz/releases/download/2.0.57/netboot.xyz-rpi4-sdcard.img

**Comment by webdog** [comment]
>We can always bring it back but just need to have better support for it and it can be time consuming working on it just myself.

No worries! I appreciate the follow up and understand that these additions are not easy or simple. Semi-related, I encountered some architectural roadblocks with the UDM Pro related to DHCP netbooting with the Raspberry Pi when trying to set up iPXE last night, related to UDM's usage of DHCP option 43 and how it supports a DHCP relay vs dnsmasq's proxy.

If/When I understand this a bit more, I'd be happy to contribute/collaborate in some fashion 😄

**Comment by mcgurk** [comment]
Thank you webdog for that log snippet. I was totally unaware what files Raspberry Pi's internal networkboot was looking for. And I didn't find anywhere tutorial how to get Raspberry Pi 4 boot from network without local storage. But it was simple after I saw your log.

I got it to work without SD-card or USB-drive. I have dnsmasq (Pi-Hole) as DHCP server.

I wrote netboot.xyz-rpi4-sdcard.img to SD-card with Raspberry Pi Imager and tested with it that netboot.xyz works. Then I took SD-card off and connected SD-card to server.
Then I made /srv/tftpboot directory to server and copied everything from SD-card to there. I also copied netboot.xyz-rpi4-snp.efi to /srv/tftpboot.

Then I made /etc/dnsmasq.d/99-custom.conf file with these lines and restarted server:
enable-tftp
tftp-root=/srv/tftpboot
pxe-service=0,"Raspberry Pi Boot"
dhcp-match=set:aarch64,60,PXEClient:Arch:00011:UNDI:003000
dhcp-boot=tag:aarch64,netboot.xyz-rpi4-snp.efi

Now my Raspberry Pi 4 B boots directly to netboot.xyz without SD-card or USB-drive.

**Comment by staticdev** [comment]
Reviving this thread now for RPi5, I am using UEFI from https://github.com/NumberOneGit/rpi5-uefi but I cannot seem to make it download any specific .efi through option 67. Did anyone success on configuring the Pi to downloading TFTP netboot.xyz files?
