### ISSUE TITLE
opensuse Leap 15.1 does not work

### ISSUE THREAD

**Issue by amard33p** [netbootxyz/netboot.xyz#387]
Error - "Please make sure the installation medium is available"  
![error](https://user-images.githubusercontent.com/13570034/68540942-55b84d00-03bf-11ea-9eb9-b4316aefac53.png)

**Comment by antonym** [comment]
I gave it a try and it loaded into the GUI installer for me. Are you using dhcp or static? It sounds like it might not be retrieving the media because the network isn't up during the loading process which is why it's in the text console.

**Comment by amard33p** [comment]
I am using dhcp.
Here's the 'Ctrl+Alt+F3' log at the same time. Notice that em1 network seems to be up...but its saying "mount ok but test failed"

![image](https://user-images.githubusercontent.com/13570034/68575907-12c7a980-0493-11ea-8dfd-f6dedad17ea8.png)

**Comment by amard33p** [comment]
The DHCP server was sending out a static route which overwrote the default gateway. Apologies for the churn.
