### ISSUE TITLE
Test distribution iso, bootstrap too large to load

### ISSUE THREAD

**Issue by orange888** [netbootxyz/netboot.xyz#388]
Hi,
I am trying to boot my custom ubuntu ISO (created with https://github.com/core-process/linux-unattended-installation) . But it error-ed out "bootstrap too large to load"

[https://imgur.com/a/dc2SKPx](https://imgur.com/a/dc2SKPx)

Any idea how to resolve this?
Thanks.

**Comment by antonym** [comment]
See https://github.com/antonym/netboot.xyz/issues/333#issuecomment-553979375

but in general I would try to avoid using memdisk where you can and either use installer kernels with a preseed or extract the ISO and point to the kernels and squash files directly.
