### ISSUE TITLE
Using preseed with Ubuntu installer, DHCP fails, how to specify static IP without manual interaction?

### ISSUE THREAD

**Issue by orange888** [netbootxyz/netboot.xyz#390]
Hi,
I am using a preseed file, inside the ubuntu installer, how do I configure the ubuntu installer static IP? how do I get around the DHCP? 

[https://imgur.com/a/YRN1UIy](https://imgur.com/a/YRN1UIy)

I would like this to be fully automated.

Thanks.

**Comment by orange888** [comment]
Because I had to configure the netboot IP in the beginning to get to the main menu, can the netboot pass the static ip information to the ubuntu installer?

Thanks.

**Comment by antonym** [comment]
Probably will need to add static support to Ubuntu, Debian:

Either it'll need to be in preseed format like this or:

```
isset ${dhcp-server} || set netcfg netcfg/get_ipaddress=${netX/ip} netcfg/get_netmask=${netX/netmask} netcfg/get_gateway=${netX/gateway} netcfg/get_nameservers=${dns} netcfg/disable_autoconfig=true
```

or ip= format for casper:
http://manpages.ubuntu.com/manpages/bionic/man7/casper.7.html

Would also need to find out how you can have it select interface to use by the mac address iPXE booted into. i.e. BOOTIF=${netX/mac}

**Comment by antonym** [comment]
Focal and Groovy now use the Subiquity installer.  I've added support to leverage an interactive fallback if DHCP is not found.  It does use the new auto install instead of typical Debian preseed though.

https://github.com/netbootxyz/netboot.xyz/commit/40d124473d0fd08a39187dc965809c83e51ac141
