### ISSUE TITLE
Support Fedora CoreOS

### ISSUE THREAD

**Issue by lfarkas** [netbootxyz/netboot.xyz#394]
Fedora CoreOS already has a newer release: 30.20191014.1 while the version in src/coreos.ipxe 30.20190716.1

**Comment by thelamer** [comment]
I think the plan is to rip out CoreOS in 2.x for now , re-visiting at a later date . Though @antonym shoudl weigh in on the matter.

**Comment by antonym** [comment]
We definitely want to support Fedora CoreOS, but right now I think it's in active development so it appears to be in a state of flux.  The development branch has the latest [method](https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/coreos.ipxe.j2) of how to do it as found [here](https://github.com/coreos/coreos-installer/blob/master/README.md#installing-from-pxe).

I didn't get a successful boot but  I also haven't spent a ton of time on it yet as it's not stable. It's in the repository for now as disabled until we can get around to either get it working or wait until it's officially stable.

**Comment by lfarkas** [comment]
when i update it to the latest version it's work for me.

**Comment by antonym** [comment]
Latest build of stable Fedora CoreOS is now working in development.  Closing this out.

**Comment by bam80** [comment]
Maybe Silverblue is similar, could we try to add it also please?

**Comment by sfxworks** [comment]
Hello, was there an update to this? I do not see it in the netboot menu. 
Edit: Ah I see it under the linux installers. Was looking under live.
