### ISSUE TITLE
ArchLinux Signature Check Issue for 2019.12.01

### ISSUE THREAD

**Issue by arjitc** [netbootxyz/netboot.xyz#399]
**Describe the bug**

Was trying to boot into the ArchLinux image and it fails to verify the signature and then stops

**To Reproduce**
1. Select ArchLinux
2. Try to boot into it

**Expected behavior**

Should boot into archlinux

**Screenshots**

![Image Pasted at 2019-12-5 19-00](https://user-images.githubusercontent.com/363587/70239918-3cbe7400-1792-11ea-827d-85cb50884fbd.png)

**Additional context**

**Comment by samip5** [comment]
Disable image signature check in main menu, and try again. It will work.

**Comment by arjitc** [comment]
Thank you. That fixed it.

**Comment by antonym** [comment]
Yeah, I'm working with v2 and shifting around stuff with signatures so new additions may break until I move things over.  Disabling signatures should be let you load it.
