### ISSUE TITLE
SystemRescueCD support

### ISSUE THREAD

**Issue by HLFH** [netbootxyz/netboot.xyz#4]
Hi,

It could help to support SystemRescueCD.
http://labalec.fr/erwan/?p=946

Thanks,
HLFH

**Comment by antonym** [comment]
Should be able to get this working, but I will have to break apart the CD and host parts of it somewhere. Booting the ISO via iPXE prevents it from finding and loading sysrcd.dat.

**Comment by antonym** [comment]
Implemented here:

https://github.com/antonym/netboot.xyz/commit/c86ec9a0771ae1447f56a4d465daaedb19cd27b9

Had to crack open ISO and host on sourceforge for it to work.
