### ISSUE TITLE
Linux Mint support

### ISSUE THREAD

**Issue by GaryGate** [netbootxyz/netboot.xyz#40]
Linux Mint Cinnamon is my favourite. Any chance of support ?
http://linuxmint.com/

**Comment by antonym** [comment]
I'd love to, but it doesn't work that well with memdisk unfortunately.  See http://netboot.xyz/faq/#will-my-favorite-distribution-work

**Comment by antonym** [comment]
Clonezilla seems to have this method of booting working pretty well using the phram, mtdblock kernel module, and memdiskfind find method.  I would think this should be pretty simple to implement into most initrds that only support ISO.

**Comment by antonym** [comment]
Closing out for now, can reopen once Mint provides other ways to install rather than ISO only.  Installer kernels would be great.
