### ISSUE TITLE
Torrent downloading

### ISSUE THREAD

**Issue by thibaultmol** [netbootxyz/netboot.xyz#41]
This is probably not going to happen but I'm one of those people who seeds torrents because I just have an very high data limit (I only have the connection for the insane speeds). 

It's probably too much work. But It would be great it could download from a torrent instead of a mirror so it goes a little easier on those mirrors.

Again. Just a suggestion.

**Comment by mtelesha** [comment]
Using aria2c https://aria2.github.io/ in the back end would make this much easier. https://aria2.github.io/

**Comment by antonym** [comment]
Yeah, ultimately iPXE would need to support the ability to retrieve via torrent and then we could add the ability to flip between direct download or torrent in netboot.xyz.

**Comment by antonym** [comment]
Closing due to not currently being possible within iPXE.
