### ISSUE TITLE
Hybrid iPXE Bootloaders

### ISSUE THREAD

**Issue by antonym** [netbootxyz/netboot.xyz#416]
Investigate putting together hybrid bootloaders that compile legacy and UEFI iPXE bootloaders to cut down number of disks and make things easier.

http://forum.ipxe.org/showthread.php?tid=8132&pid=12856#pid12856

**Comment by antonym** [comment]
Look into testing and adding hybrid support from upstream: https://github.com/ipxe/ipxe/commit/79c0173d6df8580ea2e35fc173a5281e65d5321f

**Comment by JuniorJPDJ** [comment]
.

**Comment by JuniorJPDJ** [comment]
I just did:
```
./util/genfsimg -o ~/Downloads/netboot.img ~/Downloads/netboot.xyz.lkrn ~/Downloads/netboot.xyz-snp.efi
```
And I now have usb for efi + bios ;)

**Comment by antonym** [comment]
Yeah, I have some hybrid images up here already: https://boot.netboot.xyz/

I have not added them to the main downloads page on the site but will with a little more testing.

**Comment by JuniorJPDJ** [comment]
BTW. Cool addition would be also adding ` netboot.xyz-arm64.efi` to this imgs ;)

**Comment by antonym** [comment]
I was going to but I left it off to keep it from inflating the size of the file too much.  Arm isn't being heavily used in the project yet so I'll probably leave it separate for now.

**Comment by antonym** [comment]
Available now so closing
