### ISSUE TITLE
Manjaro support

### ISSUE THREAD

**Issue by Strit** [netbootxyz/netboot.xyz#43]
Since manjaro has alot of "edition", it would be great if one could just plug in this usb key, and have access to most, if not all, of them.

Hope it is possible.

**Comment by antonym** [comment]
Manjaro does not work unfortunately with memdisk, I gave it a try last week as I was going through the distrowatch list.  See http://netboot.xyz/faq/#will-my-favorite-distribution-work for more information.  Please feel free to raise it to them though and maybe that's something we can get working.

**Comment by Strit** [comment]
Oh, alright. I'll mention it for them.

**Comment by antonym** [comment]
Thanks!  Much appreciated!

**Comment by Strit** [comment]
Seems the tools used for building the iso's does not support pxe boot. :(

**Comment by antonym** [comment]
Yeah, that's what I'm running into on a lot of the distros that are ISO only without a network installer.  Using the phram module seems to be the best way to do it if using memdisk, but that does involve a bit of work within the initramfs using memdiskfind to locate the ISO in memory and mapping it to a mount.  The more distros that can figure out the implementation details, the more options I'll be able to make available.

I'm surprised so many still ship ISOs, they'd alleviate a lot of bandwidth and improve speed if they just let you pull the packages as needed.  Plus no one wants to use CDs/DVDs anymore.

**Comment by antonym** [comment]
Looks like we'll hopefully be set up to use Manjaro on the next release as they enabled memdisk support.

**Comment by Strit** [comment]
They did? That's awesome!

**Comment by antonym** [comment]
Manjaro Cinnamon 16.02 was pushed yesterday and it has the proper memdisk support built in.  I pushed up initial support for that version and I'll continue to update them as new ones come out.

https://github.com/antonym/netboot.xyz/pull/84

Thanks for the request!

**Comment by antonym** [comment]
Added 16.06-rc1 images of XFCE, KDE, and Net-Install.  Please test out if you get a chance.  I'll see about getting community images added later.  I'm only doing x86_64 as there were some phram issues with x86. 
(https://wiki.archlinux.org/index.php/USB_flash_installation_media#Boot_the_entire_ISO_from_RAM see bottom around vmalloc)

https://github.com/antonym/netboot.xyz/pull/101
