### ISSUE TITLE
If possible in the future please add unofficial non-free debian

### ISSUE THREAD

**Issue by PascalPirate75** [netbootxyz/netboot.xyz#433]
The reg debian does not include needed firmware for some devices.
This is the location of the iso's  https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current-live/i386/iso-hybrid/

If for some reason you don't want to add these that is cool.. thanks for considering.

**Comment by antonym** [comment]
That's probably something we can add, we ultimately want users to be able to boot things the first time and get up and running without worrying if it's missing a driver.

**Comment by thelamer** [comment]
sure will do

**Comment by thelamer** [comment]
In head of development 
https://s3.amazonaws.com/dev.boot.netboot.xyz/8c20f96e94ce51c0f475b4c7657f217f1c0f56d8/index.html
https://s3.amazonaws.com/dev.boot.netboot.xyz/8c20f96e94ce51c0f475b4c7657f217f1c0f56d8/live-debian.ipxe

ref before closing: 
https://github.com/netbootxyz/netboot.xyz/issues/429
