### ISSUE TITLE
Easy BCD Support

### ISSUE THREAD

**Issue by gautamkrishnar** [netbootxyz/netboot.xyz#44]
add easy BCD support

**Comment by antonym** [comment]
Looks like it requires registration to use and it also appears to be a Windows executable, which can't run from iPXE.

**Comment by berlincount** [comment]
yeaah, I think he means it the other way round (which I'm currently also searching for).

the idea would be some documented steps to use EasyBCD to configure the Windows bootmanager to allow choosing between windows and netboot.xyz.
