### ISSUE TITLE
Hiren's BootCD

### ISSUE THREAD

**Issue by ghost** [netbootxyz/netboot.xyz#46]
Is it possible to add Hiren's BootCD (http://www.hirensbootcd.org/)? It boots fine with the unzipped iso but not the zip directly from the site itself.

**Comment by antonym** [comment]
The zip file didn't seem to play with memdisk nicely and it doesn't look like there's been development on the tool in a while.  We could look into it if there was a hosted ISO.

**Comment by Enrico204** [comment]
The ISO seems to be available now, and the development has restored, so maybe this issue can be reopened @antonym ?

PS: direct ISO URL: https://www.hirensbootcd.org/files/HBCD_PE_x64.iso

**Comment by Sander0542** [comment]
I would love to see this in Netboot

**Comment by antonym** [comment]
Gave this a whirl a week ago, dumping notes here, appears that wimboot was looking for bootmgr.exe which was not present in the actual wim.  I think we could get it working but would need that bootloader present.  The bootmgr in the root of the ISO is not the one we would need either.

If anyone has cycles to dig in, it would be appreciated.

```
#!ipxe

set win_base_url https://github.com/netbootxyz/asset-mirror/releases/download/v1.0.1-0570770e/
imgfree
kernel https://boot.netboot.xyz/wimboot
initrd -n bootmgr ${win_base_url}/bootmgr       bootmgr ||
initrd -n bootmgr.efi ${win_base_url}/bootmgr.efi   bootmgr.efi ||      
initrd -n bcd         ${win_base_url}/BCD      bcd ||
initrd -n boot.sdi    ${win_base_url}boot.sdi boot.sdi ||
initrd -n boot.wim    ${win_base_url}boot.wim boot.wim
```
