### ISSUE TITLE
Add Support for FreeBSD

### ISSUE THREAD

**Issue by antonym** [netbootxyz/netboot.xyz#479]
Get FreeBSD working either with iPXE or with FreeBSD assets.  The existing solution was using memdisk to load a raw hard disk image and broke Legacy when the cert used for mfsbsd no longer worked with https.

https://github.com/netbootxyz/netboot.xyz/issues/302

We'd probably want this working with UEFI if possible too so we'd want to move away from the memdisk solution.

**Comment by thelamer** [comment]
You wanna keep this open trying to function with UEFI?

**Comment by antonym** [comment]
We can always revisit later, at least base functionality is working again but over the next few years I think Intel plans on dropping legacy support, so we should always try and favor UEFI when possible. Thanks for knocking this out!
