### ISSUE TITLE
Add menu option with list of mirror locations for OpenBSD

### ISSUE THREAD

**Issue by viq** [netbootxyz/netboot.xyz#49]
You can get a list of them at http://ftp.openbsd.org/cgi-bin/ftplist.cgi sorted by your location

**Comment by antonym** [comment]
There's not really a good way to scrape and parse that list in iPXE.  I still need to think out the mirror strategy, but with the ISO now being 8MB in size instead of 200+MB and being able to set the mirror during the install, I think we can close this one out.
