### ISSUE TITLE
Add support for K3OS

### ISSUE THREAD

**Issue by OrvilleQ** [netbootxyz/netboot.xyz#494]
Is there any plan for K3OS support?

It should be similar to Rancher OS.

https://github.com/rancher/k3os

**Comment by antonym** [comment]
Sure, we'll look into it and add it if viable.

https://github.com/rancher/k3os/releases

**Comment by thelamer** [comment]
ref: https://github.com/rancher/k3os/issues/56

**Comment by antonym** [comment]
Iniital support merged into development: https://github.com/netbootxyz/netboot.xyz/pull/505
