### ISSUE TITLE
PartedMagic

### ISSUE THREAD

**Issue by HLFH** [netbootxyz/netboot.xyz#5]
Hi,

It would be cool to support also PartedMagic.

http://labalec.fr/erwan/?p=1220

Thanks,

**Comment by sammcj** [comment]
+1

**Comment by antonym** [comment]
Would Partition Wizard work just as well?  

https://github.com/antonym/netboot.xyz/issues/6

It appears that PartedMagic now charges for their software and only older versions are available for free.  If there's something here that the other one doesn't have, let me know.
