### ISSUE TITLE
Add support for RHEL.

### ISSUE THREAD

**Issue by OrvilleQ** [netbootxyz/netboot.xyz#501]
The RHEL scripts in v1.x still work fine. Please add it back to v2.x.

**Comment by antonym** [comment]
If you go into ipxe shell and chain rhel.ipxe it should still be there.  It looks like it fell off the menu so I'll get it added back.

**Comment by antonym** [comment]
https://github.com/netbootxyz/netboot.xyz/pull/504

**Comment by thelamer** [comment]
This will be cut in the next release .
