### ISSUE TITLE
Add text based mode for Fedora and RHEL.

### ISSUE THREAD

**Issue by OrvilleQ** [netbootxyz/netboot.xyz#502]
Please add text based option for Fedora and RHEL.

It's the same as centos. I test them with v1.x but I don't know how to make edit in this new file structure so I can only rely on you guys.

**Comment by antonym** [comment]
Makes sense, should be able to add them.  For future reference, files are now here as Jinja templates, I still need to work up a contributing doc for that:

https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/centos.ipxe.j2#L29

**Comment by antonym** [comment]
https://github.com/netbootxyz/netboot.xyz/pull/503

**Comment by antonym** [comment]
Merged into development.
