### ISSUE TITLE
Add Thinstation as a utility if possible

### ISSUE THREAD

**Issue by thelamer** [netbootxyz/netboot.xyz#517]
ThinStation ( https://thinstation.github.io/thinstation/ ) has a live CD: 
https://downloads.sourceforge.net/project/thinstation/LiveCD/TS-Multiclient-Desktop-LiveCD-Demo.iso

It boots to a simple desktop with all the major access tools (citrix rdesktop etc etc), very useful tool to have in the menu.

My initial testing is that their are options in the init for defining a squash URL and pxeboot (LM=3). They seem to be non functional . 
Boot snippet: 
```
kernel ${url}vmlinuz FASTBOOT_URL=http://192.168.10.13:8080/ LM=3
initrd ${url}initrd
```

**Comment by thelamer** [comment]
Ping for myself to follow up with this. When I tested last beyond the creation of this issue we would need to fully build the OS from scratch using their config file build process and disable the fastboot options that I was referring to above as they are out of maintenance. 
Will reach out upstream and see if it something they could possible host.

**Comment by lars18th** [comment]
Hi,

The ThinkClient project https://github.com/selivan/thinclient seems a similar project. Perhaps it will more easy to include it in netboot.xyz.

Regards.

**Comment by thelamer** [comment]
@lars18th 
Just tried to build it and consume it, not very intuitive. 
The project does not publish assets, and it looks like it is specifically made to pass kernel command args to spinup a bare minimum thin client while thinstation livecd includes a bunch of apps in a desktop GUI as a demo CD. 
Regardless I am closing this, I do not want to build and maintain an entire operating system publish.

**Comment by lars18th** [comment]
OK, no problem.
