### ISSUE TITLE
Unclear if "Ubuntu" option leads to Desktop or Server

### ISSUE THREAD

**Issue by timdonovanuk** [netbootxyz/netboot.xyz#557]
As the title suggests - given the 2 major flavors of Ubuntu, is there a way clarify? I appreciate there are quite a few derivative flavors of Ubuntu, but Server & Desktop are the primary ones used. 

And if its not the Server flavor, could that be added? :)

Many thanks.

**Comment by antonym** [comment]
The Ubuntu Linux installer options are using the network boot installer kernels, which allow you to select what you want installed.  I believe Server is essentially minimal server + ssh, so if you exclude the desktop options, that should get you the server distribution.

http://cdimage.ubuntu.com/netboot/bionic/

**Comment by timdonovanuk** [comment]
Many thanks for the quick reply! I just raised another issue as my finding was any Ubuntu selection failed...I just restarted though and now its magically working? :) Some magic.
