### ISSUE TITLE
TASK [netbootxyz : Generate iPXE EFI USB image]

### ISSUE THREAD

**Issue by ChuckWhitson** [netbootxyz/netboot.xyz#566]
**Describe the bug**
Unable to build due to the following error:
TASK [netbootxyz : Generate iPXE EFI USB image] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "truncate -s 3MiB ipxe-efi.usb\n mkfs.vfat ipxe-efi.usb\n mmd -i ipxe-efi.usb \"::/efi\"\n mmd -i ipxe-efi.usb \"::/efi/boot\"\n mcopy -i ipxe-efi.usb bin-x86_64-efi/ipxe.efi \"::/efi/boot/bootx64.efi\"", "delta": "0:00:00.010369", "end": "2020-01-29 19:32:12.704305", "msg": "non-zero return code", "rc": 1, "start": "2020-01-29 19:32:12.693936", "stderr": "/bin/sh: 2: mkfs.vfat: not found\ninit :: non DOS media\nCannot initialize '::'\ninit :: non DOS media\nCannot initialize '::'\ninit :: non DOS media\nCannot initialize '::'\nBad target ::/efi/boot/bootx64.efi", "stderr_lines": ["/bin/sh: 2: mkfs.vfat: not found", "init :: non DOS media", "Cannot initialize '::'", "init :: non DOS media", "Cannot initialize '::'", "init :: non DOS media", "Cannot initialize '::'", "Bad target ::/efi/boot/bootx64.efi"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/opt/netboot.xyz/site.retry

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=30   changed=7    unreachable=0    failed=1

**To Reproduce**
1. Build fresh Debian machine.
2. Follow directions here: https://netboot.xyz/selfhosting/
3. See error

**Expected behavior**
Successful build.

**Screenshots**
Can provide, but all text of error is above.

**Additional context**
N/A

**Comment by thelamer** [comment]
Your error is mkfs.vfat is not available , probably needs to be added to the deps.

**Comment by ChuckWhitson** [comment]
mkfs: /usr/bin/mkfs.btrfs /usr/sbin/mkfs.ext2 /usr/sbin/mkfs.ext3 /usr/sbin/mkfs.ext4 /usr/sbin/mkfs /usr/sbin/mkfs.bfs /usr/sbin/mkfs.cramfs /usr/sbin/mkfs.minix /usr/sbin/mkfs.fat /usr/sbin/mkfs.msdos **/usr/sbin/mkfs.vfat** /usr/share/man/man8/mkfs.8.gz

**Comment by thelamer** [comment]
I can't replicate this on a clean Buster install , build log for reference: 

https://pastebin.com/cLW2K1Np

What happens when you call `mkfs.vfat` directly from the user you are running ansible as? Maybe /usr/sbin/ is not in your PATH settings.

**Comment by ChuckWhitson** [comment]
Is it just me or... wait a minute... hasn't /sbin/ always been in root's path on Debian?

export PATH=$PATH:/sbin/
ansible-playbook -i inventory site.yml

results in:
localhost                  : ok=38   changed=15   unreachable=0    failed=0
