### ISSUE TITLE
CentOS 8 mirror link for arm64 is wrong

### ISSUE THREAD

**Issue by stratakis** [netbootxyz/netboot.xyz#572]
When trying to do an ipxe boot of CentOS 8 for arm64, the $arch [variable](https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/centos.ipxe.j2#L21) that is used in the link is defined as `arm64` which results in a failure when trying to fetch the image. The proper platform triplet which should be used for that link is `aarch64`.

[0] https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/centos.ipxe.j2#L21

**Comment by vielmetti** [comment]
This is related to multi-arch support, #162

**Comment by vielmetti** [comment]
Blocked on #162

**Comment by antonym** [comment]
Should be fixed with the latest https://github.com/netbootxyz/netboot.xyz/pull/971
