### ISSUE TITLE
request: add Fedora Silverblue

### ISSUE THREAD

**Issue by bam80** [netbootxyz/netboot.xyz#574]
Hello, thanks for the project!
Could we add https://silverblue.fedoraproject.org/ please?
#320 #394

**Comment by antonym** [comment]
It's already there under Fedora.  From the first Fedora version menu, select the version and then that should give you a menu of flavors.

https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/fedora.ipxe.j2#L30

**Comment by bam80** [comment]
:man_facepalming: Wasn't patient enough to find it out.. :smile: 
Many thanks!

**Comment by bam80** [comment]
Install process seem just downloads all the install media to the RAM.
It works but takes a huge amount of memory and actually a time.
In boot log, I saw iSCSI lines appeared, so iSCSI probably supported by Dracut.
Wouldn't it be feasible to use iSCSI as installation media source instead?

Dunno if it's related: https://github.com/jwmullally/dracut-iscsi-target
