### ISSUE TITLE
Cannot mount /dev/loop0 in Ubuntu and Debian image

### ISSUE THREAD

**Issue by vngvng** [netbootxyz/netboot.xyz#575]
Ubuntu and Debian image not work.
Both cannot mount /dev/loop0, seems missing loop kernel module.

**Comment by thelamer** [comment]
I would not jump to conclusions, what exactly is not working for you. 
And no generalities pick a version/flavor that is not working and be specific about the bug you are experiencing.

**Comment by vngvng** [comment]
Here I was download the ubuntu-19.10-Budgie-squash image from netbook.xyz
Attached screenshot cannot mount /dev/loop0

Did I do any think wong? Please advise. 
![Screenshot 2020-02-13 at 15 18 28](https://user-images.githubusercontent.com/24654786/74410606-72f43000-4e74-11ea-8969-ce53638c4beb.png)
![Screenshot 2020-02-13 at 15 19 38](https://user-images.githubusercontent.com/24654786/74410610-75568a00-4e74-11ea-94ae-a7364f363966.png)

**Comment by thelamer** [comment]
How much ram is in the machine you are trying to boot off of?

**Comment by vngvng** [comment]
8GB from VM

**Comment by thelamer** [comment]
Then it would seem your squash file did not download properly, mine is 1.6 gigs yours says 360 megs: 
```
root@odroidxu4-3:/home/thelamer/assets/ubuntu-squash/releases/download/945f7f4b-85bee8cf# ls -lh
total 1.6G
-rw-r--r-- 1 thelamer thelamer 1.6G Feb 13 07:29 filesystem.squashfs
```
And I can boot into budgie locally hosting these assets also. 

Try re-downloading it.

**Comment by vngvng** [comment]
Oh...it works now.
Thank you
