### ISSUE TITLE
CentOS Kickstart doesn’t seem to be working

### ISSUE THREAD

**Issue by teddue** [netbootxyz/netboot.xyz#583]
After setting the kickstart URL my kickstart file gets ignored in graphical and text mode

**Comment by hkthomas** [comment]
Yes, I also encountered this problem, I tried 3 different installation methods, all failed to install

**Comment by antonym** [comment]
I think https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/centos.ipxe.j2#L51 may need to be inst.ks= instead.  I'll make that change and we can try it out.
