### ISSUE TITLE
Test forked Github branch is broken

### ISSUE THREAD

**Issue by forkiesassds** [netbootxyz/netboot.xyz#594]
**Describe the bug**
Due to the 2.0 update the test forked branch option is broken

**To Reproduce**
1. Go to 'Utilities'
2. Select 'Test forked netboot.xyz branch or hash'
3. Type in your GitHub username and branch or hash

**Expected behavior**
Your forked branch should load

**Comment by antonym** [comment]
Since we moved to templates and they are all dynamically generated now, this feature won't work anymore.  It worked previously because the files were all static.  I'll make a note to remove it.

**Comment by antonym** [comment]
Removed here: https://github.com/netbootxyz/netboot.xyz/pull/601
