### ISSUE TITLE
Ensure the preseed/kickstart URL is valid before proceeding

### ISSUE THREAD

**Issue by orange888** [netbootxyz/netboot.xyz#596]
Please check preseed/kickstart URL returning a code 200 before proceeding installation.
Thanks.

**Comment by orange888** [comment]
```
#!/bin/bash
URL=$1
curl --silent --head --location --output /dev/null --write-out '%{http_code}'  $URL | grep '^2'
```

And check the return code, $?, before preceeding.

**Comment by antonym** [comment]
I'm open to the check if you know of a good way in iPXE to do so.  That command as it stands can't be run in the iPXE code base.

**Comment by antonym** [comment]
Closing as there's not really any good way to validate non iPXE files.  If a method comes up, feel free to suggest.
