### ISSUE TITLE
md5sum: command not found

### ISSUE THREAD

**Issue by benyanke** [netbootxyz/netboot.xyz#597]
**Describe the bug**
When using the ubuntu installer on 2.0.11, the command md5sum doesn't exist and fails.

**To Reproduce**
1. Boot to menu
2. "Linux Network Installs"
3. Ubuntu 18.04
4. Install
5. See failure.

**Expected behavior**
Ideally md5sum exists, or at the least, it is removed so it doesn't fail.

The failing command appears to be line 68 of ubuntu.ipxe.

**Screenshots**
![image](https://user-images.githubusercontent.com/4274911/79091045-5dcf3c80-7d11-11ea-9700-2bdaff0ed983.png)

**Comment by thelamer** [comment]
I can't replicate this in UEFI or PCBios. 
Can you tell us more about your environment like how you are booting netboot.xyz?

**Comment by antonym** [comment]
Unable to replicate it either as the md5sum tools are currently compiled into the latest image.  Make sure you are using the latest bootloader if you aren't already.

**Comment by benyanke** [comment]
The screenshot above and tests have been done on QEMU/KVM on Ubuntu 18.04.

How can I go about ensuring I'm using the latest bootloader?

**Comment by thelamer** [comment]
I asked how you are booting netboot.xyz and your response was with QEMU/KVM on Ubuntu . 
Think objectively here, we need information about where you got the bootloader, how you are hosting it, what your basic network boot setup looks like.
Are you even network booting ? 
Have you tried the CD/usb ?

**Comment by benyanke** [comment]
Sure - here's my setup:

netboot.xyz is running on a physical host on my LAN, in docker, from image: `linuxserver/netbootxyz:latest`, with port forwards on 69/UDP and 3000.

VM network is a bridge to my LAN subnet, so the VMs exist directly on the LAN.

The KVM/QEMU VM is set to use the NIC in the boot order. This is the NIC bridged to my LAN.

Virt-manager:
![image](https://user-images.githubusercontent.com/4274911/79628051-27276680-8103-11ea-95cb-0657db7b5d9b.png)

Next, on my DHCP server (mikrotik), I have the `next server` DHCP option set to my server hosting netboot.xyz, and the `boot file name` to menu.ipxe:

![image](https://user-images.githubusercontent.com/4274911/79628073-62299a00-8103-11ea-94b6-537195f032db.png)

From there, I simply boot the VM, and it boots from the network.
![image](https://user-images.githubusercontent.com/4274911/79628143-14616180-8104-11ea-8d61-acc3b748405d.png)

![image](https://user-images.githubusercontent.com/4274911/79628148-26db9b00-8104-11ea-992f-69f359c3159f.png)

From there, I'm booted to the menu.
![image](https://user-images.githubusercontent.com/4274911/79628158-30650300-8104-11ea-89af-c9667b321f54.png)

**Comment by thelamer** [comment]
You need to double boot and chain into the boot payload not the ipxe file. 
Right now you are using KVM's slimmed down IPXE bin to directly chain into the ipxe file. 
Your boot file name on your DHCP server needs to be `netboot.xyz.kpxe` , it takes longer but it is what is needed to boot stuff properly as we build a heavy IPXE bin with all the bells and whistles that is actually up to date.

**Comment by benyanke** [comment]
Thank you, this worked! I did not realize that netboot.xyz.kpxe was the proper boot filename. That worked perfectly.
