### ISSUE TITLE
Add support for voidlinux

### ISSUE THREAD

**Issue by zen0bit** [netbootxyz/netboot.xyz#617]
What about add voidlinux support?
https://voidlinux.org/
https://github.com/void-linux
Current x64 rootfs
https://alpha.de.repo.voidlinux.org/live/current/void-x86_64-ROOTFS-20191109.tar.xz

or browse for all live cds etc...
https://alpha.de.repo.voidlinux.org/live/current/

**Comment by thelamer** [comment]
We dug into this some time ago and asked upstream to add some dracut modules to their assets: 
https://github.com/void-linux/void-mklive/issues/97

They did not want to, and we will not be building their OS from source to publish assets, so that is basically that.
