### ISSUE TITLE
centos7.8 2003 update

### ISSUE THREAD

**Issue by OvO-nei** [netbootxyz/netboot.xyz#628]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

hi Thank you for this project. centos7 was recently updated to version 7.8, and 7.7 cannot be installed. Is it possible to update iso? thank you very much.

**Comment by samip5** [comment]
Please edit your issue, and answer to the questions.

Screenshot of the issue as discussed in Discord: https://cdn.discordapp.com/attachments/425186187368595468/707655202009907330/unknown.png
