### ISSUE TITLE
Can't install CentOS

### ISSUE THREAD

**Issue by w1577395** [netbootxyz/netboot.xyz#631]
Pretty sure this is not a bug from netboot.xyz. There is no BASEOS folder in http://mirror.centos.org/centos/7.8.2003/ for CentOS 7.8.2003 so CentOS can't be installed via netboot.xyz

**Comment by antonym** [comment]
https://github.com/netbootxyz/netboot.xyz/pull/633 should fix it up once merged.

**Comment by antonym** [comment]
Merged and should be in next release.
