### ISSUE TITLE
Add ability to change kernel command line options for every linux target

### ISSUE THREAD

**Issue by cmhe** [netbootxyz/netboot.xyz#652]
In many instances it becomes necessary to customize the kernel command line before booting a image. For instance to customize the `console=*` option for boards without screen and only serial connection. (I encountered that problem when trying to boot the system rescue cd on my pc engine apu2 board)

One way to solve that would be to add a ipxe variable to every kernel command line and add a ipxe shell option to every menu item to allow customization of it. A first step would be to add the `console` ipxe variable to every kernel command line.

I don't know enough about ipxe to know if there a better ways to modify string variables from a menu. Or if there is a way to edit ipxe scripts in memory like it is in grub.

Creating custom scripts for this does not seem feasible, since that would have to be done for every linux target.

**Comment by antonym** [comment]
I think we can probably add a menu option under Utilities that allows you to set a variable that is then placed anytime a kernel command line is loaded.  Then we'd just need to load the variable if set.  Would something like that work?

**Comment by cmhe** [comment]
Sounds like it would be enough. Full parameter preview and editing capabilities would be optimal, but at least adding some optional parameters would be great.

**Comment by antonym** [comment]
Yeah, just thinking on how to avoid creating an option for every menu page.

I could just import a jinja template for each menu that reflects those settings but it might be overkill to start.  Adding the single global override option should get you what you would need to start.

**Comment by bluecmd** [comment]
+1! I need to be able to set serial console boot options as well, this would be great :-)
