### ISSUE TITLE
Change 'Boot from local hdd' countdown length / timer

### ISSUE THREAD

**Issue by trentnbauer** [netbootxyz/netboot.xyz#654]
**Is your feature request related to a problem? Please describe.**
Yes - I want to enable my VMs to boot to DHCP first, but due to the 295 second delay, this significantly increases my VM boot times and as such, increases my downtime between reboots and DR.

**Describe the solution you'd like**
The ability to adjust the 'boot from local hdd' option.
I'm sure this is already an option, I just cannot locate the command / file to edit.

**Describe alternatives you've considered**
I've attempted to add the below commands to the boot.cfg file without luck
timeout 1500
set timeout 1500

**Additional context**
N/A

**Comment by trentnbauer** [comment]
https://pasteboard.co/Jds2wCa.png

**Comment by trentnbauer** [comment]
I have found the option!!
I was originally editing the boot.cfg
I needed to edit the 'menu.ipxe' file, in particular line 49.

I changed timeout 300000 to timeout 15000

**Comment by antonym** [comment]
I can probably move that default boot config time to the boot.cfg, would that work?

**Comment by trentnbauer** [comment]
I think it would be a good idea to have it easier to access, whether that meats having it in the boot.cfg or somewhere else. The line that I edited had a bunch of other stuff in it but in saying that, the people using netboot.xyz would be more confident than myself!
