### ISSUE TITLE
Fedora CoreOS enhancement

### ISSUE THREAD

**Issue by OrvilleQ** [netbootxyz/netboot.xyz#672]
1. Different channels(Stable, Testing, Next) should be used for version differentiation instead of which Feodora version been based.

2. If ignition config url is skip, then this script shouldn't boot cause this is a must.

**Comment by OrvilleQ** [comment]
And Feodra CoreOS script is just unusable that everytime I tried to edit ignition config url it come back with this:

![image](https://user-images.githubusercontent.com/21377465/87419801-b8c14a00-c606-11ea-9db3-0975a7409228.png)

**Comment by OrvilleQ** [comment]
Fedora CoreOS script still can't use on vultr with this error:

![image](https://user-images.githubusercontent.com/21377465/87495173-4f335100-c683-11ea-9927-0a9433a51dcf.png)

**Comment by antonym** [comment]
Made a few more tweaks which should allow it to work now.  You can hit it from the development endpoint in the Utility menu to test.

**Comment by OrvilleQ** [comment]
And it just stuck here:
![image](https://user-images.githubusercontent.com/21377465/87516263-b0711980-c6af-11ea-996e-29187b256c7a.png)

Use the script from dev endpoint.

**Comment by antonym** [comment]
It got farther for me in Virtual Box, and laid down a basic install.  Are there any console setting requirements there?

**Comment by OrvilleQ** [comment]
Change to 2GB ram vm make it go farther. Seem like Coreos just like feodra require more than 1.5GB Ram for iPXE boot.

But here comes a new error.

![image](https://user-images.githubusercontent.com/21377465/87621790-262ec100-c754-11ea-96e8-729d0bc0ea7b.png)

Ps. That `${console}`  generate nothing. I think it might be better change it to `console=tty0 console=ttyS0` follow the [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/)

**Comment by antonym** [comment]
Looks like you may need 4gb of ram.

**Comment by OrvilleQ** [comment]
Yes, you are right. Tried with 4GB VM and it's success.

And still I suggest replace `${console}` with `console=tty0 console=ttyS0` follow the [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/)
