### ISSUE TITLE
Support Grml 2020.06 release

### ISSUE THREAD

**Issue by mika** [netbootxyz/netboot.xyz#678]
The Grml live system is already listed in netboot.xyz (thanks!), though it's version 2018.12 only[1], while since a few weeks we have a new stable release [Grml 2020.06](https://grml.org/changelogs/README-grml-2020.06/).

![screenshot 2020-07-17T20-27-53](https://user-images.githubusercontent.com/115592/87819448-89ac1200-c86c-11ea-8a45-eff729d9f6a6.png)

Would be great if Grml 2020.06 could be supported!

(I'm one of the core developers of Grml and would be happy to assist if there are any questions, or if there's guide how we can contribute this on our own as PR I'd appreciate pointers!)

Thanks for netboot.xyz!

[1] And AFAICS the Grml 2018.12 entry fails to boot due to `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443` nowadays.

**Comment by antonym** [comment]
2.0.18 contains updated Grml of 2020.06.

**Comment by mika** [comment]
Fantastic, that was fast - thanks! :+1:
