### ISSUE TITLE
Cannot deploy self-hosted version via ansible

### ISSUE THREAD

**Issue by altucor** [netbootxyz/netboot.xyz#684]
**Describe the bug**
Cannot deploy self-hosted netboot via ansible script

**To Reproduce**
I just followed the steps on fresh and clear Proxmox container based on Ubuntu 16.04
https://netboot.xyz/selfhosting/#deploying-using-ansible

**Expected behavior**
Correct installation via ansible script

**Additional context**
Error log during installation:

root@pxe-server:/opt/netboot.xyz# ansible-playbook -i inventory site.yml
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html
#task-include-files-and-encouraging-reuse

 for currently supported syntax regarding included files and variables. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [netbootxyz : include] ****************************************************
fatal: [localhost]: FAILED! => {"failed": true, "reason": "ERROR! 'with_filetree' is not a valid attribute for a Task\n\nThe error appears to have been in '/opt/netboot.xyz/roles/netbootxyz/tasks/generate_menus.yml': line 52, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Generate netboot.xyz source files templates\n    ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

root@pxe-server:/opt/netboot.xyz#

**Comment by antonym** [comment]
The current Ansible code is tested on Ansible 2.9.6 on Ubuntu 20.04.  You may try building on that or utilize the container build to generate the code and dump it from the proper environment.
