### ISSUE TITLE
UBCD is missing in the Utilities

### ISSUE THREAD

**Issue by avezinaATastus** [netbootxyz/netboot.xyz#690]
Wrote the latest netboot.xyz-efi.usb to my usb key.

UBCD is missing from the list.

Is it because of UEFI ?

Docs is incomplete in that regard.

**Comment by avezinaATastus** [comment]
After trying non-uefi netboot, I get the UBCD entry, but I get an error:

http://mirror.sysadminguide.net/ubcd/ubcd538.iso... Operation not permitted (http://ipxe.org/410de13c)

**Comment by samip5** [comment]
Huh, I was just about to post this too. 👍

**Comment by thelamer** [comment]
Yes, UBCD is not compatible with UEFI as it uses memdisk to load.
