### ISSUE TITLE
Arch Linux 2020.08.01 - installation files not found

### ISSUE THREAD

**Issue by schopenhauer** [netbootxyz/netboot.xyz#695]
There seems to be an issue with the URL to the _Arch Linux 2020.08.01_ image included in the latest available [netboot.xyz.kpxe](https://boot.netboot.xyz/ipxe/netboot.xyz.kpxe) (DHCP) image. Please see screenshots below.

**Step 1: List of Arch Linux OS releases**

![image](https://user-images.githubusercontent.com/2085103/90341969-9014e180-e004-11ea-98a0-67e25661e98b.png)

**Step 2: Selection of Arch Linux OS 2020.08.01**

![Screenshot_2020-08-16_17-54-04](https://user-images.githubusercontent.com/2085103/90338336-3f43bf80-dfe9-11ea-88f4-5c9b59417b3e.png)

**Comment by antonym** [comment]
Looks like upstream renamed it to vmlinuz-linux from vmlinuz, we'll get a fix for it, thanks for raising it.
