### ISSUE TITLE
The archlinux install has a broken link

### ISSUE THREAD

**Issue by renich** [netbootxyz/netboot.xyz#697]
**Describe the bug**
It seems that the installation link is wrong. 

You're trying http://mirror.rackspace.com/archlinux/iso/2020.08.01/arch/boot/x86_64/vmlinuz
The actual link should be: http://mirror.rackspace.com/archlinux/iso/2020.08.01/arch/boot/x86_64/vmlinuz-linux

Just try installing arch using netboot.xyz.

**Comment by antonym** [comment]
Thanks, we found they changed the name upstream.  It should be covered by https://github.com/netbootxyz/netboot.xyz/pull/696 and will be in the next release.  You should be able to use the development endpoint in the Utility menu for now to load up an install until it's released to production.
