### ISSUE TITLE
GRML support

### ISSUE THREAD

**Issue by rpglover64** [netbootxyz/netboot.xyz#70]
[Grml](http://grml.org/) is a bootable live system (Live-CD) based on Debian. Grml includes a collection of GNU/Linux software especially for system administrators. Users don't have to install anything on fixed storage. Grml is especially well suited for administrative tasks like installation, deployment and system rescue.

The isos seem to work; the netboot image is a tar.gz archive.

**Comment by antonym** [comment]
I wasn't able to get the ISOs to boot with memdisk, despite GRML saying they added memdisk support to one of their images for booting from Grub.

http://michael-prokop.at/blog/2011/01/07/booting-iso-images-from-within-grub2/

Did you try booting an ISO from the Utility menu?  I could probably use the netboot archive but I'd need them extracted and hosted from their site.

**Comment by rpglover64** [comment]
I successfully booted a `grml64-small_2013.09.iso` that I happened to have locally. I'll try with a newer image.

I'm not having luck with `grml64-small_2014.11.iso`. (I'm testing this in VirtualBox, booting into netboot.xyz and serving the image to test on a local webserver)

[This](http://www.mail-archive.com/grml@ml.grml.org/msg00371.html) mailing list post seems to be related to the symptoms, but I haven't read through it yet

**Comment by antonym** [comment]
Interesting, it sounds like it worked at one point on older images, maybe that's something we can raise with the GRML devs.  Arch has the [memdisk](https://www.reversengineered.com/2016/01/07/booting-linux-isos-with-memdisk-and-ipxe/) implementation working great and it's actually been available to use in a lot of the various distributions that have built on Arch as a base.  Debian Live appeared to have support built in but not in their tools that generate or mount their ISOs.  If that's something we could get added to Debian, we'd probably be able to boot a lot more distributions over time.

**Comment by rpglover64** [comment]
I [sent](http://www.mail-archive.com/grml@ml.grml.org/msg00429.html) a message to the user mailing list asking for input.

**Comment by antonym** [comment]
So I went one more version back from the latest (2014.03) and it just worked.  I guess at one point it supported memdisk, so I guess now we should find out how we get that support back in.  I've added the older version for now which seemed to work great.  Let's keep this open for now and see if we hear anything back from the developer.

**Comment by antonym** [comment]
Looks like they opened an issue, thanks @rpglover64 for kicking this off. http://bts.grml.org/grml/issue2165

**Comment by antonym** [comment]
Bumping GRML to latest test build, as memdiskfind was added back in.

https://github.com/antonym/netboot.xyz/pull/89
