### ISSUE TITLE
Arch Linux fails to boot

### ISSUE THREAD

**Issue by kinifwyne** [netbootxyz/netboot.xyz#701]
Installed on USB, try to boot to Arch Linux and get this message
```
http://mirror.rackspace.com/archlinux/iso/2020.08.01/arch/boot/x86_64/vmlinuz... No such file or  directory (http://ipxe.org/2d0c618e)
Could not boot: No such file  or directory (http://ipxe.org/2d0c618e)
Could not boot: No such file  or directory (http://ipxe.org/2d0c618e)
Error occured, press any key to return to menu ...
```

I successfully booted Debian.

netbootxyz can't load via https for some reason
tried loading http://ipxe.org/2d0c618e in a web browser, page does not exist

Attempted on a Dell Precision 3541.

**Comment by antonym** [comment]
Thanks, we found they changed the name upstream. It should be covered by #696 and will be in the next release. You should be able to use the development endpoint in the Utility menu for now to load up an install until it's released to production.
