### ISSUE TITLE
Distros missing / not working

### ISSUE THREAD

**Issue by n3gwg** [netbootxyz/netboot.xyz#705]
ipFire is at Core 147 (they are up to Core 148 now), but, that notwithstanding, Core 147 does not boot properly. Perhaps in the midst of fixing this you can upgrade it.

As well, the following distros were conspicuously absent!

FreeNAS
openmediavault
ProxMox
ophcrack-vista-livecd-3.6.0.iso
ophcrack-xp-livecd-3.6.0.iso
Tails
ovirt
backbox (not sure, might have been there)

Thanks for all your hard work!

**Comment by unixfox** [comment]
Up for proxmox!

**Comment by thelamer** [comment]
FreeNAS- BSD based and no luck getting this to boot over https, you can feel free to try.
openmediavault- I am sure I tried this previously and failed, but I can look at it again as I did not publish notes. 
ProxMox- This is technically possible and i have proofed it out https://github.com/netbootxyz/netboot.xyz/discussions/33, but it is a license and permission issue.
ophcrack- This is possible, but essentially we would just be booting slitaz with the app, the rainbow tables for cracking passwords are expected to be mounted via the CD there is no boot logic to pull that in from a remote source and store in a ramdisk, I am not sure how useful this would be without the tables baked into the image. 
Tails- We had this briefly, but their pre init process is specifically designed not to allow network access, while patching their changes we essentially broke the security model and the OS itself. It was functional, but not something we could continue to reccmmend and distro. 
ovirt- this is not a distro
backbox- we have this in a livecd
