### ISSUE TITLE
please update coreos or add a parameter

### ISSUE THREAD

**Issue by lfarkas** [netbootxyz/netboot.xyz#710]
currently in roles/netbootxyz/defaults/main.yml the Fedora CoreOS version is hard coded to 32.20200629.3.0. the best would be if it can be a parameter like the roles/netbootxyz/templates/menu/coreos.ipxe.j2 install_device and the ignition_url. the build_version can be also input parameter or if not given can use the default from the main.yml.

anyway the latest version is 32.20200907.3.0 and there is a release in every 2 weeks.

**Comment by antonym** [comment]
CoreOS build versions are now automated for Stable so they should be updated periodically now.
