### ISSUE TITLE
After pre-seed install bugs

### ISSUE THREAD

**Issue by nickkostov** [netbootxyz/netboot.xyz#711]
When using preseed file, I noticed some bugs after install, like gnome-terminal not working correctly in ubuntu.

Used preseed:
d-i debian-installer/locale string en_US.UTF-8

##############################CLOCK##############################

d-i clock-setup/utc boolean true
d-i clock-setup/utc-auto boolean true
d-i time/zone string Europe/Sofia
##############################CLOCK##############################

##############################KERNEL##############################

d-i base-installer/kernel/image string linux-generic

##############################KERNEL##############################

##############################GRUBAUTOMATION##############################
d-i grub-installer/only_debian boolean true
##############################GRUBAUTOMATION##############################

##############################KEYBOARD##############################

d-i console-setup/ask_detect boolean false
d-i keyboard-configuration/xkb-keymap select us
d-i keymap select us
d-i keyboard-configuration/layoutcode string us
d-i keyboard-configuration/modelcode string pc105
d-i keyboard-configuration/layout string "American English"

##############################KEYBOARD##############################

##############################NETWORKAUTOMATION##############################

d-i netcfg/choose_interface select auto
d-i hw-detect/load_firmware boolean true
#test that this will give random hostname
d-i netcfg/get_hostname string ubuntu
##############################NETWORKAUTOMATION##############################

##############################DISK AUTOMATION##############################
d-i partman-auto-lvm/guided_size string max
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman/choose_partition select finish
d-i partman/confirm_nooverwrite boolean true
d-i partman/confirm boolean true
##############################DISK AUTOMATION##############################

##############################APTAUTOMATION##############################
#apt
#d-i apt-setup/country BG
#d-i apt-setup/directory string /ubuntu

##############################APTAUTOMATION##############################

##############################MIRRORS##############################
d-i mirror/country string auto
d-i mirror/suite string focal
d-i mirror/http/hostname string bg.archive.ubuntu.com
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string

##############################MIRRORS##############################

##############################SOFTWARE##############################
d-i pkgsel/include string openssh-server build-essential ubuntu-desktop vim terminator htop
d-i pkgsel/install-language-support boolean false
d-i pkgsel/upgrade select full-upgrade
d-i pkgsel/update-policy select unattended-upgrades
d-i pkgsel/language-packs multiselect en, bg
##############################SOFTWARE##############################

##############################USERS##############################

d-i passwd/root-login boolean true
d-i passwd/root-password-crypted password smpass
d-i passwd/user-fullname string smstring
d-i passwd/username string user
d-i passwd/user-password-crypted password smpass

d-i passwd/user-default-groups user

##############################USERS##############################

##############################SCRIPTSTEST##############################
#No scripts work

##############################SCRIPTSTEST##############################

##############################AFTERINSTALLACTION##############################
d-i finish-install/reboot_in_progress note
##############################AFTERINSTALLACTION##############################

**Comment by nickkostov** [comment]
I am installing ubuntu20.04

**Comment by nickkostov** [comment]
Also will there be a feature to use the cloud-init instead of preseed

**Comment by antonym** [comment]
I'm not sure what the bug is... if it's loading the preseed and doing actions it's working, you may need to make some fixes to the preseed.

**Comment by nickkostov** [comment]
So, after installing the OS, using the preseed. There are some missing functions. Like for example the gnome terminal is not working at all.

**Comment by antonym** [comment]
You may need to double check the packages being installed. If you do a manual install do you have the same behavior?  Is terminator possibly being installed and preferred as the default over gnome terminal?

**Comment by nickkostov** [comment]
Well, I was not going to bring it here if I did not try out to add gnome-terminal in there.
"d-i pkgsel/include string openssh-server build-essential ubuntu-desktop vim terminator htop" 
It was without "terminator" when I saw that there is a trouble with it. 
I thought its going to be best if I add it in order to make sure there is a console which I could use in order to run the start up scripts on the hosts.
