### ISSUE TITLE
Update Anarchy Linux Builder

### ISSUE THREAD

**Issue by antonym** [netbootxyz/netboot.xyz#714]
Anarchy Linux has transitioned to gitlab (https://gitlab.com/anarchyinstaller/installer) and has archived the github repo.

Need to update the builder to reflect the new location here:

https://github.com/netbootxyz/asset-mirror/tree/anarchy

**Comment by zellkou** [comment]
I found the correct url for gitlab's api https://gitlab.com/api/v4/projects/anarchyinstaller%2Finstaller/releases. Passing it through jq yields [releases.txt](https://github.com/netbootxyz/netboot.xyz/files/5337262/releases.txt) but trying to parse it with jq to return only the direct_asset_url has bested me for hours and my googlefu trying to learn jq's syntax has left me with a migraine. I hope this helps.

**Comment by thelamer** [comment]
https://github.com/netbootxyz/asset-mirror/commit/55d9fe94b7aefd90af2a00a24e223a6a42d2b18c
@zellkou can you test out the head build when you get a chance? I am not 100% the arch patches I have in place are still compatible. 
https://github.com/netbootxyz/docker-mod-layers/blob/archiso/root/patch

**Comment by zellkou** [comment]
@thelamer Arch works correctly.

**Comment by antonym** [comment]
Thanks all!
