### ISSUE TITLE
SuperGrub wont work: Operation not permitted

### ISSUE THREAD

**Issue by abbbi** [netbootxyz/netboot.xyz#782]
Hi,

it seems the SuperGrub entry doesnt work anymore, see screenshot.
![supergrub](https://user-images.githubusercontent.com/3919561/100590970-6357b200-32f5-11eb-92f7-0d44a9a79511.jpg)

**Comment by BasicWombat** [comment]
Seems to be related to #785

**Comment by Firminator** [comment]
https://github.com/netbootxyz/netboot.xyz/blob/0799ef3f34f72f5141c73d7626ac6f74b52dcfd3/roles/netbootxyz/defaults/main.yml#L682

Could it be because SourceForge has moved the download location? I see a 301 (moved), then 302 (redirect), and a switch from HTTP to HTTPS.

> $ wget http://master.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso

> --2020-12-29 23:56:18--  http://master.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso
> Resolving master.dl.sourceforge.net (master.dl.sourceforge.net)... 216.105.38.12
> Connecting to master.dl.sourceforge.net (master.dl.sourceforge.net)|216.105.38.12|:80... connected.
> HTTP request sent, awaiting response... **301 Moved Permanently**
> Location: http://downloads.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso [following]

> --2020-12-29 23:56:19--  http://downloads.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso
> Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
> Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://phoenixnap.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso [following]

> --2020-12-29 23:56:20--  https://phoenixnap.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso
> Resolving phoenixnap.dl.sourceforge.net (phoenixnap.dl.sourceforge.net)... 184.164.141.26
> Connecting to phoenixnap.dl.sourceforge.net (phoenixnap.dl.sourceforge.net)|184.164.141.26|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 16361472 (16M) [application/octet-stream]
> Saving to: ‘super_grub2_disk_hybrid_2.04s1.iso’
> 
> super_grub2_disk_hy 100%[===================>]  15.60M  8.08MB/s    in 1.9s    

Here's another alternative direct link from another mirror:
https://iweb.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso

**Comment by Firminator** [comment]
Nevermind. Tried troubleshooting before actually reproducing :( I just tested this and SuperGrub loads fine for me.

**Comment by thelamer** [comment]
I can't reproduce this, please use discord for support: 
https://discord.gg/An6PA2a
