### ISSUE TITLE
ArchLinux&Ubuntu, unable to download these files.

### ISSUE THREAD

**Issue by catnyaa** [netbootxyz/netboot.xyz#802]
**Describe the bug**
Booting using IPXE.

**Screenshots**
ArchLinux
![image](https://user-images.githubusercontent.com/22401759/103156770-5096a700-47e7-11eb-8d4d-3461312621c1.png)
Ubuntu20.04
![image](https://user-images.githubusercontent.com/22401759/103156804-a0756e00-47e7-11eb-941d-7d1772efbc7e.png)

**Comment by antonym** [comment]
Both appear to work for me directly from boot.netboot.xyz.
