### ISSUE TITLE
USB UEFI image not working

### ISSUE THREAD

**Issue by fidelix** [netbootxyz/netboot.xyz#805]
Downloaded https://boot.netboot.xyz/ipxe/netboot.xyz-efi.usb
Burned it to USB with Rufus.

Nothing shows up in the boot menu of my motherboard.
I can boot other Windows, Linux etc UEFI usb images just fine

**Comment by antonym** [comment]
I was able to burn the same file to a USB key and boot it without any issues so I don't think its a bad image.

**Comment by fidelix** [comment]
Well I tried on 2 different PCs with different motherboards, 2 different usb devices on my side. Perhaps you can provide some instructions on how one might be able to boot it?

Also, did you burn it with rufus?

**Comment by antonym** [comment]
No, I just did dd to the USB key from MacOS.

**Comment by fidelix** [comment]
Tried from Linux:

```
# dd if=netboot.xyz-efi.usb of=/dev/sdc
6144+0 records in
6144+0 records out
3145728 bytes (3.1 MB, 3.0 MiB) copied, 0.621104 s, 5.1 MB/s
```

Doesn't show up in boot list. If I turn CSM on, it shows up in legacy mode, but says the media is not bootable (naturally as it is trying to do legacy bios booting).

**Comment by fidelix** [comment]
I just tried the non-uefi usb image and it boots fine (with CSM), although it doesn't recognise my network interface (Intel® 2.5GbE LAN chip).

My motherboard is the Gigabyte Z490 VISION G.

**Comment by fidelix** [comment]
This shouldn't be closed. I am sure there is a problem with the UEFI USB image, unless I am doing something wrong to boot it, have to enable something on the motherboard to boot it, etc.

But all other UEFI-only linux images I try to boot work just fine. Again, I tried in 2 different motherboards.

**Comment by thelamer** [comment]
Did you disable secureboot in your bios ? IPXE images will never have a valid UEFI sig. I am going to close this issue, feel free to reply though I will get pinged and will respond. I cannot replicate this on any of my 3 test machines.

**Comment by nzbart** [comment]
I know that this issue is closed, but I'd just like to mention that I'm having the same problem as the OP. Other OSes work fine, but writing netboot.xyz to USB using `dd` results in a USB that appears to have the EFI partition when mounted but will not boot on two different PCs I've tried.
