### ISSUE TITLE
Is it possible to change ubuntu 20.04 to traditional net install?

### ISSUE THREAD

**Issue by Remonli** [netbootxyz/netboot.xyz#806]
Hello,

Now ubuntu 20.04 will try to download server live iso and mount it ,then installation will be done by new installer,this is 
quite differrent from ubuntu 18.04,which will do installation with traditional net installer. 

Is it possible to make 20.04 as same as 18.04 ? The new installer need download full server live iso, it can not work properly
on many cloud server like Oracle. In the mean time,it is also nother better than traditional installer .

You can find traditional installer here for 20.04 
http://archive.ubuntu.com/ubuntu/dists/focal-updates/main/installer-amd64/current/legacy-images/netboot/ .

**Comment by antonym** [comment]
I agree that the old style network bootable installer is better and more lightweight but Ubuntu is moving away from the Debian Installers.  With the 20.10 launch, they marked the 20.04 LTS installers as legacy so we made the switch to be on the more supported and updated path.  Is the issue that the ignited does not have any networking connection when downloading the ISO?

**Comment by Remonli** [comment]
The server can be booted with netboot.xyz.efi, but failed downloading the live server iso. 
Even if it can be download successfully, 900MB iso is too much for many cloud servers which have 512M mem or less. 

Canonical removed d-i installer support from 20.10 , and 20.04 still works as legacy , so maybe netboot.xyz can 
keep traditional way for 20.04 LTS and switch from 20.10 ? 

Thanks for your great work for this project. @antonym

**Comment by antonym** [comment]
I'll look at seeing if we can at least make 20.04 LTS work with both for now, I was trying to avoid the ugliness of branching the code just for that one version.
