### ISSUE TITLE
Distro Request: PartedMagic

### ISSUE THREAD

**Issue by j0nnymoe** [netbootxyz/netboot.xyz#807]
**Is your feature request related to a problem? Please describe.**
New Distro request for netboot

**Describe the solution you'd like**
Please could I request PartedMagic for netboot.xyz - https://partedmagic.com/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks!

**Comment by antonym** [comment]
Unfortunately it's a commercial product and no longer free, so we'd be unable to add it.

**Comment by j0nnymoe** [comment]
Well I hadn't realised that! Apologies for the request, I should've checked!
