### ISSUE TITLE
Distro Request: RescueZilla

### ISSUE THREAD

**Issue by j0nnymoe** [netbootxyz/netboot.xyz#808]
**Is your feature request related to a problem? Please describe.**
New Distro request for netboot

**Describe the solution you'd like**
Please could I request RescueZilla for netboot.xyz - https://rescuezilla.com/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks!

**Comment by antonym** [comment]
Looking at this one now, seems easy enough to ingest, will see how well it netboots.

**Comment by thelamer** [comment]
This will be included in the next tagged release and is available at the dev endpoint. 
https://s3.amazonaws.com/dev.boot.netboot.xyz/a6f6099898eb536609f79696ab1d4d95492d1bf1/index.html
