### ISSUE TITLE
Distro Request: Redo Rescue

### ISSUE THREAD

**Issue by j0nnymoe** [netbootxyz/netboot.xyz#809]
**Is your feature request related to a problem? Please describe.**
New Distro request for netboot

**Describe the solution you'd like**
Please could I request Redo Rescue for netboot.xyz - http://redorescue.com/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks!

**Comment by thelamer** [comment]
This is buster based with gz initrd kernel options:
```
boot=live quiet splash noprompt nocomponents setkmap=us
```
(just making notes)

**Comment by thelamer** [comment]
https://github.com/netbootxyz/netboot.xyz/pull/893
