### ISSUE TITLE
Restarting docker container resets boot.cfg and other menu changes configured using web interface.

### ISSUE THREAD

**Issue by jerrywoo96** [netbootxyz/netboot.xyz#814]
I've customised my boot cfg, menu.ipxe and windows.ipxe via the web interface. restarting the container resets those files. How to make it persistent?

**Comment by thelamer** [comment]
You need to mount your config directory as outlined in the usage commands here:
https://github.com/linuxserver/docker-netbootxyz#usage

If you are still having issues please hop on the Linuxserver discord for support: 
https://discord.gg/YWrKVTn
