### ISSUE TITLE
Troubles with preseed.cfg in Ubuntu option.

### ISSUE THREAD

**Issue by nickkostov** [netbootxyz/netboot.xyz#815]
**Describe the bug**
Preseed.cfg does not automate the installation.

**To Reproduce**
1. Select network installs.
2. Choose ubuntu
3. Ubuntu 20.04.1+ and use preseed 
4. Load the preseeded cfg and check it out.
5. It seems to load it but it does not.
6. What happens is that it skips the part and downloads the Ubuntu 20.04.1 live server 
7. It loads default ubuntu server installation not automated.
8. 
**Expected behavior**
Automated ubuntu install 

**Screenshots**

I can provide the preseed.cfg file.

**Comment by nickkostov** [comment]
Just tested with different versions of Ubuntu:
20.10 - no go
20.04 - no go
18.04 - works

**Comment by nickkostov** [comment]
Additions 18.04 installed me 20.04

**Comment by antonym** [comment]
20.04 and 20.10 both use https://ubuntu.com/server/docs/install/autoinstall in the Subiquity installers.

If you need to do preseed on 20.04, I'm adding the legacy back in (see the development endpoint in utilities), but going forward, Ubuntu is getting rid of old debian installer and preseeds.

**Comment by nickkostov** [comment]
@antonym just to get this clear if I create the file for Subiquity  installer and pass it as a preseed, will this work out.

**Comment by antonym** [comment]
The installer for 20.04 will support either, if using subiquity, you need to use autoinstall, if using legacy, it'll use d-i preseed.

**Comment by nickkostov** [comment]
Thanks for your reply will try it out and will update you if there are troubles ahead.
