### ISSUE TITLE
Operation not permitted when trying to use custom menu

### ISSUE THREAD

**Issue by bjo81** [netbootxyz/netboot.xyz#819]
**Describe the bug**
I'm getting a "Operation not permitted" error.

**To Reproduce**
* Tools -> Custom Menu -> github username: bjo81
* tries to load https://raw.githubusercontent.com/bjo81/netboot.xyz-custom/master/custom.ipxe
* gets Operation not permitted / Error Code 410de1

**Expected behavior**
Just load the custom menu :)

**Additional Info**
Redownloaded https://boot.netboot.xyz/ipxe/netboot.xyz.kpxe to have the newest netboot, but no luck.

**Comment by Firminator** [comment]
https://github.com/netbootxyz/netboot.xyz/issues/785

**Comment by bjo81** [comment]
Thanks for the hint, unfornuately I did not find it.
