### ISSUE TITLE
Distro request: Truenas

### ISSUE THREAD

**Issue by diwu1989** [netbootxyz/netboot.xyz#833]
**Is your feature request related to a problem? Please describe.**
Please add Truenas netboot option:
http://apt.tn.ixsystems.com/truenas/unstable/dists/truenas/main/installer-amd64/current/images/netboot/

**Describe the solution you'd like**
Under BSD choice, we should be able to select TrueNAS as the operating system

**Describe alternatives you've considered**
Custom menu script fork, but it's better for Truenas to be included in the official

**Additional context**
I want to use this to bootstrap and install Truenas on Equinix Metal

**Comment by ghost** [comment]
That's an unmodified Debian Sid netboot from almost a year ago. It's probably an artifact from the development of TrueNAS SCALE. There's no documented way to use it to install TrueNAS SCALE (which is Linux-based), let alone a BSD-based one. In fact, there's a good chance it can't install anything.

**Comment by thelamer** [comment]
I'm not gonna close this one, this does not have out of the box support to be network booted as an installer as @TooDumbForAName  pointed out what you are linking to is not the current truenas project, also their download links are behind a signup wall.
They also are a paid product for the most part outside of one off installs.

**Comment by docdawning** [comment]
Phh, TrueNAS offers vast functionality on their free tier. It's a FreeBSD appliance distro that's absolutely epic
