### ISSUE TITLE
support debian-firmware installer

### ISSUE THREAD

**Issue by divinity76** [netbootxyz/netboot.xyz#836]
**Is your feature request related to a problem? Please describe.**
Some servers require closed-source network drivers (or raid drivers? i've seen both) which Debian isn't including in their base installer, but they have an installer labeled [unofficial/non-free/cd-including-firmware](https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/) (interestingly, Ubuntu does provide these extra drivers, Ubuntu's normal installer is comparable to Debian's unofficial-including-firmware installers)

**Describe the solution you'd like**
netboot.xyz support for the installers found at https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/

**Describe alternatives you've considered**
installing Ubuntu instead of Debian is an easy workaround..

**Additional context**
example of server needing the firmware installer for network support: ![image](https://user-images.githubusercontent.com/1874996/106221754-7ea04a00-61de-11eb-993d-35bda038ff5e.png)

**Comment by thelamer** [comment]
We do this now: 
https://github.com/netbootxyz/debian-squash/blob/kde-10/settings.sh#L1
