### ISSUE TITLE
Support For Antivirus Live CD in Utilities section

### ISSUE THREAD

**Issue by bforcier299** [netbootxyz/netboot.xyz#838]
Hello,

Could you please add support for Antivirus LiveCD from 4mLinux?

It's a ClamAV LiveCD with ability to update in RAM the most recent definitions as it can download them from clams repository.

More info here:

https://antiviruslivecd.4mlinux.com

**Comment by antonym** [comment]
4M Linux Antivirus is under the Utilities menu already.

**Comment by bforcier299** [comment]
my bad, thank you!
