### ISSUE TITLE
Ubuntu 20.04.01 image missing from releases.ubuntu.com

### ISSUE THREAD

**Issue by rxbynerd** [netbootxyz/netboot.xyz#840]
**Describe the bug**
Attempting to install Ubuntu 20.04 errors out because 20.04.01 has been pulled from the mirror

**To Reproduce**
1. Go to 'Linux Network Installs'
2. Select 'Ubuntu'
3. Select 'Ubuntu 20.04 LTS Focal Fossa (Subiquity)'
4. Select 'Install'

**Expected behavior**
Ubuntu 20.04 LTS installer boots

**Screenshots**
<img width="1043" alt="Screenshot 2021-02-05 at 00 08 01" src="https://user-images.githubusercontent.com/816243/106972714-4bfbd180-6749-11eb-898c-0573ddc5cd12.png">

**Additional context**

I've attempted to look at the source code to figure out what's going on here. The following diff produces an `ubuntu.ipxe` file with the correct `version_number` set, but I'm concerned this isn't enough for a pull request given what's going on in [netbootxyz/ubuntu-squash](https://github.com/netbootxyz/ubuntu-squash).

```diff
diff --git a/endpoints.yml b/endpoints.yml
index 8ec1eb4..4e574c0 100644
--- a/endpoints.yml
+++ b/endpoints.yml
@@ -1438,7 +1438,7 @@ endpoints:
     - initrd
     - vmlinuz
     os: ubuntu
-    version: 20.04.1
+    version: 20.04.2
     codename: focal
     flavor: netboot
     kernel: ubuntu-20.04-netboot
```

I can create pull requests with some prior art or direction on approach, but I couldn't find anything for bumping ubuntu versions in the pull request history.

On a side note, I would like to thank everyone contributing to this project — it's endlessly useful, and I appreciate your time. :bow:

**Comment by antonym** [comment]
Thanks, development endpoint should have it now and it'll go out in the next release.
