### ISSUE TITLE
Ubuntu focal (subiquity) trying to connect over ipv6 for image download when no ipv6 is available

### ISSUE THREAD

**Issue by rknightion** [netbootxyz/netboot.xyz#843]
**Describe the bug**
When trying to install Ubuntu focal subiquity from the menu, it fails to download the release from releases.ubuntu.com as the DNS resolution is returning an ipv6 address, even though there is no ipv6 configured in the network (see screenshot):

This is causing the install to fail on my networks where there is no ipv6 connectivity.

**To Reproduce**
Try installing ubuntu focal subiquity from the netboot menu on a network with ipv6 disabled

**Expected behavior**
That the ipv4 address returned by DNS is used to pull the iso file

**Screenshots**
<img width="935" alt="Screenshot 2021-02-10 at 16 25 01" src="https://user-images.githubusercontent.com/12484127/107539417-d9fa1100-6bbc-11eb-8d53-bc294ccbd3d7.png">

**Additional context**
I'm using the linuxserver.io self hosted netboot.xyz, but with no changes to any menu files. Perhaps there is a menu option I should change to disable ipv6 at kernel time boot?
Using the legacy installer method seems to work fine

**Comment by thelamer** [comment]
I can't duplicate this because I don't have ipv6 setup on my local network. The kernel command line option you are looking for is: 
```
ipv6.disable=1
```
I am hesitant to disable this project wide though not sure if it is only something on your network.

**Comment by rknightion** [comment]
I'm not sure if I explained myself properly, but I don't have ipv6 on my network at all. That's what's caused the issue in a way; something is trying to use the ipv6 address to download the files but I don't have ipv6 enabled on the network so it fales. 
Doing the ipv6.disable=1 option worked for me as a workaround, so that is much appreciated.

**Comment by thelamer** [comment]
Something on your DHCP setup has to be offering a ipv6 address. I get IPv4 on two different networks I tested it on, so it is not a default setting or something.

**Comment by antonym** [comment]
Closing for now, if it becomes an issue, we could always add as an option, but you should be able to override the kernel command line for now.
