### ISSUE TITLE
Can't download ISO images

### ISSUE THREAD

**Issue by dbohdan** [netbootxyz/netboot.xyz#85]
I get a 403 Forbidden response like the one below when trying to download the ISO file from https://boot.netboot.xyz/ipxe/netboot.xyz-dhcp.iso or https://boot.netboot.xyz/ipxe/netboot.xyz-static.iso.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>71CAB6F19A14D43F</RequestId><HostId>H3+i2aFEwG5M20qz+3xgxfZnxAyjHYW9Sm0pvvgmkratFum7DLcnS2FksH41+UiAWSlMmge0Q68=</HostId></Error>
```

<hr>

**Edit:** The download link https://boot.netboot.xyz/ipxe/netboot.xyz.iso works. It appears that the links above are simply obsolete and should be removed from the page http://netboot.xyz/boot-iso/.

**Comment by antonym** [comment]
Thanks, I corrected those links here:

https://github.com/antonym/netboot.xyz/commit/739378ef1171432b16a6adb1375bb268a57e66ab

I consolidated the bootloader so now it has the option of a failsafe menu for manual configuration if needed, so the older disks are obsolete.

If you find any other broken links, feel free to open an issue.
