### ISSUE TITLE
"Permission denied" error when you try to boot DBAN 

### ISSUE THREAD

**Issue by dbohdan** [netbootxyz/netboot.xyz#86]
![screenshot](https://cloud.githubusercontent.com/assets/3179832/13407996/032e00c4-df34-11e5-95b2-aa312909a8ab.png)

Edit: I get the same error for other disc images hosted on SourceForge.

**Comment by antonym** [comment]
GIve it a try now, the iPXE root ca cross signing cert had expired and is now fixed.

**Comment by dbohdan** [comment]
> GIve it a try now

It works!

**Comment by timwhite** [comment]
I'm hitting this issue again. Oddly enough, not on all computers, but on some. Any ideas?

**Comment by dragon788** [comment]
I've hit this recently as well. Twiddling the signature options didn't help a lot.
