### ISSUE TITLE
after select centos to install ,then boot with error ...

### ISSUE THREAD

**Issue by wxlg1117** [netbootxyz/netboot.xyz#866]
vultr.com, 1g vps:
boot from iso : https://github.com/netbootxyz/netboot.xyz/releases/download/2.0.35/netboot.xyz.iso

after select centos to install ,then boot with error ...

![Snipaste_2021-04-07_03-15-41](https://user-images.githubusercontent.com/9752596/113769425-90a8e680-9753-11eb-82b4-094d3e7a3fe9.jpg)

![Snipaste_2021-04-07_03-15-56](https://user-images.githubusercontent.com/9752596/113769459-94d50400-9753-11eb-81cd-7929e1a26760.jpg)

![Snipaste_2021-04-07_03-20-41](https://user-images.githubusercontent.com/9752596/113769483-99012180-9753-11eb-9179-28df7484f475.jpg)

looks like dhcp get ip address error, but when i check netboot.xyz menu :network card info ,It shows the correct ip address, mask and gateway .

**Comment by antonym** [comment]
You'll need to increase the RAM (no space left on device). 1GB is too small to load the rootfs.img into RAM, you'll probably need at least 4GB.

**Comment by TheCableGuy99** [comment]
Sorry to re-open this, I am also struggling with the exact same error. I am new to netboot.xyz though so not sure exactly which device you are referring to adding more RAM to?

The device booting has 32GB RAM, the DHCP Server (pfSense router) has 8GB RAM (although I doubt this is what you mean), the VM Host has 16GM RAM and the netboot.xyz Docker container within the VM appears to be set to "Unlimited" meaning it has the full 16GB of the VM host.

Am I missing something? Please can you give some instructions for a newbie?

Thanks.
