### ISSUE TITLE
Keyboard doesn´t work on macbook pro booting usb pen with refind.

### ISSUE THREAD

**Issue by netbrain** [netbootxyz/netboot.xyz#87]
On my MacBook Pro (15-inch, Mid 2009), the usb pendrive of netboot.xyz doesn't work properly in terms of the keyboard interface.

The onboard keyboard and attached usb keyboards are completely dead when entering the first boot menu of netboot.xyz. slowly ticking down to booting local hdd..

**Comment by antonym** [comment]
I haven't had the chance to try it on a Macbook but you might hunt around on the iPXE lists/forums to see about USB key and keyboard conflicts in the past.  I've seen some over time and there have been either patches or other ways to build the key to include the proper support.  If I have some time I'll play around with it.

**Comment by netbrain** [comment]
Why was this closed? has it been fixed?

**Comment by antonym** [comment]
You'll probably want to ask the iPXE lists/forums for a solution to get Macbook and keyboard interface working.  There's not a whole lot that I can really do except for tweaking the iPXE driver disk if you find a solution.  If the keyboard isn't working, then it's probably a bug in iPXE itself.
