### ISSUE TITLE
Operation Not Permitted when Trying to Netboot Windows Installer

### ISSUE THREAD

**Issue by morg-mov** [netbootxyz/netboot.xyz#870]
Trying to netboot a Windows 10 Installation hosted on a web server.
Every time it attempts to retrieve the files it needs, it throws an "Operation not Permitted" error.
![image](https://user-images.githubusercontent.com/56270390/114074442-5eda7180-9872-11eb-95dc-be26e9c4d36d.png)
You can check out the web server if you wish to see if I set anything up wrong, but as far as I can tell, I set it up correctly.
https://pxe.morg-s9.cf

**Comment by antonym** [comment]
It's a TLS error, so more than likely the webserver is not using iPXE compatible https protocols.  See https://ipxe.org/crypto for what protocols are supported.

**Comment by morg-mov** [comment]
Tried setting TLS1.2 only to no avail, so I just turned off SSL and it works. Thanks.
