### ISSUE TITLE
Ubuntu does not autoinstall as expected with auto-install.

### ISSUE THREAD

**Issue by nickkostov** [netbootxyz/netboot.xyz#881]
**Describe the bug**
When installing with auto-install Ubuntu 20.04 does not work it starts downloading the .iso and it boots it.
Lead me to graphical experience but still can not install.
**To Reproduce**
1. Go to Ubuntu 20.04 Legacy/New & use the preseed/autoinstall way.
2. I add the http://link-to-my-auto install file.
3. Starts installing but after around 30 seconds it starts downloading the .iso for ubuntu and just boots it in graphical.
4. I boot in uefi mode, this could be the reason --> a lot of threads state it is not working.
5. Can you paste me the link to pull request in which the debian-installer was updated. I would like to try it back again. 

**Expected behavior**
Ubuntu should autoinstall it self.

**Screenshots**
Sorry but I did not have my phone with me.

Thanks.

**Comment by nickkostov** [comment]
I can confirm that Legacy installer does not work with preseeds.
Tested it right now in UEFI

**Comment by antonym** [comment]
Is it the preseed method or the autoinstall method that isn't working for you?  The updated subiquity installer uses the autoinstall method and downloads the iso during kernel boot up.  The older legacy method uses the install kernels to do the install and looks for a preseed style file.

Can you detail which method you were trying and which one you were having problems with?

**Comment by andyloree** [comment]
I am having the same problem, using autoinstall with UEFI vm's, have not tried preseed

**Comment by andyloree** [comment]
> 
> 
> I am having the same problem, using autoinstall with UEFI vm's, have not tried preseed

Ignore, UEFI netboot with autoinstall is working.  My issue was the naming convention Ubuntu has for autoinstaller...URL needs to be the path which has two files, named user-data and meta-data

**Comment by nickkostov** [comment]
> Can you detail which method you were trying and which one you were having problems with?

I will update you tomorrow regarding that, when I have access to the systems.

**Comment by nickkostov** [comment]
> data

I will try that out!

**Comment by nickkostov** [comment]
> Ignore, UEFI netboot with autoinstall is working. My issue was the naming convention Ubuntu has for autoinstaller...URL needs to be the path which has two files, named user-data and meta-data

I will try that one out, I think I made a mistake during the creation of the files.

**Comment by nickkostov** [comment]
> Is it the preseed method or the autoinstall method that isn't working for you? The updated subiquity installer uses the autoinstall method and downloads the iso during kernel boot up. The older legacy method uses the install kernels to do the install and looks for a preseed style file.
> 
> Can you detail which method you were trying and which one you were having problems with?

This is trying to use the Legacy installer with preseed.cfg over UEFI
Step one:

![step1](https://user-images.githubusercontent.com/35745114/117159869-515ccc80-adc9-11eb-9624-aab3b4f24b09.png)

Here I try upload the preseed.cfg:

d-i debian-installer/locale string en_US.UTF-8

d-i clock-setup/utc boolean true
d-i clock-setup/utc-auto boolean true
d-i time/zone string Europe/Sofia

d-i base-installer/kernel/image string linux-generic
d-i grub-installer/only_debian boolean true

d-i console-setup/ask_detect boolean false
d-i keyboard-configuration/xkb-keymap select us
d-i keymap select us
d-i keyboard-configuration/layoutcode string us
d-i keyboard-configuration/modelcode string pc105
d-i keyboard-configuration/layout string "American English"

d-i netcfg/choose_interface select auto
d-i hw-detect/load_firmware boolean true
d-i netcfg/get_hostname string ubuntu


d-i partman-auto-lvm/guided_size string max
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman/choose_partition select finish
d-i partman/confirm_nooverwrite boolean true
d-i partman/confirm boolean true

d-i mirror/country string auto
d-i mirror/suite string focal
d-i mirror/http/hostname string bg.archive.ubuntu.com
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string


d-i pkgsel/include string openssh-server build-essential ubuntu-desktop vim terminator htop
d-i pkgsel/install-language-support boolean false
d-i pkgsel/upgrade select full-upgrade
d-i pkgsel/update-policy select unattended-upgrades
d-i pkgsel/language-packs multiselect en, bg





d-i passwd/root-login boolean true
d-i passwd/root-password-crypted password PASSHASH

d-i passwd/user-fullname string OPERATOR
d-i passwd/username string user
d-i passwd/user-password-crypted password PASSHASH

d-i passwd/user-default-groups user

d-i finish-install/reboot_in_progress note

step two:

I get this:

![step2](https://user-images.githubusercontent.com/35745114/117160285-a993ce80-adc9-11eb-9358-13636efbe67b.png)


It used to only prompt me for network adapters before and auto install everything it was told do.

**Comment by nickkostov** [comment]
> > I am having the same problem, using autoinstall with UEFI vm's, have not tried preseed
> 
> Ignore, UEFI netboot with autoinstall is working. My issue was the naming convention Ubuntu has for autoinstaller...URL needs to be the path which has two files, named user-data and meta-data

I tried the method with UEFI and just pointing the URL to the folder containing the autoinstall once --> I used the webserver public dir ( which could have lead to this result)

![step1 2](https://user-images.githubusercontent.com/35745114/117162164-38edb180-adcb-11eb-94fa-4f22c43a1b9b.png)

It just got stuck for that test I used meta-data and user-data from this repository: https://gist.github.com/anedward01/b68e00bb2dcfa4f1335cd4590cbc8484

( I did not have the time for the second test was making desks all day)

and is still stuck.

What I am looking for is a simple autoinstall for ubuntu --> desktop and a few packages, if you could advise what I do wrong and what is the correct way I will be really glad, the docs for autoinstall are not really clear for me or I just misunderstand something.

**Comment by andyloree** [comment]
> 
> 
> > > I am having the same problem, using autoinstall with UEFI vm's, have not tried preseed
> > 
> > 
> > Ignore, UEFI netboot with autoinstall is working. My issue was the naming convention Ubuntu has for autoinstaller...URL needs to be the path which has two files, named user-data and meta-data
> 
> I tried the method with UEFI and just pointing the URL to the folder containing the autoinstall once --> I used the webserver public dir ( which could have lead to this result)
> 
> ![step1 2](https://user-images.githubusercontent.com/35745114/117162164-38edb180-adcb-11eb-94fa-4f22c43a1b9b.png)
> 
> It just got stuck for that test I used meta-data and user-data from this repository: https://gist.github.com/anedward01/b68e00bb2dcfa4f1335cd4590cbc8484
> 
> ( I did not have the time for the second test was making desks all day)
> 
> and is still stuck.
> 
> What I am looking for is a simple autoinstall for ubuntu --> desktop and a few packages, if you could advise what I do wrong and what is the correct way I will be really glad, the docs for autoinstall are not really clear for me or I just misunderstand something.

The VM console on the right shows you are the live ISO download, which is before the autoinstall or preseed part of installation.  What is the memory size of the VM you are using?  The live ISO actually has to load into memory before the installer, could be your VM doesn't have enough memory.  With Hyper-V, I also noticed I could not use "dynamic memory" allocation for the VM, which is a typical default.  I was able to get a 3GB VM on hyper-v to boot, not sure how much lower you can go.

**Comment by nickkostov** [comment]
> the live ISO download, which is before the autoinstall or preseed part of installation. What is the memory size of the VM you are using? The live ISO actually has to load into memory before the installer, could be your VM doesn't have enough memory. With Hyper-V,

I understand what you are saying. I am using really small amounts of RAM I suppose. I use my VMs with 1GB. I will try to set them up with 3/4GB and see if this is going to make it happen.

**Comment by antonym** [comment]
Yeah, one of the reasons I preferred the Debian style installer kernels.  Ubuntu dropped that support for netbooting with the lightweight installer kernels, so now you have to load the entire ISO into ram now during the initrd load.

**Comment by nickkostov** [comment]
> Yeah, one of the reasons I preferred the Debian style installer kernels. Ubuntu dropped that support for netbooting with the lightweight installer kernels, so now you have to load the entire ISO into ram now during the initrd load.

I knew something was off with the drop for the installers but that big of a change is terrible. It almost looks like a downgrade instead of upgrade. If we are not really happy like that I will suggest to switch to Fedora or Debian. At least they are still working with the old once and they do not seem to go in that direction, correct me if I am wrong its real hard to track all distros these days.

**Comment by antonym** [comment]
Yeah, so far the others haven't changed yet.  This is where I posted about the Ubuntu changes, feel free to let them know your feelings upstream:

https://github.com/netbootxyz/netboot.xyz/discussions/729

**Comment by nickkostov** [comment]
> > > > I am having the same problem, using autoinstall with UEFI vm's, have not tried preseed
> > > 
> > > 
> > > Ignore, UEFI netboot with autoinstall is working. My issue was the naming convention Ubuntu has for autoinstaller...URL needs to be the path which has two files, named user-data and meta-data
> > 
> > 
> > I tried the method with UEFI and just pointing the URL to the folder containing the autoinstall once --> I used the webserver public dir ( which could have lead to this result)
> > ![step1 2](https://user-images.githubusercontent.com/35745114/117162164-38edb180-adcb-11eb-94fa-4f22c43a1b9b.png)
> > It just got stuck for that test I used meta-data and user-data from this repository: https://gist.github.com/anedward01/b68e00bb2dcfa4f1335cd4590cbc8484
> > ( I did not have the time for the second test was making desks all day)
> > and is still stuck.
> > What I am looking for is a simple autoinstall for ubuntu --> desktop and a few packages, if you could advise what I do wrong and what is the correct way I will be really glad, the docs for autoinstall are not really clear for me or I just misunderstand something.
> 
> The VM console on the right shows you are the live ISO download, which is before the autoinstall or preseed part of installation. What is the memory size of the VM you are using? The live ISO actually has to load into memory before the installer, could be your VM doesn't have enough memory. With Hyper-V, I also noticed I could not use "dynamic memory" allocation for the VM, which is a typical default. I was able to get a 3GB VM on hyper-v to boot, not sure how much lower you can go.

Hey there I am going to test another configuration which will do it in the following manner:
I will try to autoinstall it over a VM with 4GB RAM. 
I will create a folder one the webserver that will store the meta-data and user-data.
Hopefully it will work. 
I will post the config I used.

**Comment by nickkostov** [comment]
> > > > I am having the same problem, using autoinstall with UEFI vm's, have not tried preseed
> > > 
> > > 
> > > Ignore, UEFI netboot with autoinstall is working. My issue was the naming convention Ubuntu has for autoinstaller...URL needs to be the path which has two files, named user-data and meta-data
> > 
> > 
> > I tried the method with UEFI and just pointing the URL to the folder containing the autoinstall once --> I used the webserver public dir ( which could have lead to this result)
> > ![step1 2](https://user-images.githubusercontent.com/35745114/117162164-38edb180-adcb-11eb-94fa-4f22c43a1b9b.png)
> > It just got stuck for that test I used meta-data and user-data from this repository: https://gist.github.com/anedward01/b68e00bb2dcfa4f1335cd4590cbc8484
> > ( I did not have the time for the second test was making desks all day)
> > and is still stuck.
> > What I am looking for is a simple autoinstall for ubuntu --> desktop and a few packages, if you could advise what I do wrong and what is the correct way I will be really glad, the docs for autoinstall are not really clear for me or I just misunderstand something.
> 
> The VM console on the right shows you are the live ISO download, which is before the autoinstall or preseed part of installation. What is the memory size of the VM you are using? The live ISO actually has to load into memory before the installer, could be your VM doesn't have enough memory. With Hyper-V, I also noticed I could not use "dynamic memory" allocation for the VM, which is a typical default. I was able to get a 3GB VM on hyper-v to boot, not sure how much lower you can go.

I have tried once again without any success. Could advise with your way of auto-installing, I saw that desktop is not supported and tried to install using the packages option -->  https://github.com/nickkostov/autoinstall/blob/main/autoinstall-subiquity/docs.md ( you can check out both the files used and the whole thing and what else I tried)

**Comment by nickkostov** [comment]
@antonym why I am not able to preseed via the Legacy one?

**Comment by andyloree** [comment]
> I have tried once again without any success. Could advise with your way of auto-installing, I saw that desktop is not supported and tried to install using the packages option --> https://github.com/nickkostov/autoinstall/blob/main/autoinstall-subiquity/docs.md ( you can check out both the files used and the whole thing and what else I tried)

Where is it stopping?  If it is still during the ISO download as in your earlier screencap, the issue is not autoinstall, its your VM configuration and/or hypervisor.  In the case of Hyper-V, I had to disable dynamic memory.  I am not familiar enough with virtualbox to help troubleshoot.

**Comment by nickkostov** [comment]
> > I have tried once again without any success. Could advise with your way of auto-installing, I saw that desktop is not supported and tried to install using the packages option --> https://github.com/nickkostov/autoinstall/blob/main/autoinstall-subiquity/docs.md ( you can check out both the files used and the whole thing and what else I tried)
> 
> Where is it stopping? If it is still during the ISO download as in your earlier screencap, the issue is not autoinstall, its your VM configuration and/or hypervisor. In the case of Hyper-V, I had to disable dynamic memory. I am not familiar enough with virtualbox to help troubleshoot.

I will check if there are such options in vbox
It is not even stopping it directly gets me the graphical installator.

**Comment by nickkostov** [comment]
I figured it out, so much fuss for nothing I had the ubuntu menu misconfigured. Updated the menus and reverted the change. Now it works. Preseeds work. I can sleep well now. Do you have any idea when will be the full deprication of the preseeds in order to know how much time I have before we need to work it out?

**Comment by antonym** [comment]
20.04 LTS marked the transition to autoinstall, so preseeds will probably work until that LTS is EOL unless Ubuntu removes it sooner than later.  Glad you got things figured out though!
