### ISSUE TITLE
Distro Request: Guix System

### ISSUE THREAD

**Issue by jgarte** [netbootxyz/netboot.xyz#888]
http://guix.gnu.org/

https://www.youtube.com/watch?v=iBaqOK75cho

**Comment by thelamer** [comment]
The distribution would have to be forked off of a popular distro we have hacked https booting support into or in itself have the ability to be booted off the internet. 
As it stands this project only has the ability to load initrd/kernel off TFTP with NFS support, no pulling in a squash and running a live environment from a web endpoint. 

Basically this is a super custom non forked distro, and unless they directly add support to boot off http/https endpoints we will not be able to support this in an ipxe environment like ours.
