### ISSUE TITLE
Can you add a menu  "priority=low"  for ubuntu legacy installer ? 

### ISSUE THREAD

**Issue by Remonli** [netbootxyz/netboot.xyz#900]
Hello,

I noticed the  "priority=low"  was switched back to  "priority=critical" for ubuntu legacy installer, does it conflict with
preseeds install ? 

Is it possible to add one more menu for "priority=low" like debian installer does ? This is really very useful as you can
do much more customization during installation if choose expert mode "priority=low" .

Thank you and looking forward good news.

**Comment by IceCodeNew** [comment]
not stale.
