### ISSUE TITLE
Enable Wireless support on iPXE

### ISSUE THREAD

**Issue by samip5** [netbootxyz/netboot.xyz#909]
**Is your feature request related to a problem? Please describe.**
Not able to use iPXE to boot wirelessly as well

**Describe the solution you'd like**
WPA2 encryption and wireless as a whole support enabled in iPXE that are being generated by ansible.

**Describe alternatives you've considered**
None

**Comment by samip5** [comment]
Nope

**Comment by antonym** [comment]
The build of iPXE should have those enabled already so they can be loaded if need be.  If someone has the equipment to mock this up into a wrapper script we can look into it.
