### ISSUE TITLE
Ubuntu 20.04 and PopOS 20.04 LTS Live Boot images fail to load squashfs image

### ISSUE THREAD

**Issue by ndebruin** [netbootxyz/netboot.xyz#918]
Booting from the hosted `netboot.xyz` instance and attempting to load the Ubuntu or PopOS 20.04 Live Images lead to failure, and dropping into an `initramfs` shell.

It seems to be that `curl` is failing to grab the squashfs image with the error message:
```
curl: (23) Failed writing body (<varying number between boots> != 16384)
```

Screenshot attached of attempted boot to Ubuntu 20.04 Live Image.

![Screenshot from 2021-06-28 14-33-08](https://user-images.githubusercontent.com/73964478/123686448-cffc4600-d81d-11eb-9b64-d250379d4aa0.png)

**Comment by thelamer** [comment]
How much ram you have on that setup? 
Squashfs images are stored in a ramdisk which is half of the available memory on the machine. 
Those squashes are big too, prob need a machine with 8 gigs min to support booting these Live CDs.

**Comment by ndebruin** [comment]
I was originally attempting on a VM with 4GB of RAM. Bumping it up to 8GB got them both to work, thanks!
