### ISSUE TITLE
Does not work on Compaq Armada M700

### ISSUE THREAD

**Issue by TyrfingMjolnir** [netbootxyz/netboot.xyz#95]
Does not work on Compaq Armada M700 128MB RAM,
menu loads,
I choose linux,
the following shows up:

---

linux.ipxe... ok
http://boot.netboot.xyz/sigs/linux.ipxe.sig... ok
Could not verify: Permission denied (http://ipxe.org/0216eb3c)
Error occured, press any key to return to menu ...

---

At this point in time the keyboard does not work.

**Comment by antonym** [comment]
Maybe try disabling signatures on the main menu and see if you can get any further?
