### ISSUE TITLE
Add support for proxy DHCP

### ISSUE THREAD

**Issue by notepass** [netbootxyz/netboot.xyz#952]
**Is your feature request related to a problem? Please describe.**
While setting up a netboot server, I had to use a DHCP proxy to inject the boot server IP into the network. This had to be done, as my DHCP server has no support for setting the "next-server" option. When now booting the netboot.xyz instance, it tried to access the .ipxe files not from my tftp server, but from the server provided by my root DHCP. As there was no tftp server running, all requests timed out (although the normal menu showed up). To reproduce this, the docker container in the repo "samdbmg/dhcp-netboot.xyz" can be used, as that starts up a dnsmasq dhcp proxy.

**Describe the solution you'd like**
When a DHCP proxy exist, netboot.xyz should detect it and honor it in some way. It is a bit hard for me to say in which way would be the best, but I would think of something like this:
* Check if next-server is set
  * If no, check if proxydhcp/next-server is set. If yes, use that to access .ipxe files
  * If yes, check if proxydhcp/next-server is set. If yes, show a prompt telling the user that the proxy-provided server is used instead of the server provided by to root dhcp. 
    * But also give the user  a prompt to override this (e.g. by pressing e or something) 
    * Additionally, a ipxe file could be accessed on the root dhcp provided server (e.g. proxy-dhcp-vars.ipxe) which could set default vars to override any of this behaviour

**Describe alternatives you've considered**
N/A

**Additional context**
I'm currently trying to implement this in a fork. If you would consider adding this feature, I might be able to implement it or submit a PR for it.

**Comment by notepass** [comment]
Created PR #953  to implement this feature

**Comment by antonym** [comment]
Looks to be functioning now with a few changes.  Going to close this out but feel free to test with the development endpoint and binaries:

https://s3.amazonaws.com/dev.boot.netboot.xyz/cf44496e311bf2bf597856b22a2b1368d961ef76/index.html
