### ISSUE TITLE
centos 8.*  failed to open file initrd.magic

### ISSUE THREAD

**Issue by ninetian** [netbootxyz/netboot.xyz#987]
try install got this

![boot_fail](https://user-images.githubusercontent.com/2613794/132185170-63edd495-c89f-4dd6-b05e-f78a519d0d87.jpg)

**Comment by ninetian** [comment]
download latest versoins is working now
thanks

**Comment by antonym** [comment]
Cool, yeah that was a feature recently added in upstream iPXE so updating it will let it work.
