### ISSUE TITLE
Please add support for hrmpf

### ISSUE THREAD

**Issue by BrassyPanache** [netbootxyz/netboot.xyz#993]
The hrmpf rescue system is built on Void Linux.  I couldn't see it mentioned in the list of supported distributions or the issue tracker so I thought I'd add a request here.

The website: https://github.com/leahneukirchen/hrmpf

Thanks - I really appreciate netboot.xyz!

**Comment by antonym** [comment]
We had looked into Void Linux in the past but I don't think they were interested in supporting our initiative:

https://github.com/netbootxyz/netboot.xyz/issues/617
https://github.com/void-linux/void-mklive/issues/97

There's not a lot of docs yet but open to looking into it if they've made it more netboot friendly.

**Comment by BrassyPanache** [comment]
I've just made a request for the required changes to hrmpf.  As the project has different aims to the Void Live ISO it may be something that the maintainer is interested in supporting.

**Comment by leahneukirchen** [comment]
As mentioned in https://github.com/leahneukirchen/hrmpf/issues/18#issuecomment-919140607 it seems adding livenet just works---is there anything more I need to do than cut a release with dracut livenet enabled?

**Comment by leahneukirchen** [comment]
I made a new release that should be suitable for livenet booting: https://github.com/leahneukirchen/hrmpf/releases/tag/v20210914

**Comment by antonym** [comment]
Thanks for the quick response and turn around... I was able to get it booting using these flags:

```
#!ipxe
imgfree
kernel http://10.0.100.10:8080/hrmpf-boot/vmlinuz root=live:http://10.0.100.10:8080/hrmpf-boot/squashfs.img ro rd.luks=0 rd.md=0 rd.dm=0 loglevel=6 initrd=initrd.magic
initrd http://10.0.100.10:8080/hrmpf-boot/initrd
boot
```
<img width="799" alt="Screen Shot 2021-09-14 at 9 23 26 AM" src="https://user-images.githubusercontent.com/245007/133275683-32a95a90-6cd2-4499-b44f-a82975014c06.png">

Just checking to see if the remaining booted properly as it's my first time booting it.  I'll work on turning it into a menu option later this week.

**Comment by leahneukirchen** [comment]
That booted, but something else broke the boot later... try Ctrl-C to see if it goes on.

A completely booted hrmpf looks like this:

![2021-09-14-163527_1024x789_scrot](https://user-images.githubusercontent.com/139/133277991-2ed1aeea-b1de-4ffe-b725-038bc25aa588.png)

**Comment by leahneukirchen** [comment]
The CD-ROM kernel parameters are btw:

```
                root=live:CDLABEL=VOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 gpt add_efi_memmap vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 loglevel=6 printk.time=1 consoleblank=0 net.ifnames=0
```

I'd recommend to keep them (except for root= ofc).

**Comment by antonym** [comment]
K, updated to those, but still get the emergency shell.  But if I exit, it does resume boot.

**Comment by leahneukirchen** [comment]
Yep, that's a Void glitch due to the thin LVM your disks have... not a problem I think.

**Comment by antonym** [comment]
Menu is added and can be tried out via the Development endpoint via Utilities menu.

**Comment by leahneukirchen** [comment]
I get a 403 https://ipxe.org/err/0216e4 trying to download from github, what's wrong there? The path looks correct.

**Comment by antonym** [comment]
Github releases require us to use https, so I would check to make sure time is synced on whatever is booting.  Some virtual machine also struggle with having enough entropy occasionally.  I tested with a VM in Proxmox and it seemed to at least load correctly.

**Comment by antonym** [comment]
Also, I had to hit CTRL-D twice in order to actually get the end screen as a future note:
![Screen Shot 2021-09-15 at 10 04 47 AM](https://user-images.githubusercontent.com/245007/133459280-8eed7a4e-e18a-493c-8f28-ae44b6325493.png)

I ended up resetting my scratch disk and then it booted normally, so I must have had some cruft on that disk it wasn't liking.
