### ISSUE TITLE
Ubuntu 20.04 needs to be updated

### ISSUE THREAD

**Issue by vrelk** [netbootxyz/netboot.xyz#995]
**Describe the bug**
Ubuntu 20.04 (Subiquity) under Linux network installs needs to be updated from 20.04.2 to 20.04.3, as the old ISO file has been removed from `http://releases.ubuntu.com/focal/`, which results in a 404 error during boot.

**Comment by antonym** [comment]
You may have outdated code, latest release resolves this.  Make sure you are at least on 2.0.47 or using the hosted version.

**Comment by vrelk** [comment]
> 
> 
> You may have outdated code, latest release resolves this. Make sure you are at least on 2.0.47 or using the hosted version.

The ISO file was downloaded from `https://boot.netboot.xyz/ipxe/netboot.xyz.iso` about an hour ago at this point.

**Comment by antonym** [comment]
Are you using the docker container on your network?  Latest versions on boot.netboot.xyz are all 20.04.3.

```
~ % curl -s https://boot.netboot.xyz/ubuntu.ipxe | grep version_number
set version_number 20.04.3
set version_number 21.04
isset ${dhcp-server} && set netboot_params ip=dhcp url=http://releases.ubuntu.com/${codename}/ubuntu-${version_number}-live-server-${os_arch}.iso || set netboot_params
```

**Comment by Keno** [comment]
I ran into the same issue. I wasn't using dhcp, so it was attempting to use the interactive_netmount functionality. However, that functionality appears to have a bug on the LTS point releases. I have filed an appropriate issue upstream here: https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1948884
